#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Esperando PostgreSQL..."
python3 manage.py wait_for_db --settings=config.settings.local

echo "Aplicando migraciones..."
python3 manage.py migrate --settings=config.settings.local

echo "Collecting static..."
python3 manage.py collectstatic --noinput --settings=config.settings.local

echo "Iniciando Django DEV server..."

exec python3 manage.py runserver 0.0.0.0:8000 \
    --settings=config.settings.local

