# Generated by Django 5.2.8 on 2026-05-05 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personas",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registroactividades",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="personas",
            name="unique_dni",
        ),
        migrations.RemoveConstraint(
            model_name="personas",
            name="unique_cuil",
        ),
        migrations.RemoveIndex(
            model_name="personas",
            name="personas_apellid_44f564_idx",
        ),
        migrations.RemoveField(
            model_name="personas",
            name="f_nac",
        ),
        migrations.RemoveField(
            model_name="personas",
            name="telefono_tipo",
        ),
        migrations.RemoveField(
            model_name="registroactividades",
            name="designacion",
        ),
        migrations.RemoveField(
            model_name="registroactividades",
            name="t_designacion",
        ),
        migrations.AlterField(
            model_name="personas",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("PASIVO", "Pasivo")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personas",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?\\d[\\d\\s\\-]{7,18}$",
                        message="Número de teléfono inválido",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="telefono_normalizado",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="personas",
            name="usuario_creacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="usuario_modificacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="categoria",
            field=models.CharField(
                choices=[("DOCENTE", "Docente"), ("NO DOCENTE", "No Docente")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="cueanexo",
            field=models.CharField(db_index=True, editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bnhpersonas.personas"
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="usuario_creacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="usuario_modificacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
