# Generated by Django 5.1.1 on 2025-08-26 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cueanexo",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_cueanexo",
                                message="El CUEANEXO debe comenzar con 22 y tener sólo dígitos (9 en total, sin puntos ni guiones).",
                                regex="^22\\d{7}$",
                            )
                        ],
                    ),
                ),
                ("apellido_nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ConsultaSGE",
                "verbose_name_plural": "ConsultasSGE",
                "db_table": "consultas_sge",
                "managed": True,
            },
        ),
    ]
