# Generated by Django 5.1.1 on 2025-08-28 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta",
            options={
                "verbose_name": "ConsultaSGE",
                "verbose_name_plural": "ConsultasSGE",
            },
        ),
        migrations.AddField(
            model_name="consulta",
            name="nivel_modalidad",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primario", "Primario"),
                    ("Secundario", "Secundario"),
                    ("Adultos - Primario", "Adultos - Primario"),
                    ("Adultos - Secundario", "Adultos - Secundario"),
                    ("Especial", "Especial"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consulta",
            name="regional",
            field=models.CharField(
                choices=[
                    ("R.E. 1", "R.E. 1"),
                    ("R.E. 2", "R.E. 2"),
                    ("R.E. 3", "R.E. 3"),
                    ("R.E. 4-A", "R.E. 4-A"),
                    ("R.E. 4-B", "R.E. 4-B"),
                    ("R.E. 5", "R.E. 5"),
                    ("R.E. 6", "R.E. 6"),
                    ("R.E. 7", "R.E. 7"),
                    ("R.E. 8-A", "R.E. 8-A"),
                    ("R.E. 8-B", "R.E. 8-B"),
                    ("R.E. 9", "R.E. 9"),
                    ("R.E. 10-A", "R.E. 10-A"),
                    ("R.E. 10-B", "R.E. 10-B"),
                    ("R.E. 10-C", "R.E. 10-C"),
                    ("SUB. R.E. 1-A", "SUB. R.E. 1-A"),
                    ("SUB. R.E. 1-B", "SUB. R.E. 1-B"),
                    ("SUB. R.E. 2", "SUB. R.E. 2"),
                    ("SUB. R.E. 3", "SUB. R.E. 3"),
                    ("SUB. R.E. 5", "SUB. R.E. 5"),
                ],
                default=1,
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consulta",
            name="sge_modulo",
            field=models.CharField(
                choices=[
                    ("SGE-USUARIOS", "SGE-USUARIOS"),
                    ("SGE-TITULACIONES", "SGE-TITULACIONES"),
                    ("SGE-SECCIONES", "SGE-SECCIONES"),
                    ("SGE-ASISTENCIA", "SGE-ASISTENCIA"),
                    ("SGE-CALIFICACIONES", "SGE-CALIFICACIONES"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consulta",
            name="cueanexo",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cueanexo",
                        message="El CUEANEXO debe comenzar con 22 y tener 9 dígitos sin puntos ni guiones.",
                        regex="^22\\d{7}$",
                    )
                ],
            ),
        ),
    ]
