# Generated by Django 5.1.1 on 2025-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0002_alter_consulta_options_consulta_nivel_modalidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="estado",
            field=models.CharField(default="Pendiente", max_length=20),
        ),
    ]
