# Generated by Django 5.1.1 on 2025-08-29 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0003_consulta_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="estado_fecha",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consulta",
            name="estado_usuario",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="sge_modulo",
            field=models.CharField(
                choices=[
                    ("USUARIOS", "USUARIOS"),
                    ("TITULACIONES", "TITULACIONES"),
                    ("SECCIONES", "SECCIONES"),
                    ("ASISTENCIA", "ASISTENCIA"),
                    ("CALIFICACIONES", "CALIFICACIONES"),
                ],
                max_length=30,
            ),
        ),
    ]
