# Generated by Django 5.1.1 on 2025-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0004_consulta_estado_fecha_consulta_estado_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="estado_usuario",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
