# Generated by Django 5.1.1 on 2025-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0005_alter_consulta_estado_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="sge_rol",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "DIRECTOR"),
                    ("SECRETARIO", "SECRETARIO"),
                    ("MAESTRO/PROFESOR", "MAESTRO/PROFESOR"),
                    ("AUXILIAR DOCENTE", "AUXILIAR DOCENTE"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
