# Generated by Django 5.1.1 on 2025-08-29 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0006_consulta_sge_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="apellido_nombre",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Solo se permiten letras y espacios, sin puntos, comas ni otros caracteres.",
                        regex="^[A-Z\\s]+$",
                    )
                ],
            ),
        ),
    ]
