# Generated by Django 5.1.1 on 2025-08-29 18:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0007_alter_consulta_apellido_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultaRenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cueanexo",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_cueanexo",
                                message="El CUEANEXO debe comenzar con 22 y tener 9 dígitos sin puntos ni guiones.",
                                regex="^22\\d{7}$",
                            )
                        ],
                    ),
                ),
                (
                    "regional",
                    models.CharField(
                        choices=[
                            ("R.E. 1", "R.E. 1"),
                            ("R.E. 2", "R.E. 2"),
                            ("R.E. 3", "R.E. 3"),
                            ("R.E. 4-A", "R.E. 4-A"),
                            ("R.E. 4-B", "R.E. 4-B"),
                            ("R.E. 5", "R.E. 5"),
                            ("R.E. 6", "R.E. 6"),
                            ("R.E. 7", "R.E. 7"),
                            ("R.E. 8-A", "R.E. 8-A"),
                            ("R.E. 8-B", "R.E. 8-B"),
                            ("R.E. 9", "R.E. 9"),
                            ("R.E. 10-A", "R.E. 10-A"),
                            ("R.E. 10-B", "R.E. 10-B"),
                            ("R.E. 10-C", "R.E. 10-C"),
                            ("SUB. R.E. 1-A", "SUB. R.E. 1-A"),
                            ("SUB. R.E. 1-B", "SUB. R.E. 1-B"),
                            ("SUB. R.E. 2", "SUB. R.E. 2"),
                            ("SUB. R.E. 3", "SUB. R.E. 3"),
                            ("SUB. R.E. 5", "SUB. R.E. 5"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "renpe_modulo",
                    models.CharField(
                        choices=[
                            ("ACCESO", "ACCESO"),
                            ("VALIDACIONES", "VALIDACIONES"),
                            ("OTROS", "OTROS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "apellido_nombre",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo se permiten letras y espacios, sin puntos, comas ni otros caracteres.",
                                regex="^[A-Z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "estado_usuario",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "estado_fecha",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "ConsultaRENPE",
                "verbose_name_plural": "ConsultasRENPE",
                "db_table": "consultas_renpe",
            },
        ),
    ]
