# Generated by Django 5.1.1 on 2025-08-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0008_consultarenpe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="sge_modulo",
            field=models.CharField(
                choices=[
                    ("ALERTAS", "ALERTAS"),
                    ("ALUMNOS", "ALUMNOS"),
                    ("ASISTENCIA", "ASISTENCIA"),
                    ("CALIFICACIONES", "CALIFICACIONES"),
                    ("CURSADA", "CURSADA"),
                    ("EVENTOS", "EVENTOS"),
                    ("PROMOCIONES", "PROMOCIONES"),
                    ("REPORTES", "REPORTES"),
                    ("TITULACIONES", "TITULACIONES"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="sge_rol",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "DIRECTOR"),
                    ("SECRETARIO", "SECRETARIO"),
                    ("MAESTRO/PROFESOR", "MAESTRO/PROFESOR"),
                    ("AUXILIAR DOCENTE/PRECEPTOR", "AUXILIAR DOCENTE/PRECEPTOR"),
                ],
                max_length=50,
            ),
        ),
    ]
