# Generated by Django 5.1.1 on 2025-09-15 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0009_alter_consulta_sge_modulo_alter_consulta_sge_rol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "ConsultaSGE",
                "verbose_name_plural": "ConsultasSGE",
            },
        ),
    ]
