# Generated by Django 5.2.8 on 2025-11-17 18:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0010_alter_consulta_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultaDocentesRenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "cuil",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "El CUIL debe contener solo números."
                            ),
                            django.core.validators.MinLengthValidator(
                                10, "El CUIL debe tener al menos 10 dígitos."
                            ),
                            django.core.validators.MaxLengthValidator(
                                11, "El CUIL debe tener como máximo 11 dígitos."
                            ),
                        ],
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("DOCENTE", "DOCENTE"), ("NO DOCENTE", "NO DOCENTE")],
                        max_length=50,
                    ),
                ),
                (
                    "cuenta_miargentina",
                    models.CharField(
                        choices=[("SÍ", "SÍ"), ("NO", "NO")], max_length=3
                    ),
                ),
                (
                    "ingreso_miargentina",
                    models.CharField(
                        choices=[("SÍ", "SÍ"), ("NO", "NO")], max_length=3
                    ),
                ),
                (
                    "reseteo_contraseña_miargentina",
                    models.CharField(
                        choices=[("SÍ", "SÍ"), ("NO", "NO")], max_length=3
                    ),
                ),
                (
                    "formulario_sin_miargentina",
                    models.CharField(
                        choices=[("SÍ", "SÍ"), ("NO", "NO")], max_length=3
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "estado_usuario",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "estado_fecha",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="adjuntos/"),
                ),
            ],
            options={
                "verbose_name": "ConsultaDocenteRENPE",
                "verbose_name_plural": "ConsultasDocentesRENPE",
                "db_table": "consultas_docentes_renpe",
            },
        ),
    ]
