# Generated by Django 4.2.5 on 2024-06-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_acceso", models.DateTimeField(auto_now_add=True)),
                ("url_acceso", models.CharField(max_length=255)),
                ("metodo_http", models.CharField(max_length=10)),
                ("ip_usuario", models.CharField(max_length=45)),
                ("agente_usuario", models.CharField(max_length=255)),
                ("tiempo_carga_pagina", models.FloatField(blank=True, null=True)),
                ("tiempo_respuesta_servidor", models.FloatField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
