# Generated by Django 5.1.1 on 2025-04-04 19:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlumnosSecundariaDiagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("anio", models.CharField(max_length=25, verbose_name="Año")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Alumno Secundaria Diagnostico",
                "verbose_name_plural": "Alumnos Secundaria Diagnosticos",
                "db_table": "Alumno_Secundaria_Diagnostico",
            },
        ),
        migrations.CreateModel(
            name="ConceptosLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacidad",
                    models.CharField(max_length=50, verbose_name="Capacidad"),
                ),
                (
                    "contenido",
                    models.CharField(max_length=150, verbose_name="Contenido"),
                ),
                (
                    "puntaje_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje Maximo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto Lengua",
                "verbose_name_plural": "Conceptos Lengua",
                "db_table": "Concepto_Lengua",
            },
        ),
        migrations.CreateModel(
            name="ExamenLenguaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("anio", models.CharField(max_length=25, verbose_name="Año")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "p1",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("7.00"), "7.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 1",
                    ),
                ),
                (
                    "p2",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("7.00"), "7.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 2",
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 3",
                    ),
                ),
                (
                    "p4",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("6.00"), "6.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 4",
                    ),
                ),
                (
                    "p5",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("7.00"), "7.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 5",
                    ),
                ),
                (
                    "p6",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("7.00"), "7.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 6",
                    ),
                ),
                (
                    "p7",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 7",
                    ),
                ),
                (
                    "p8",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(12.5),
                        ],
                        verbose_name="Item 8",
                    ),
                ),
                (
                    "p9",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("6.00"), "6.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 9",
                    ),
                ),
                (
                    "p10",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("6.00"), "6.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 10",
                    ),
                ),
                (
                    "p11",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 11",
                    ),
                ),
                (
                    "p12",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 12",
                    ),
                ),
                (
                    "p13",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 13",
                    ),
                ),
                (
                    "p14",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("5.00"), "5.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 14",
                    ),
                ),
                (
                    "p15",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 15",
                    ),
                ),
                (
                    "p16",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(12.5),
                        ],
                        verbose_name="Item 16",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Lengua Alumno",
                "verbose_name_plural": "Examen Lengua Alumnos",
                "db_table": "Examen_Lengua_Alumnos",
            },
        ),
    ]
