# Generated by Django 5.1.1 on 2025-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptoslengua",
            name="cod",
            field=models.CharField(default=1, max_length=2, verbose_name="Codigo"),
            preserve_default=False,
        ),
    ]
