# Generated by Django 5.1.1 on 2025-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0002_conceptoslengua_cod"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptoslengua",
            name="pregunta",
            field=models.IntegerField(default=1, verbose_name="Pregunta"),
            preserve_default=False,
        ),
    ]
