# Generated by Django 5.1.1 on 2025-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0003_conceptoslengua_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptoslengua",
            name="cod",
            field=models.CharField(max_length=3, verbose_name="Codigo"),
        ),
    ]
