# Generated by Django 5.1.1 on 2025-04-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0004_alter_conceptoslengua_cod"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAsistenciaLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ausentes", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Registro Asistencia Lengua",
                "verbose_name_plural": "Registros Asistencia Lengua",
                "db_table": "Registro_Asistencia_Lengua",
            },
        ),
        migrations.AlterField(
            model_name="alumnossecundariadiagnostico",
            name="dni",
            field=models.CharField(max_length=8, unique=True, verbose_name="DNI"),
        ),
    ]
