# Generated by Django 5.1.1 on 2025-04-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0005_registroasistencialengua_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencialengua",
            name="total_registros",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
