# Generated by Django 5.1.1 on 2025-04-05 16:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0006_registroasistencialengua_total_registros"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptosMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.IntegerField(verbose_name="Pregunta")),
                (
                    "capacidad",
                    models.CharField(max_length=50, verbose_name="Capacidad"),
                ),
                (
                    "contenido",
                    models.CharField(max_length=150, verbose_name="Contenido"),
                ),
                ("eje", models.CharField(max_length=50, verbose_name="Eje")),
                (
                    "puntaje_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje Maximo"
                    ),
                ),
                ("cod", models.CharField(max_length=3, verbose_name="Codigo")),
            ],
            options={
                "verbose_name": "Concepto Matematica",
                "verbose_name_plural": "Conceptos Matematica",
                "db_table": "Concepto_Matematica",
            },
        ),
        migrations.CreateModel(
            name="ExamenMatematicaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("anio", models.CharField(max_length=25, verbose_name="Año")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "p1",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("3.00"), "3.00"),
                            (Decimal("10.00"), "10.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 1",
                    ),
                ),
                (
                    "p2",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 2",
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("2.00"), "2.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 3",
                    ),
                ),
                (
                    "p4",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("5.00"), "5.00"),
                            (Decimal("10.00"), "10.00"),
                            (Decimal("15.00"), "15.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 4",
                    ),
                ),
                (
                    "p5",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("4.00"), "4.00"),
                            (Decimal("7.00"), "7.00"),
                            (Decimal("10.00"), "10.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 5",
                    ),
                ),
                (
                    "p6",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("3.00"), "3.00"),
                            (Decimal("6.00"), "6.00"),
                            (Decimal("8.00"), "8.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 6",
                    ),
                ),
                (
                    "p7",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("6.00"), "6.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 7",
                    ),
                ),
                (
                    "p8",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("10.00"), "10.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 8",
                    ),
                ),
                (
                    "p9",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("5.00"), "5.00"),
                            (Decimal("10.00"), "10.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 9",
                    ),
                ),
                (
                    "p10",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("7.00"), "7.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 10",
                    ),
                ),
                (
                    "p11",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 11",
                    ),
                ),
                (
                    "p12",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0.00"),
                            (Decimal("2.00"), "2.00"),
                            (Decimal("4.00"), "4.00"),
                            (Decimal("5.00"), "5.00"),
                        ],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 12",
                    ),
                ),
                (
                    "p13",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("4.00"), "4.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 13",
                    ),
                ),
                (
                    "p14",
                    models.DecimalField(
                        choices=[(Decimal("0.00"), "0.00"), (Decimal("5.00"), "5.00")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Item 14",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Matematica Alumno",
                "verbose_name_plural": "Examen Matematica Alumnos",
                "db_table": "Examen_Matematica_Alumnos",
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistenciaMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ausentes", models.PositiveIntegerField()),
                ("total_registros", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Registro Asistencia Matematica",
                "verbose_name_plural": "Registros Asistencia Matematica",
                "db_table": "Registro_Asistencia_Matematica",
            },
        ),
    ]
