# Generated by Django 5.1.1 on 2025-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0007_conceptosmatematica_examenmatematicaalumno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalSecundarias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_escuelas", models.PositiveIntegerField(verbose_name="Total")),
                ("estatal", models.PositiveIntegerField(verbose_name="Estatal")),
                ("privado", models.PositiveIntegerField(verbose_name="Privada")),
                (
                    "gestion_social",
                    models.PositiveIntegerField(verbose_name="Gestion Social"),
                ),
                ("urbano", models.PositiveIntegerField(verbose_name="Urbano")),
                (
                    "rural_disperso",
                    models.PositiveIntegerField(verbose_name="Rural_Disperso"),
                ),
                (
                    "rural_aglomerado",
                    models.PositiveIntegerField(verbose_name="Rural_Aglomerado"),
                ),
            ],
            options={
                "verbose_name": "Total Secundaria",
                "verbose_name_plural": "Total Secundarias",
                "db_table": "total_secundarias",
                "managed": False,
            },
        ),
    ]
