# Generated by Django 5.1.1 on 2025-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0008_totalsecundarias"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscuelasSecundarias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("region_loc", models.CharField(max_length=255, verbose_name="Region")),
                ("sector", models.CharField(max_length=255, verbose_name="Sector")),
                ("ambito", models.CharField(max_length=255, verbose_name="Ambito")),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
                (
                    "lengua",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Lengua"
                    ),
                ),
                (
                    "matematica",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Matematica"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escuela Secundaria",
                "verbose_name_plural": "Escuelas Secundarias",
                "db_table": "escuelas_secundarias",
            },
        ),
    ]
