# Generated by Django 5.1.1 on 2025-04-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0009_escuelassecundarias"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencialengua",
            name="region",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registroasistenciamatematica",
            name="region",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
