# Generated by Django 5.1.1 on 2025-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0010_registroasistencialengua_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examenlenguaalumno",
            name="discapacidad",
            field=models.CharField(
                choices=[("SI", "SI"), ("NO", "NO")],
                default=1,
                max_length=2,
                verbose_name="Discapacidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenlenguaalumno",
            name="etnia",
            field=models.CharField(
                choices=[
                    ("NO", "NO"),
                    ("QOM", "QOM"),
                    ("WICHI", "WICHI"),
                    ("MOQOIT", "MOQOIT"),
                ],
                default=1,
                max_length=10,
                verbose_name="Etnia",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaalumno",
            name="discapacidad",
            field=models.CharField(
                choices=[("SI", "SI"), ("NO", "NO")],
                default=1,
                max_length=2,
                verbose_name="Discapacidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaalumno",
            name="etnia",
            field=models.CharField(
                choices=[
                    ("NO", "NO"),
                    ("QOM", "QOM"),
                    ("WICHI", "WICHI"),
                    ("MOQOIT", "MOQOIT"),
                ],
                default=1,
                max_length=10,
                verbose_name="Etnia",
            ),
            preserve_default=False,
        ),
    ]
