# Generated by Django 5.1.1 on 2025-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0011_examenlenguaalumno_discapacidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteComunicacionMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Comunicacion Matematica",
                "verbose_name_plural": "Cortes Comunicacion Matematica",
                "db_table": "corte_comunicacion_matematica",
            },
        ),
        migrations.CreateModel(
            name="CorteEscrituraLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Escritura Lengua",
                "verbose_name_plural": "Cortes Escritura Lengua",
                "db_table": "corte_escritura_lengua",
            },
        ),
        migrations.CreateModel(
            name="CorteEvaluarLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Evaluar Lengua",
                "verbose_name_plural": "Cortes Evaluar Lengua",
                "db_table": "corte_evaluar_lengua",
            },
        ),
        migrations.CreateModel(
            name="CorteExtraerLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Extraer Lengua",
                "verbose_name_plural": "Cortes Extraer Lengua",
                "db_table": "corte_extraer_lengua",
            },
        ),
        migrations.CreateModel(
            name="CorteGeneralLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte General Lengua",
                "verbose_name_plural": "Cortes Generales Lengua",
                "db_table": "corte_general_lengua",
            },
        ),
        migrations.CreateModel(
            name="CorteGeneralMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte General Matematica",
                "verbose_name_plural": "Cortes Generales Matematica",
                "db_table": "corte_general_matematica",
            },
        ),
        migrations.CreateModel(
            name="CorteInterpretarLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Interpretar Lengua",
                "verbose_name_plural": "Cortes Interpretar Lengua",
                "db_table": "corte_interpretar_lengua",
            },
        ),
        migrations.CreateModel(
            name="CorteReconocimientoMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Reconocimiento Matematica",
                "verbose_name_plural": "Cortes Reconocimiento Matematica",
                "db_table": "corte_reconocimiento_matematica",
            },
        ),
        migrations.CreateModel(
            name="CorteResolucionMatematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_desempeño",
                    models.CharField(max_length=50, verbose_name="Nivel Desempeño"),
                ),
                (
                    "punto_corte",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Punto Corte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte Resolucion Matematica",
                "verbose_name_plural": "Cortes Resolucion Matematica",
                "db_table": "corte_resolucion_matematica",
            },
        ),
    ]
