# Generated by Django 5.1.1 on 2025-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativchaco",
            "0012_cortecomunicacionmatematica_corteescrituralengua_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaEscrituraLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Escritura Lengua",
                "verbose_name_plural": "Vistas Escritura Lengua",
                "db_table": "v_escritura_lengua",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaEvaluarLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Evaluar Lengua",
                "verbose_name_plural": "Vistas Evaluar Lengua",
                "db_table": "v_evaluar_lengua",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaExtraerLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Extraer Lengua",
                "verbose_name_plural": "Vistas Extraer Lengua",
                "db_table": "v_extraer_lengua",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaGeneralLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista General Lengua",
                "verbose_name_plural": "Vistas Generales Lengua",
                "db_table": "v_gral_lengua",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaInterpretarLengua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Interpretar Lengua",
                "verbose_name_plural": "Vistas Interpretar Lengua",
                "db_table": "v_interpretar_lengua",
                "managed": False,
            },
        ),
    ]
