# Generated by Django 5.1.1 on 2025-04-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativchaco",
            "0014_vistacomunicacionmatematica_vistageneralmatematica_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaComunicacionMatematicaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Comunicacion Matematica Region",
                "verbose_name_plural": "Vistas Comunicacion Matematica Region",
                "db_table": "v_comunicacion_matematica_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaEscrituraLenguaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Escritura Lengua Region",
                "verbose_name_plural": "Vistas Escritura Lengua Region",
                "db_table": "v_escritura_lengua_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaEvaluarLenguaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Evaluar Lengua Region",
                "verbose_name_plural": "Vistas Evaluar Lengua Region",
                "db_table": "v_evaluar_lengua_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaExtraerLenguaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Extraer Lengua Region",
                "verbose_name_plural": "Vistas Extraer Lengua Region",
                "db_table": "v_extraer_lengua_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaGeneralLenguaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista General Lengua Region",
                "verbose_name_plural": "Vistas Generales Lengua Region",
                "db_table": "v_gral_lengua_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaGeneralMatematicaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista General Matematica Region",
                "verbose_name_plural": "Vistas Generales Matematica Region",
                "db_table": "v_gral_matematica_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaInterpretarLenguaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Interpretar Lengua Region",
                "verbose_name_plural": "Vistas Interpretar Lengua Region",
                "db_table": "v_interpretar_lengua_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaReconocimientoMatematicaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Reconocimiento Matematica Region",
                "verbose_name_plural": "Vistas Reconocimiento Matematica Region",
                "db_table": "v_reconocimiento_matematica_reg",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="vistaresolucionmatematica",
            options={
                "managed": False,
                "verbose_name": "Vista Resolucion Matematica Region",
                "verbose_name_plural": "Vistas Resolucion Matematica Region",
            },
        ),
        migrations.AlterModelTable(
            name="vistaresolucionmatematica",
            table="v_resolucion_matematica_reg",
        ),
    ]
