# Generated by Django 5.1.1 on 2025-04-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0015_vistacomunicacionmatematicareg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaResolucionMatematicaReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Resolucion Matematica Region",
                "verbose_name_plural": "Vistas Resolucion Matematica Region",
                "db_table": "v_resolucion_matematica_reg",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="vistaresolucionmatematica",
            options={
                "managed": False,
                "verbose_name": "Vista Resolucion Matematica",
                "verbose_name_plural": "Vistas Resolucion Matematica",
            },
        ),
        migrations.AlterModelTable(
            name="vistaresolucionmatematica",
            table="v_resolucion_matematica",
        ),
    ]
