# Generated by Django 5.1.1 on 2025-04-23 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0016_vistaresolucionmatematicareg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumnosPrimariaFluidez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("grado", models.CharField(max_length=25, verbose_name="Año")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Alumno Primaria Fluidez",
                "verbose_name_plural": "Alumnos Primaria Fluidez",
                "db_table": "Alumno_Primaria_Fluidez",
            },
        ),
        migrations.CreateModel(
            name="EscuelasPrimarias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("region_loc", models.CharField(max_length=255, verbose_name="Region")),
                ("sector", models.CharField(max_length=255, verbose_name="Sector")),
                ("ambito", models.CharField(max_length=255, verbose_name="Ambito")),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
                (
                    "segundo",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Segundo"
                    ),
                ),
                (
                    "tercero",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Tercero"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escuela Primaria",
                "verbose_name_plural": "Escuelas Primarias",
                "db_table": "escuelas_primarias",
            },
        ),
        migrations.CreateModel(
            name="ExamenFluidezSegundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("grado", models.CharField(max_length=25, verbose_name="Año")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("QOM", "QOM"),
                            ("WICHI", "WICHI"),
                            ("MOQOIT", "MOQOIT"),
                        ],
                        max_length=10,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "velocidad",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Velocidad",
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Precisión",
                    ),
                ),
                (
                    "prosodia",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                        verbose_name="Prosodia",
                    ),
                ),
                (
                    "p1",
                    models.CharField(
                        choices=[("NR", "NR"), ("a", "a"), ("b", "b"), ("c", "c")],
                        verbose_name="Pregunta 1",
                    ),
                ),
                (
                    "p2",
                    models.CharField(
                        choices=[("NR", "NR"), ("a", "a"), ("b", "b"), ("c", "c")],
                        verbose_name="Pregunta 2",
                    ),
                ),
                (
                    "p3",
                    models.CharField(
                        choices=[("NR", "NR"), ("a", "a"), ("b", "b"), ("c", "c")],
                        verbose_name="Pregunta 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Fluidez Segundo",
                "verbose_name_plural": "Examenes Fluidez Segundo",
                "db_table": "Examen_Fluidez_Segundo",
            },
        ),
    ]
