# Generated by Django 5.1.1 on 2025-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0019_examenfluideztercero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaComprensionSegundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Comprension Segundo",
                "verbose_name_plural": "Vistas Comprension Segundo",
                "db_table": "v_comprension_segundo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaComprensionSegundoReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Comprension Segundo Region",
                "verbose_name_plural": "Vistas Comprension Segundo Region",
                "db_table": "v_comprension_segundo_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaComprensionTercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Comprension Tercero",
                "verbose_name_plural": "Vistas Comprension Tercero",
                "db_table": "v_comprension_tercero",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaComprensionTerceroReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Comprension Tercero Region",
                "verbose_name_plural": "Vistas Comprension Tercero Region",
                "db_table": "v_comprension_tercero_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaPrecisionSegundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Precision Segundo",
                "verbose_name_plural": "Vistas Precision Segundo",
                "db_table": "v_precision_segundo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaPrecisionSegundoReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Precision Segundo Region",
                "verbose_name_plural": "Vistas Precision Segundo Region",
                "db_table": "v_precision_segundo_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaPrecisionTercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Precision Tercero",
                "verbose_name_plural": "Vistas Precision Tercero",
                "db_table": "v_precision_tercero",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaPrecisionTerceroReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Precision Tercero Region",
                "verbose_name_plural": "Vistas Precision Tercero Region",
                "db_table": "v_precision_tercero_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaProsodiaSegundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Prosodia Segundo",
                "verbose_name_plural": "Vistas Prosodia Segundo",
                "db_table": "v_prosodia_segundo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaProsodiaSegundoReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Prosodia Segundo Region",
                "verbose_name_plural": "Vistas Prosodia Segundo Region",
                "db_table": "v_prosodia_segundo_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaProsodiaTercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Prosodia Tercero",
                "verbose_name_plural": "Vistas Prosodia Tercero",
                "db_table": "v_prosodia_tercero",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaProsodiaTerceroReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Prosodia Tercero Region",
                "verbose_name_plural": "Vistas Prosodia Tercero Region",
                "db_table": "v_prosodia_tercero_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaVelocidadSegundo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Velocidad Segundo",
                "verbose_name_plural": "Vistas Velocidad Segundo",
                "db_table": "v_velocidad_segundo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaVelocidadSegundoReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Velocidad Segundo Region",
                "verbose_name_plural": "Vistas Velocidad Segundo Region",
                "db_table": "v_velocidad_segundo_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaVelocidadTercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Velocidad Tercero",
                "verbose_name_plural": "Vistas Velocidad Tercero",
                "db_table": "v_velocidad_tercero",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaVelocidadTerceroReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Región")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Velocidad Tercero Region",
                "verbose_name_plural": "Vistas Velocidad Tercero Region",
                "db_table": "v_velocidad_tercero_reg",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="examenfluidezsegundo",
            name="p1",
        ),
        migrations.RemoveField(
            model_name="examenfluidezsegundo",
            name="p2",
        ),
        migrations.RemoveField(
            model_name="examenfluidezsegundo",
            name="p3",
        ),
        migrations.RemoveField(
            model_name="examenfluideztercero",
            name="p1",
        ),
        migrations.RemoveField(
            model_name="examenfluideztercero",
            name="p2",
        ),
        migrations.RemoveField(
            model_name="examenfluideztercero",
            name="p3",
        ),
    ]
