# Generated by Django 5.1.1 on 2025-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativchaco",
            "0020_vistacomprensionsegundo_vistacomprensionsegundoreg_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenfluidezsegundo",
            name="division",
            field=models.CharField(max_length=1, verbose_name="División"),
        ),
        migrations.AlterField(
            model_name="examenfluidezsegundo",
            name="grado",
            field=models.CharField(default="2", max_length=1, verbose_name="Grado"),
        ),
        migrations.AlterField(
            model_name="examenfluideztercero",
            name="division",
            field=models.CharField(max_length=1, verbose_name="División"),
        ),
        migrations.AlterField(
            model_name="examenfluideztercero",
            name="grado",
            field=models.CharField(default="3", max_length=1, verbose_name="Grado"),
        ),
    ]
