# Generated by Django 5.1.1 on 2025-05-28 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0021_alter_examenfluidezsegundo_division_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscuelasPrimariasMatematica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("region_loc", models.CharField(max_length=255, verbose_name="Region")),
                ("sector", models.CharField(max_length=255, verbose_name="Sector")),
                ("ambito", models.CharField(max_length=255, verbose_name="Ambito")),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
                (
                    "quinto",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Segundo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escuela Primaria Matematica",
                "verbose_name_plural": "Escuelas Primarias Matematica",
                "db_table": "escuelas_primarias_matematica",
            },
        ),
        migrations.CreateModel(
            name="ExamenMatematicaQuintoGrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "grado",
                    models.CharField(default="5", max_length=1, verbose_name="Grado"),
                ),
                ("division", models.CharField(max_length=1, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("QOM", "QOM"),
                            ("WICHI", "WICHI"),
                            ("MOQOIT", "MOQOIT"),
                        ],
                        max_length=10,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "preg1a",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 1 A",
                    ),
                ),
                (
                    "preg1b",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 1 B",
                    ),
                ),
                (
                    "preg1c",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 1 C",
                    ),
                ),
                (
                    "preg1d",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 1 D",
                    ),
                ),
                (
                    "preg2a",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 2 A",
                    ),
                ),
                (
                    "preg2b",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 2 B",
                    ),
                ),
                (
                    "preg2c",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 2 C",
                    ),
                ),
                (
                    "preg2d",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 2 D",
                    ),
                ),
                (
                    "preg3a",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 3 A",
                    ),
                ),
                (
                    "preg3b",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 3 B",
                    ),
                ),
                (
                    "preg3c",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 3 C",
                    ),
                ),
                (
                    "preg3d",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)],
                        verbose_name="Pregunta 3 D",
                    ),
                ),
                (
                    "preg4a",
                    models.CharField(
                        choices=[
                            ("CIRCULO", "CIRCULO"),
                            ("CUADRADO", "CUADRADO"),
                            ("TRIANGULO", "TRIANGULO"),
                            ("RECTANGULO", "RECTANGULO"),
                            ("ROMBO", "ROMBO"),
                            ("TRAPECIO", "TRAPECIO"),
                            ("NINGUNA", "NINGUNA"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 A",
                    ),
                ),
                (
                    "preg4b",
                    models.CharField(
                        choices=[
                            ("TRES", "TRES"),
                            ("CUATRO", "CUATRO"),
                            ("CINCO", "CINCO"),
                            ("SEIS", "SEIS"),
                            ("SIETE", "SIETE"),
                            ("OCHO", "OCHO"),
                            ("NUEVE", "NUEVE"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 B",
                    ),
                ),
                (
                    "preg4c",
                    models.CharField(
                        choices=[
                            ("TRES", "TRES"),
                            ("CUATRO", "CUATRO"),
                            ("CINCO", "CINCO"),
                            ("SEIS", "SEIS"),
                            ("SIETE", "SIETE"),
                            ("OCHO", "OCHO"),
                            ("NUEVE", "NUEVE"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 C",
                    ),
                ),
                (
                    "preg4d",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Pregunta 4 D",
                    ),
                ),
                (
                    "preg5",
                    models.CharField(
                        choices=[
                            ("CIRCULO", "CIRCULO"),
                            ("CUADRADO", "CUADRADO"),
                            ("TRIANGULO", "TRIANGULO"),
                            ("RECTANGULO", "RECTANGULO"),
                            ("ROMBO", "ROMBO"),
                            ("TRAPECIO", "TRAPECIO"),
                            ("NINGUNA", "NINGUNA"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 5",
                    ),
                ),
                (
                    "preg6a",
                    models.CharField(
                        choices=[
                            ("CIRCULO", "CIRCULO"),
                            ("CUADRADO", "CUADRADO"),
                            ("TRIANGULO", "TRIANGULO"),
                            ("RECTANGULO", "RECTANGULO"),
                            ("ROMBO", "ROMBO"),
                            ("TRAPECIO", "TRAPECIO"),
                            ("NINGUNA", "NINGUNA"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 6 A",
                    ),
                ),
                (
                    "preg6b",
                    models.CharField(
                        choices=[
                            ("CIRCULO", "CIRCULO"),
                            ("CUADRADO", "CUADRADO"),
                            ("TRIANGULO", "TRIANGULO"),
                            ("RECTANGULO", "RECTANGULO"),
                            ("ROMBO", "ROMBO"),
                            ("TRAPECIO", "TRAPECIO"),
                            ("NINGUNA", "NINGUNA"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 6 B",
                    ),
                ),
                (
                    "preg6c",
                    models.CharField(
                        choices=[
                            ("CIRCULO", "CIRCULO"),
                            ("CUADRADO", "CUADRADO"),
                            ("TRIANGULO", "TRIANGULO"),
                            ("RECTANGULO", "RECTANGULO"),
                            ("ROMBO", "ROMBO"),
                            ("TRAPECIO", "TRAPECIO"),
                            ("NINGUNA", "NINGUNA"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 6 C",
                    ),
                ),
                (
                    "preg7a",
                    models.CharField(
                        choices=[
                            ("CENTIMETRO", "CENTIMETRO"),
                            ("METRO", "METRO"),
                            ("KILOMETRO", "KILOMETRO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 7 A",
                    ),
                ),
                (
                    "preg7b",
                    models.CharField(
                        choices=[
                            ("CENTIMETRO", "CENTIMETRO"),
                            ("METRO", "METRO"),
                            ("KILOMETRO", "KILOMETRO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 7 B",
                    ),
                ),
                (
                    "preg7c",
                    models.CharField(
                        choices=[
                            ("CENTIMETRO", "CENTIMETRO"),
                            ("METRO", "METRO"),
                            ("KILOMETRO", "KILOMETRO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 7 C",
                    ),
                ),
                (
                    "preg7d",
                    models.CharField(
                        choices=[
                            ("CENTIMETRO", "CENTIMETRO"),
                            ("METRO", "METRO"),
                            ("KILOMETRO", "KILOMETRO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 7 D",
                    ),
                ),
                (
                    "preg8a",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 8 A",
                    ),
                ),
                (
                    "preg8b",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 8 B",
                    ),
                ),
                (
                    "preg8c",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 8 C",
                    ),
                ),
                (
                    "preg8d",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 8 D",
                    ),
                ),
                (
                    "preg9a",
                    models.CharField(
                        choices=[
                            ("COMPLETO", "COMPLETO"),
                            ("ALTERNATIVA", "ALTERNATIVA"),
                            ("SIN UNIDAD MONETARIA", "SIN UNIDAD MONETARIA"),
                        ],
                        max_length=50,
                        verbose_name="Pregunta 9 Planteo",
                    ),
                ),
                (
                    "preg9b",
                    models.CharField(
                        choices=[
                            ("SOLUCION A", "SOLUCION A"),
                            ("SOLUCION B", "SOLUCION B"),
                            ("SIN UNIDAD MONETARIA", "SIN UNIDAD MONETARIA"),
                        ],
                        max_length=50,
                        verbose_name="Pregunta 9 Solución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Matematica Quinto Grado",
                "verbose_name_plural": "Examenes Matematica Quinto Grado",
                "db_table": "Examen_Matematica_Quinto_Grado",
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistenciaMatematicaQuinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("region", models.CharField(max_length=25)),
                ("ausentes", models.PositiveIntegerField()),
                ("total_registros", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Registro Asistencia Matematica Quinto",
                "verbose_name_plural": "Registros Asistencia Matematica Quinto",
                "db_table": "Registro_Asistencia_Matematica_Quinto",
            },
        ),
    ]
