# Generated by Django 5.1.1 on 2025-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0022_escuelasprimariasmatematica_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespuestaCorrectaMatematicaQuinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=50, verbose_name="Pregunta")),
                (
                    "respuesta_correcta",
                    models.CharField(max_length=50, verbose_name="Respuesta Correcta"),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Puntaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Correcta Matematica Quinto",
                "verbose_name_plural": "Respuestas Correctas Matematica Quinto",
                "db_table": "respuesta_correcta_matematica_quinto",
            },
        ),
    ]
