# Generated by Django 5.1.1 on 2025-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0023_respuestacorrectamatematicaquinto"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaResultadoMatematicaQuinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "grado",
                    models.CharField(default="5", max_length=1, verbose_name="Grado"),
                ),
                ("division", models.CharField(max_length=1, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("QOM", "QOM"),
                            ("WICHI", "WICHI"),
                            ("MOQOIT", "MOQOIT"),
                        ],
                        max_length=10,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "puntaje_preg1a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 A"
                    ),
                ),
                (
                    "puntaje_preg1b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 B"
                    ),
                ),
                (
                    "puntaje_preg1c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 C"
                    ),
                ),
                (
                    "puntaje_preg1d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 D"
                    ),
                ),
                (
                    "puntaje_preg2a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 A"
                    ),
                ),
                (
                    "puntaje_preg2b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 B"
                    ),
                ),
                (
                    "puntaje_preg2c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 C"
                    ),
                ),
                (
                    "puntaje_preg2d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 D"
                    ),
                ),
                (
                    "puntaje_preg3a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 A"
                    ),
                ),
                (
                    "puntaje_preg3b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 B"
                    ),
                ),
                (
                    "puntaje_preg3c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 C"
                    ),
                ),
                (
                    "puntaje_preg3d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 D"
                    ),
                ),
                (
                    "puntaje_preg4a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 A"
                    ),
                ),
                (
                    "puntaje_preg4b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 B"
                    ),
                ),
                (
                    "puntaje_preg4c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 C"
                    ),
                ),
                (
                    "puntaje_preg4d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 D"
                    ),
                ),
                (
                    "puntaje_preg5",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 5"
                    ),
                ),
                (
                    "puntaje_preg6a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 6 A"
                    ),
                ),
                (
                    "puntaje_preg6b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 6 B"
                    ),
                ),
                (
                    "puntaje_preg6c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 6 C"
                    ),
                ),
                (
                    "puntaje_preg7a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 A"
                    ),
                ),
                (
                    "puntaje_preg7b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 B"
                    ),
                ),
                (
                    "puntaje_preg7c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 C"
                    ),
                ),
                (
                    "puntaje_preg7d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 D"
                    ),
                ),
                (
                    "puntaje_preg8a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 A"
                    ),
                ),
                (
                    "puntaje_preg8b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 B"
                    ),
                ),
                (
                    "puntaje_preg8c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 C"
                    ),
                ),
                (
                    "puntaje_preg8d",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 D"
                    ),
                ),
                (
                    "puntaje_preg9a",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Pregunta 9 Planteo",
                    ),
                ),
                (
                    "puntaje_preg9b",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Pregunta 9 Solución",
                    ),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje Total"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Resultado Matematica Quinto Grado",
                "verbose_name_plural": "Vistas Resultados Matematica Quinto Grado",
                "db_table": "v_resultado_matematica_quinto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AlumnosPrimariaQuinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("grado", models.CharField(max_length=25, verbose_name="grado")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Alumno Primaria Quinto",
                "verbose_name_plural": "Alumnos Primaria Quinto",
                "db_table": "Alumno_Primaria_Quinto",
            },
        ),
    ]
