# Generated by Django 5.1.1 on 2025-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0024_vistaresultadomatematicaquinto_alumnosprimariaquinto"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaMatematicaQuinto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Matematica Quinto",
                "verbose_name_plural": "Vistas Matematica Quinto",
                "db_table": "v_matematica_quinto",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="examenmatematicaquintogrado",
            name="preg9a",
            field=models.CharField(
                choices=[
                    ("PLANTEO A", "PLANTEO A"),
                    ("PLANTEO B", "PLANTEO B"),
                    ("SIN UNIDAD MONETARIA", "SIN UNIDAD MONETARIA"),
                ],
                max_length=50,
                verbose_name="Pregunta 9 Planteo",
            ),
        ),
    ]
