# Generated by Django 5.1.1 on 2025-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0025_vistamatematicaquinto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaMatematicaSegundoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Matematica Segundo Anio",
                "verbose_name_plural": "Vistas Matematica Segundo Anio",
                "db_table": "v_matematica_segundo_anio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaResultadoMatematicaSegundoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "grado",
                    models.CharField(default="2", max_length=1, verbose_name="Grado"),
                ),
                ("division", models.CharField(max_length=1, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("QOM", "QOM"),
                            ("WICHI", "WICHI"),
                            ("MOQOIT", "MOQOIT"),
                        ],
                        max_length=10,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "puntaje_preg1a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 A"
                    ),
                ),
                (
                    "puntaje_preg1b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 1 B"
                    ),
                ),
                (
                    "puntaje_preg2a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 A"
                    ),
                ),
                (
                    "puntaje_preg2b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 2 B"
                    ),
                ),
                (
                    "puntaje_preg3a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 A"
                    ),
                ),
                (
                    "puntaje_preg3b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 B"
                    ),
                ),
                (
                    "puntaje_preg3c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 3 C"
                    ),
                ),
                (
                    "puntaje_preg4a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 A"
                    ),
                ),
                (
                    "puntaje_preg4b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 B"
                    ),
                ),
                (
                    "puntaje_preg4c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 4 C"
                    ),
                ),
                (
                    "puntaje_preg5a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 5 A"
                    ),
                ),
                (
                    "puntaje_preg5b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 5 B"
                    ),
                ),
                (
                    "puntaje_preg5c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 5 C"
                    ),
                ),
                (
                    "puntaje_preg6",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 6"
                    ),
                ),
                (
                    "puntaje_preg7a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 A"
                    ),
                ),
                (
                    "puntaje_preg7b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 7 B"
                    ),
                ),
                (
                    "puntaje_preg8a",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 A"
                    ),
                ),
                (
                    "puntaje_preg8b",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 B"
                    ),
                ),
                (
                    "puntaje_preg8c",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Pregunta 8 C"
                    ),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje Total"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Resultado Matematica Segundo Anio",
                "verbose_name_plural": "Vistas Resultados Matematica Segundo Anio",
                "db_table": "v_resultado_matematica_segundo_anio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AlumnosSegundoSecundaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("grado", models.CharField(max_length=25, verbose_name="grado")),
                ("division", models.CharField(max_length=5, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Alumno Segundo Secundaria",
                "verbose_name_plural": "Alumnos Segundo Secundaria",
                "db_table": "Alumno_Secundaria_Segundo",
            },
        ),
        migrations.CreateModel(
            name="EscuelasSecundariasMatematica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("region_loc", models.CharField(max_length=255, verbose_name="Region")),
                ("sector", models.CharField(max_length=255, verbose_name="Sector")),
                ("ambito", models.CharField(max_length=255, verbose_name="Ambito")),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
                (
                    "segundo",
                    models.CharField(
                        default="PENDIENTE", max_length=255, verbose_name="Segundo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escuela Secundaria Matematica",
                "verbose_name_plural": "Escuelas Secundarias Matematica",
                "db_table": "escuelas_secundarias_matematica",
            },
        ),
        migrations.CreateModel(
            name="ExamenMatematicaSegundoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "grado",
                    models.CharField(default="5", max_length=1, verbose_name="Grado"),
                ),
                ("division", models.CharField(max_length=1, verbose_name="División")),
                ("region", models.CharField(max_length=25, verbose_name="Regional")),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("QOM", "QOM"),
                            ("WICHI", "WICHI"),
                            ("MOQOIT", "MOQOIT"),
                        ],
                        max_length=10,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "preg1a",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 1 A",
                    ),
                ),
                (
                    "preg1b",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 1 B",
                    ),
                ),
                (
                    "preg2a",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 2 A",
                    ),
                ),
                (
                    "preg2b",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 2 B",
                    ),
                ),
                (
                    "preg3a",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 3 A",
                    ),
                ),
                (
                    "preg3b",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 3 B",
                    ),
                ),
                (
                    "preg3c",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 3 C",
                    ),
                ),
                (
                    "preg4a",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 A",
                    ),
                ),
                (
                    "preg4b",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 B",
                    ),
                ),
                (
                    "preg4c",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 4 C",
                    ),
                ),
                (
                    "preg5a",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 5 A",
                    ),
                ),
                (
                    "preg5b",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 5 B",
                    ),
                ),
                (
                    "preg5c",
                    models.CharField(
                        choices=[("V", "V"), ("F", "F")],
                        max_length=1,
                        verbose_name="Pregunta 5 C",
                    ),
                ),
                (
                    "preg6",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 6",
                    ),
                ),
                (
                    "preg7a",
                    models.CharField(
                        choices=[
                            ("RESOLUCION-RESPUESTA", "RESOLUCION-RESPUESTA"),
                            ("RESOLUCION-SIN RESPUESTA", "RESOLUCION-SIN RESPUESTA"),
                        ],
                        max_length=60,
                        verbose_name="Pregunta 7 A",
                    ),
                ),
                (
                    "preg7b",
                    models.CharField(
                        choices=[
                            ("RESOLUCION-RESPUESTA", "RESOLUCION-RESPUESTA"),
                            ("RESOLUCION-SIN RESPUESTA", "RESOLUCION-SIN RESPUESTA"),
                        ],
                        max_length=60,
                        verbose_name="Pregunta 7 B",
                    ),
                ),
                (
                    "preg8a",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 8 Gráfico",
                    ),
                ),
                (
                    "preg8b",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 8 Desarrollo",
                    ),
                ),
                (
                    "preg8c",
                    models.CharField(
                        choices=[
                            ("CORRECTO", "CORRECTO"),
                            ("INCORRECTO", "INCORRECTO"),
                        ],
                        max_length=25,
                        verbose_name="Pregunta 8 Respuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Matematica Segundo Anio",
                "verbose_name_plural": "Examenes Matematica Segundo Anio",
                "db_table": "Examen_Matematica_Segundo_Anio",
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistenciaMatematicaSegundoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("region", models.CharField(max_length=25)),
                ("ausentes", models.PositiveIntegerField()),
                ("total_registros", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Registro Asistencia Matematica Segundo Anio",
                "verbose_name_plural": "Registros Asistencia Matematica Segundo Anio",
                "db_table": "Registro_Asistencia_Matematica_Segundo_Anio",
            },
        ),
        migrations.CreateModel(
            name="RespuestaCorrectaMatematicaSegundoAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=50, verbose_name="Pregunta")),
                (
                    "respuesta_correcta",
                    models.CharField(max_length=50, verbose_name="Respuesta Correcta"),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Puntaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Correcta Matematica Segundo Anio",
                "verbose_name_plural": "Respuestas Correctas Matematica Segundo Anio",
                "db_table": "respuesta_correcta_matematica_segundo_anio",
            },
        ),
        migrations.AlterField(
            model_name="escuelasprimariasmatematica",
            name="quinto",
            field=models.CharField(
                default="PENDIENTE", max_length=255, verbose_name="Quinto"
            ),
        ),
    ]
