# Generated by Django 5.1.1 on 2025-05-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0026_vistamatematicasegundoanio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenmatematicasegundoanio",
            name="grado",
            field=models.CharField(default="2", max_length=1, verbose_name="Grado"),
        ),
    ]
