# Generated by Django 5.1.1 on 2025-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0027_alter_examenmatematicasegundoanio_grado"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaMatematicaQuintoRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Region")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Matematica Quinto Regional",
                "verbose_name_plural": "Vistas Matematica Quinto Regional",
                "db_table": "v_resultado_matematica_quinto_reg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaMatematicaSegundoAnioRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=9, verbose_name="Region")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Porcentaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vista Matematica Segundo Anio Regional",
                "verbose_name_plural": "Vistas Matematica Segundo Anio Regional",
                "db_table": "v_resultado_matematica_segundo_anio_reg",
                "managed": False,
            },
        ),
    ]
