# Generated by Django 5.1.1 on 2025-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0028_vistamatematicaquintoregional_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg1a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg1b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg2a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg2b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg3a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg3b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg3c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg4a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg4b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg4c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg5a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg5b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg5c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg6",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg7a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg7b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicasegundoanio",
            name="preg8c",
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg1",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 1",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg10",
            field=models.CharField(
                choices=[
                    ("15", "15"),
                    ("10", "10"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 10",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg2",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("6", "6"),
                    ("3", "3"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 2",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg3",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 3",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg4",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("3", "3"),
                    ("2", "2"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 4",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg5",
            field=models.CharField(
                choices=[("10", "10"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 5",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg6a",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 6 A",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg6b",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 6 B",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg7",
            field=models.CharField(
                choices=[("10", "10"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 7",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicasegundoanio",
            name="preg9",
            field=models.CharField(
                choices=[("10", "10"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 9",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examenmatematicasegundoanio",
            name="preg8a",
            field=models.CharField(
                choices=[
                    ("5", "5"),
                    ("2.5", "2.5"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                max_length=25,
                verbose_name="Pregunta 8 A",
            ),
        ),
        migrations.AlterField(
            model_name="examenmatematicasegundoanio",
            name="preg8b",
            field=models.CharField(
                choices=[("10", "10"), ("0", "0"), ("Ausente", "Ausente")],
                max_length=25,
                verbose_name="Pregunta 8 B",
            ),
        ),
    ]
