# Generated by Django 5.1.1 on 2025-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativchaco", "0029_remove_examenmatematicasegundoanio_preg1a_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg1a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg1b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg1c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg1d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg2a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg2b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg2c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg2d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg3a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg3b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg3c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg3d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg4a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg4b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg4c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg4d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg6a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg6b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg6c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg7a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg7b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg7c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg7d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg8a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg8b",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg8c",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg8d",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg9a",
        ),
        migrations.RemoveField(
            model_name="examenmatematicaquintogrado",
            name="preg9b",
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg1",
            field=models.CharField(
                choices=[("3", "3"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 1",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg10",
            field=models.CharField(
                choices=[
                    ("15", "15"),
                    ("10", "10"),
                    ("5", "5"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 10",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg11",
            field=models.CharField(
                choices=[
                    ("15", "15"),
                    ("10", "10"),
                    ("5", "5"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 11",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg12",
            field=models.CharField(
                choices=[("16", "16"), ("8", "8"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 12",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg2",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 2",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg3",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 3",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg4",
            field=models.CharField(
                choices=[
                    ("6", "6"),
                    ("4", "4"),
                    ("2", "2"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 4",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg6",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 6",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg7",
            field=models.CharField(
                choices=[("5", "5"), ("0", "0"), ("Ausente", "Ausente")],
                default=1,
                max_length=25,
                verbose_name="Pregunta 7",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg8",
            field=models.CharField(
                choices=[
                    ("9", "9"),
                    ("6", "6"),
                    ("3", "3"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 8",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examenmatematicaquintogrado",
            name="preg9",
            field=models.CharField(
                choices=[
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("10", "10"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                default=1,
                max_length=25,
                verbose_name="Pregunta 9",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examenmatematicaquintogrado",
            name="preg5",
            field=models.CharField(
                choices=[
                    ("6", "6"),
                    ("4", "4"),
                    ("2", "2"),
                    ("0", "0"),
                    ("Ausente", "Ausente"),
                ],
                max_length=25,
                verbose_name="Pregunta 5",
            ),
        ),
    ]
