# Generated by Django 5.2.8 on 2026-07-07 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogos", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("cuit", models.CharField(max_length=20, unique=True)),
                ("contacto", models.CharField(blank=True, max_length=150, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Relevamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cueanexo", models.CharField(max_length=9)),
                ("cui", models.CharField(blank=True, max_length=20)),
                ("oferta", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_PROCESO", "En proceso"),
                            ("FINALIZADO", "Finalizado"),
                            ("OBSERVADO", "Observado"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                    ),
                ),
                (
                    "tipo_relevamiento",
                    models.CharField(
                        choices=[
                            ("INFRAESTRUCTURA", "Infraestructura"),
                            ("EQUIPAMIENTO", "Equipamiento"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "usuario_creador",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("finalizado", models.BooleanField(default=False)),
                ("fecha_finalizacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Relevamiento",
                "verbose_name_plural": "Relevamientos",
                "db_table": "sirtee_relevamientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("objeto_str", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CambioDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                (
                    "auditoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios",
                        to="sirtee.auditoriabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cambio",
                "verbose_name_plural": "Cambios",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sirtee.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hallazgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej.: Aula 4, Galería Norte, Cubierta Sector B",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("observacion_tecnica", models.TextField(blank=True, null=True)),
                ("recomendacion", models.TextField(blank=True, null=True)),
                (
                    "evidencia",
                    models.TextField(
                        blank=True, help_text="Fotos, links o documentos.", null=True
                    ),
                ),
                (
                    "usuario_responsable",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "area_afectada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.areaafectada",
                    ),
                ),
                (
                    "criticidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.criticidad",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.estadohallazgo",
                    ),
                ),
                (
                    "riesgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.riesgo",
                    ),
                ),
                (
                    "sistema_constructivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.sistemaconstructivo",
                    ),
                ),
                (
                    "tipo_hallazgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="catalogos.tipohallazgo",
                    ),
                ),
                (
                    "relevamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallazgos",
                        to="sirtee.relevamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hallazgo",
                "verbose_name_plural": "Hallazgos",
                "db_table": "sirtee_hallazgos",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Intervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REPARACION", "Reparación"),
                            ("REEMPLAZO", "Reemplazo"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("CONSTRUCCION", "Construcción"),
                            ("ADMINISTRATIVA", "Administrativa"),
                        ],
                        default="REPARACION",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("PAUSADA", "Pausada"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=30,
                    ),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "equipo_ejecutor",
                    models.CharField(
                        blank=True,
                        help_text="Empresa, cuadrilla o equipo responsable",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("fecha_estimada_fin", models.DateField(blank=True, null=True)),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("porcentaje_avance", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "hallazgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervenciones",
                        to="sirtee.hallazgo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervención",
                "verbose_name_plural": "Intervenciones",
                "db_table": "sirtee_intervenciones",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotObjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auditoria",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="sirtee.auditoriabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot",
                "verbose_name_plural": "Snapshots",
            },
        ),
    ]
