# Generated by Django 5.2.8 on 2026-07-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogos", "0001_initial"),
        ("sirtee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["razon_social"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.RenameField(
            model_name="empresa",
            old_name="activo",
            new_name="activa",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="nombre",
        ),
        migrations.AddField(
            model_name="empresa",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="localidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nombre_fantasia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="responsable",
            field=models.CharField(
                blank=True, help_text="Persona de contacto", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CONSTRUCTORA", "Constructora"),
                    ("SERVICIOS", "Servicios"),
                    ("PROVEEDOR", "Proveedor"),
                    ("OTRA", "Otra"),
                ],
                default="CONSTRUCTORA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="fuente_financiamiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervenciones",
                to="catalogos.fuentefinanciamiento",
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="organismo_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervenciones",
                to="catalogos.organismoresponsable",
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="prioridad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervenciones",
                to="catalogos.prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cuit",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="costo_estimado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="costo_real",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="equipo_ejecutor",
            field=models.CharField(
                blank=True,
                help_text="Empresa, cuadrilla o equipo ejecutor.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervenciones",
                to="catalogos.estadointervencion",
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="responsable",
            field=models.CharField(
                blank=True,
                help_text="Responsable directo de la intervención.",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervenciones",
                to="catalogos.tipointervencion",
            ),
        ),
        migrations.AlterModelTable(
            name="empresa",
            table="sirtee_empresas",
        ),
        migrations.DeleteModel(
            name="Contrato",
        ),
    ]
