# Generated by Django 5.2.8 on 2026-07-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirtee", "0002_alter_empresa_options_rename_activo_empresa_activa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="condicion_fiscal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="registro_empresa",
            field=models.CharField(
                blank=True, help_text="Registro o matrícula", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intervenciones",
                to="sirtee.empresa",
                verbose_name="Empresa ejecutora",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cuit",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="equipo_ejecutor",
            field=models.CharField(
                blank=True,
                help_text="Cuadrilla o equipo interno.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="responsable",
            field=models.CharField(
                blank=True,
                help_text="Responsable técnico o administrativo.",
                max_length=150,
                null=True,
            ),
        ),
    ]
