# Generated by Django 5.2.8 on 2026-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirtee", "0003_empresa_condicion_fiscal_empresa_registro_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cuit",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
