# Generated by Django 5.2.8 on 2026-07-08 12:56

import apps.sirtee.utils.upload
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogos", "0001_initial"),
        ("sirtee", "0004_alter_empresa_cuit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaHallazgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(
                        upload_to=apps.sirtee.utils.upload.upload_hallazgo
                    ),
                ),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("IMAGEN", "Imagen"),
                            ("DOCUMENTO", "Documento"),
                            ("VIDEO", "Video"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                (
                    "principal",
                    models.BooleanField(
                        default=False, help_text="Evidencia principal del hallazgo"
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evidencia de hallazgo",
                "verbose_name_plural": "Evidencias de hallazgos",
                "db_table": "sirtee_hallazgo_evidencias",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.RemoveField(
            model_name="hallazgo",
            name="evidencia",
        ),
        migrations.AddField(
            model_name="hallazgo",
            name="fecha_deteccion",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="hallazgo",
            name="referencia_espacial",
            field=models.CharField(
                blank=True,
                help_text="Ej: Eje B, columna 4, techo sector norte",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hallazgo",
            name="requiere_seguimiento",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="hallazgo",
            name="fecha_resolucion",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="hallazgo",
            name="titulo",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="hallazgo",
            name="usuario_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hallazgos_responsables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción técnica"),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intervenciones",
                to="sirtee.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="equipo_ejecutor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="hallazgo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervenciones",
                to="sirtee.hallazgo",
                verbose_name="Hallazgo asociado",
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="porcentaje_avance",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="responsable",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="cueanexo",
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="usuario_creador",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relevamientos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="intervencion",
            index=models.Index(
                fields=["estado", "fecha_inicio"], name="sirtee_inte_estado__752d79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervencion",
            index=models.Index(
                fields=["hallazgo"], name="sirtee_inte_hallazg_489543_idx"
            ),
        ),
        migrations.AddField(
            model_name="evidenciahallazgo",
            name="hallazgo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias",
                to="sirtee.hallazgo",
            ),
        ),
        migrations.AddField(
            model_name="evidenciahallazgo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidencias_hallazgos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
