# Generated by Django 5.2.8 on 2026-07-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirtee", "0005_evidenciahallazgo_remove_hallazgo_evidencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=30)),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "hallazgo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="sirtee.hallazgo",
                    ),
                ),
                (
                    "intervencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="sirtee.intervencion",
                    ),
                ),
                (
                    "relevamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="sirtee.relevamiento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento",
                "verbose_name_plural": "Seguimientos",
                "db_table": "sirtee_seguimientos",
                "ordering": ["-fecha"],
            },
        ),
    ]
