# Generated by Django 5.2.8 on 2026-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirtee", "0007_hallazgo_created_at_hallazgo_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevamiento",
            name="cui",
            field=models.JSONField(
                blank=True, default=list, verbose_name="CUI seleccionados"
            ),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="oferta",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ofertas seleccionadas"
            ),
        ),
    ]
