# Generated by Django 5.2.8 on 2026-07-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0017_modalidadnivelceic"),
        ("sirtee", "0008_alter_relevamiento_cui_alter_relevamiento_oferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="localidad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.localidades",
            ),
            preserve_default=False,
        ),
    ]
