# Generated by Django 5.2.8 on 2026-06-09 18:32

import apps.supervisa2.models.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABMSupervisores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[apps.supervisa2.models.validators.validate_phone],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[
                            apps.supervisa2.models.validators.validate_email_strict
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="cuil",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisor",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor",
                "verbose_name_plural": "Supervisores",
                "db_table": "supervisor_registro_supervisor",
            },
        ),
        migrations.CreateModel(
            name="ResponsableRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puede_crear_supervisores", models.BooleanField(default=True)),
                ("puede_modificar_supervisores", models.BooleanField(default=True)),
                ("puede_eliminar_supervisores", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("regiones", models.ManyToManyField(to="supervisa2.region")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable Regional",
                "verbose_name_plural": "Responsables Regionales",
                "db_table": "supervisor_registro_responsable_regional",
            },
        ),
        migrations.CreateModel(
            name="SupervisorRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supervisa2.region",
                    ),
                ),
                (
                    "responsable_alta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supervisor_registro.responsableregional",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_regionales",
                        to="supervisor_registro.abmsupervisores",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_registro_supervisor_regional",
                "unique_together": {("supervisor", "region")},
            },
        ),
        migrations.CreateModel(
            name="SupervisorSituacionRevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("vigente", models.BooleanField(default=True)),
                (
                    "situacion_revista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supervisa2.situacionrevista",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situaciones",
                        to="supervisor_registro.abmsupervisores",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_registro_supervisor_situacion",
            },
        ),
        migrations.CreateModel(
            name="SupervisorRegionalNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supervisa2.nivelmodalidad",
                    ),
                ),
                (
                    "supervisor_regional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveles",
                        to="supervisor_registro.supervisorregional",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_registro_supervisor_regional_nivel",
                "unique_together": {("supervisor_regional", "nivel")},
            },
        ),
        migrations.CreateModel(
            name="SupervisorRegionalOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9)),
                ("nom_est", models.CharField(max_length=255)),
                ("oferta", models.CharField(max_length=255)),
                ("acronimo", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                (
                    "supervisor_regional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="supervisor_registro.supervisorregional",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_registro_supervisor_regional_oferta",
                "unique_together": {("supervisor_regional", "cueanexo", "oferta")},
            },
        ),
    ]
