# Generated by Django 5.2.8 on 2026-06-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
        ("supervisor_registro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("TOGGLE", "TOGGLE"),
                            ("VIEW", "VIEW"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_log",
            },
        ),
        migrations.RenameField(
            model_name="supervisorsituacionrevista",
            old_name="vigente",
            new_name="activo",
        ),
        migrations.AddField(
            model_name="supervisorregionalnivel",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supervisorregionaloferta",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="supervisorregional",
            index=models.Index(
                fields=["supervisor", "region"], name="supervisor__supervi_be5647_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "object_id"], name="audit_log_model_n_c04ad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_log_user_id_835db7_idx"
            ),
        ),
    ]
