# Generated by Django 5.2.8 on 2026-08-14 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
        ("supervisor_registro", "0002_auditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsableregional",
            name="regiones",
            field=models.ManyToManyField(blank=True, to="supervisa2.region"),
        ),
        migrations.AlterField(
            model_name="responsableregional",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsable_regional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supervisorregional",
            name="responsable_alta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="altas_supervisores",
                to="supervisor_registro.responsableregional",
            ),
        ),
        migrations.AddIndex(
            model_name="abmsupervisores",
            index=models.Index(
                fields=["activo", "fecha_alta"], name="supervisor__activo_691c24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="responsableregional",
            index=models.Index(fields=["activo"], name="supervisor__activo_c6639e_idx"),
        ),
        migrations.AddIndex(
            model_name="supervisorregional",
            index=models.Index(
                fields=["region", "activo"], name="supervisor__region__b57747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorregional",
            index=models.Index(
                fields=["supervisor", "activo"], name="supervisor__supervi_954d9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorregionalnivel",
            index=models.Index(
                fields=["supervisor_regional", "activo"],
                name="supervisor__supervi_dccac1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorregionalnivel",
            index=models.Index(
                fields=["nivel", "activo"], name="supervisor__nivel_i_e92ab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorregionaloferta",
            index=models.Index(
                fields=["supervisor_regional", "activo"],
                name="supervisor__supervi_a643ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorregionaloferta",
            index=models.Index(
                fields=["cueanexo"], name="supervisor__cueanex_9071e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorsituacionrevista",
            index=models.Index(
                fields=["supervisor", "activo"], name="supervisor__supervi_052568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorsituacionrevista",
            index=models.Index(
                fields=["situacion_revista", "activo"],
                name="supervisor__situaci_e48e1f_idx",
            ),
        ),
    ]
