version: '3'

volumes:
  visor_local_postgres_data: {}
  visor_local_postgres_data_backups: {}
  

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: visor_local_django
    container_name: visor_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z      
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: visor_production_postgres
    container_name: visor_local_postgres
    volumes:
      - visor_local_postgres_data:/var/lib/postgresql/data:z
      - visor_local_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    ports:
      - "5433:5432"

  redis:
    image: redis
    container_name: visor_local_redis
    ports:
      - "6379:6379"

  
    