version: '3.8'

volumes:
  production_postgres_data_visor: {}
  production_postgres_data_backups_visor: {}
  production_traefik_visor: {}
  production_media_visor: {}
  production_redis_data: {}
  production_static_visor: {}   # 👈 NUEVO

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: visor_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    volumes:
      - production_static_visor:/app/productionfiles   # 👈 CAMBIO (antes bind mount)
      - production_media_visor:/app/media:Z
    command: /start
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: visor_production_django
    platform: linux/x86_64
    command: celery -A config worker -l info
    depends_on:
      - django
      - redis
    env_file:
      - ./.env
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: visor_production_django
    platform: linux/x86_64
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - django
      - redis
    env_file:
      - ./.env
    restart: unless-stopped