version: '3'

volumes:
  production_postgres_data_visor: {}
  production_postgres_data_backups_visor: {}
  production_traefik_visor: {} 
  production_media_visor: {}
  production_static_visor: {} 

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: visor_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
    env_file:
      - ./.env
    user: "www-data:www-data"
    volumes:
      - production_static_visor:/app/staticfiles
      - production_media_visor:/apps/media
    command: /start        
    
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: visor_production_postgres
    volumes:
      - production_postgres_data_visor:/var/lib/postgresql/data_visor:Z
      - production_postgres_data_backups_visor:/backups_visor:z      
    env_file:
      - ./.env   
    ports:
      - "5433:5432" 
          
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: visor_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik_visor:/etc/traefik/acme:z 
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`visoreducativochaco.com.ar`)"
      - "traefik.http.routers.django.entrypoints=http"
      - "traefik.http.routers.django-secure.entrypoints=https"
      - "traefik.http.routers.django-secure.rule=Host(`visoreducativochaco.com.ar`)"
      - "traefik.http.routers.django-secure.tls=true"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  nginx:
    image: nginx:latest
    depends_on:
      - django
    user: "www-data:www-data"
    volumes:
      - production_static_visor:/usr/share/nginx/html/static
      - production_media_visor:/usr/share/nginx/html/media
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
  
  
