version: '3'

volumes:
  production_postgres_data_visor: {}
  production_postgres_data_backups_visor: {}
  production_traefik_visor: {}
  production_nginx_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: visor_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
    env_file:
      - ./.env  
    volumes:
      - ./productionfiles:/app/productionfiles 
    command: /start        

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: visor_production_postgres
    volumes:
      - production_postgres_data_visor:/var/lib/postgresql/data_visor:Z
      - production_postgres_data_backups_visor:/backups_visor:z      
    env_file:
      - ./.env   
    ports:
      - "5433:5432" 
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile 
    image: visor_production_nginx
    depends_on:
      - django
    volumes:
      - production_nginx_data:/usr/share/nginx/html  
    ports:
      - "8080:80"
      - "8443:443"

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik_visor:/etc/traefik/acme:z 
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"   
    labels:
      - "traefik.http.routers.django.rule=Host(`visoreducativochaco.com.ar`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=le"
      - "traefik.http.services.django.loadbalancer.server.port=5000"
 

  
