# Generated by Django 5.2.14 on 2026-06-22 15:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VCapaUnicaOfertasAnt",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("nom_est", models.CharField(blank=True, max_length=255, null=True)),
                ("nro_est", models.CharField(blank=True, max_length=100, null=True)),
                ("acronimo", models.TextField(blank=True, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("ambito", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("region_loc", models.CharField(blank=True, max_length=100, null=True)),
                ("ref_loc", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                ("localidad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("resploc_cuitcuil", models.TextField(blank=True, null=True)),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Vista capa Ãºnica oferta",
                "verbose_name_plural": "Vista capa Ãºnica ofertas",
                "db_table": '"public"."v_capa_unica_ofertas_ant"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LocalizacionPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cueanexo",
                    models.CharField(
                        db_index=True,
                        help_text="CUEANEXO completo de 9 dÃ­gitos.",
                        max_length=20,
                        verbose_name="CUEANEXO",
                    ),
                ),
                (
                    "cuof",
                    models.CharField(blank=True, max_length=50, verbose_name="CUOF"),
                ),
                (
                    "cui",
                    models.CharField(blank=True, max_length=50, verbose_name="CUI"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "LocalizaciÃ³n POF",
                "verbose_name_plural": "Localizaciones POF",
                "db_table": '"reunidas_pof"."localizacion_pof"',
            },
        ),
        migrations.CreateModel(
            name="LoteCargaPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MODIFICACION", "ModificaciÃ³n"),
                            ("AFECTACION", "AfectaciÃ³n"),
                            ("DESAFECTACION", "DesafectaciÃ³n"),
                        ],
                        default="ALTA",
                        max_length=40,
                        verbose_name="Tipo de operaciÃ³n",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="ObservaciÃ³n"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de operaciÃ³n",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "localizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_carga",
                        to="reunidas_pof.localizacionpof",
                        verbose_name="LocalizaciÃ³n POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_carga_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de carga POF",
                "verbose_name_plural": "Lotes de carga POF",
                "db_table": '"reunidas_pof"."lote_carga_pof"',
            },
        ),
        migrations.CreateModel(
            name="CargoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ceic",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="CÃ³digo CEIC asociado al cargo.",
                        verbose_name="CEIC",
                    ),
                ),
                ("cargo", models.TextField(blank=True, verbose_name="Cargo")),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unidad_cantidad",
                    models.CharField(
                        choices=[
                            ("CARGO", "Cargo"),
                            ("HORA_CATEDRA", "Hora cÃ¡tedra"),
                            ("Otro", "Otro"),
                        ],
                        default="CARGO",
                        max_length=20,
                        verbose_name="Unidad de cantidad",
                    ),
                ),
                (
                    "puntos_asignados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Puntos asignados",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado_pof",
                    models.CharField(
                        choices=[
                            ("AFECTADO", "Afectado"),
                            ("DESAFECTADO", "Desafectado"),
                        ],
                        default="AFECTADO",
                        max_length=20,
                        verbose_name="Estado POF",
                    ),
                ),
                (
                    "snapshot_ceic",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Snapshot CEIC"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "localizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="reunidas_pof.localizacionpof",
                        verbose_name="LocalizaciÃ³n POF",
                    ),
                ),
                (
                    "lote_carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="reunidas_pof.lotecargapof",
                        verbose_name="Lote de carga POF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo POF",
                "verbose_name_plural": "Cargos POF",
                "db_table": '"reunidas_pof"."cargo_pof"',
            },
        ),
        migrations.CreateModel(
            name="MovimientoCargoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MODIFICACION", "ModificaciÃ³n"),
                            ("AFECTACION", "AfectaciÃ³n"),
                            ("DESAFECTACION", "DesafectaciÃ³n"),
                        ],
                        max_length=40,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Estado anterior"
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Estado nuevo"
                    ),
                ),
                (
                    "valores_anteriores",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Valores anteriores"
                    ),
                ),
                (
                    "valores_nuevos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Valores nuevos"
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="ObservaciÃ³n"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del movimiento",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="reunidas_pof.cargopof",
                        verbose_name="Cargo POF",
                    ),
                ),
                (
                    "lote_carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="reunidas_pof.lotecargapof",
                        verbose_name="Lote de carga POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_cargos_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de cargo POF",
                "verbose_name_plural": "Movimientos de cargos POF",
                "db_table": '"reunidas_pof"."movimiento_cargo_pof"',
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ReunidaPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        help_text="AÃ±o de la Reunida POF.", verbose_name="AÃ±o"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Inicial"),
                            ("PRIMARIA", "Primaria"),
                            ("ESPECIAL", "EducaciÃ³n Especial"),
                            ("FISICA", "EducaciÃ³n FÃ­sica"),
                            ("ADULTOS", "Adultos"),
                            ("TERCIARIO", "Terciario"),
                            ("BIBLIOTECA", "Biblioteca"),
                        ],
                        max_length=30,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTA", "Abierta"), ("CERRADA", "Cerrada")],
                        default="ABIERTA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de apertura",
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Reunida POF",
                "verbose_name_plural": "Reunidas POF",
                "db_table": '"reunidas_pof"."reunida_pof"',
                "ordering": ["-anio", "nivel"],
                "indexes": [
                    models.Index(
                        fields=["anio", "nivel"], name="idx_reunida_pof_anio_nivel"
                    ),
                    models.Index(fields=["estado"], name="idx_reunida_pof_estado"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anio", "nivel"), name="uq_reunida_pof_anio_nivel"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("anio__gt", 0)),
                        name="ck_reunida_pof_anio_gt_0",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="lotecargapof",
            name="reunida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_carga",
                to="reunidas_pof.reunidapof",
                verbose_name="Reunida POF",
            ),
        ),
        migrations.AddField(
            model_name="localizacionpof",
            name="reunida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localizaciones",
                to="reunidas_pof.reunidapof",
                verbose_name="Reunida POF",
            ),
        ),
        migrations.CreateModel(
            name="SnapshotPadronLocalizacionPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_snapshot",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Inicial"),
                            ("VERIFICACION", "VerificaciÃ³n"),
                            ("SINCRONIZACION", "SincronizaciÃ³n"),
                        ],
                        default="INICIAL",
                        max_length=30,
                        verbose_name="Tipo de snapshot",
                    ),
                ),
                (
                    "vigente",
                    models.BooleanField(default=True, verbose_name="Snapshot vigente"),
                ),
                (
                    "estado_padron",
                    models.CharField(
                        choices=[
                            ("SIN_VERIFICAR", "Sin verificar"),
                            ("VIGENTE", "Vigente"),
                            ("MODIFICADO", "Modificado"),
                            ("BAJA", "Baja"),
                            ("NO_ENCONTRADO", "No encontrado"),
                        ],
                        default="SIN_VERIFICAR",
                        max_length=30,
                        verbose_name="Estado del padrÃ³n",
                    ),
                ),
                (
                    "estado_localizacion_padron",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado localizaciÃ³n padrÃ³n",
                    ),
                ),
                (
                    "estado_oferta_padron",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Estado oferta padrÃ³n"
                    ),
                ),
                (
                    "estado_establecimiento_padron",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado establecimiento padrÃ³n",
                    ),
                ),
                ("oferta", models.TextField(blank=True, verbose_name="Oferta")),
                ("acronimo", models.TextField(blank=True, verbose_name="AcrÃ³nimo")),
                (
                    "nombre_establecimiento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre del establecimiento",
                    ),
                ),
                (
                    "numero_establecimiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="NÃºmero del establecimiento",
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="RegiÃ³n"),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Localidad"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Departamento"
                    ),
                ),
                (
                    "ambito",
                    models.CharField(blank=True, max_length=100, verbose_name="Ãmbito"),
                ),
                ("categoria", models.TextField(blank=True, verbose_name="CategorÃ­a")),
                ("jornada", models.TextField(blank=True, verbose_name="Jornada")),
                ("ubicacion", models.TextField(blank=True, verbose_name="UbicaciÃ³n")),
                (
                    "ubicacion_localidad_departamento",
                    models.TextField(
                        blank=True, verbose_name="UbicaciÃ³n localidad/departamento"
                    ),
                ),
                (
                    "datos_padron",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Datos completos del padrÃ³n",
                    ),
                ),
                (
                    "fecha_snapshot",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del snapshot",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "localizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_padron",
                        to="reunidas_pof.localizacionpof",
                        verbose_name="LocalizaciÃ³n POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_padron_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot padrÃ³n localizaciÃ³n POF",
                "verbose_name_plural": "Snapshots padrÃ³n localizaciÃ³n POF",
                "db_table": '"reunidas_pof"."snapshot_padron_localizacion_pof"',
                "ordering": ["-fecha_snapshot"],
            },
        ),
        migrations.AddIndex(
            model_name="cargopof",
            index=models.Index(
                fields=["localizacion", "estado_pof"], name="idx_cargo_pof_loc_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="cargopof",
            index=models.Index(fields=["ceic"], name="idx_cargo_pof_ceic"),
        ),
        migrations.AddIndex(
            model_name="cargopof",
            index=models.Index(fields=["estado_pof"], name="idx_cargo_pof_estado"),
        ),
        migrations.AddIndex(
            model_name="cargopof",
            index=models.Index(fields=["lote_carga"], name="idx_cargo_pof_lote"),
        ),
        migrations.AddIndex(
            model_name="cargopof",
            index=models.Index(
                fields=["localizacion", "ceic"], name="idx_cargo_pof_loc_ceic"
            ),
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(("ceic__gt", 0)), name="ck_cargo_pof_ceic_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="ck_cargo_pof_cantidad_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(("puntos_asignados__gte", 0)),
                name="ck_cargo_pof_puntos_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="ck_cargo_pof_total_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(
                fields=["cargo", "fecha"], name="idx_mov_cargo_pof_cargo_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(
                fields=["lote_carga", "fecha"], name="idx_mov_cargo_pof_lote_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(
                fields=["tipo_movimiento"], name="idx_mov_cargo_pof_tipo"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(
                fields=["usuario", "fecha"], name="idx_mov_cargo_pof_usr"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(fields=["fecha"], name="idx_mov_cargo_pof_fecha"),
        ),
        migrations.AddIndex(
            model_name="lotecargapof",
            index=models.Index(
                fields=["reunida", "localizacion"],
                name="idx_lote_carga_pof_reunida_loc",
            ),
        ),
        migrations.AddIndex(
            model_name="lotecargapof",
            index=models.Index(
                fields=["tipo_operacion"], name="idx_lote_carga_pof_tipo"
            ),
        ),
        migrations.AddIndex(
            model_name="lotecargapof",
            index=models.Index(fields=["fecha"], name="idx_lote_carga_pof_fecha"),
        ),
        migrations.AddIndex(
            model_name="lotecargapof",
            index=models.Index(fields=["usuario"], name="idx_lote_carga_pof_usuario"),
        ),
        migrations.AddIndex(
            model_name="localizacionpof",
            index=models.Index(
                fields=["reunida", "cueanexo"], name="idx_loc_pof_reunida_cue"
            ),
        ),
        migrations.AddIndex(
            model_name="localizacionpof",
            index=models.Index(
                fields=["cueanexo"], name="idx_localizacion_pof_cueanexo"
            ),
        ),
        migrations.AddIndex(
            model_name="localizacionpof",
            index=models.Index(fields=["cuof"], name="idx_localizacion_pof_cuof"),
        ),
        migrations.AddConstraint(
            model_name="localizacionpof",
            constraint=models.UniqueConstraint(
                fields=("reunida", "cueanexo", "cuof"),
                name="uq_localizacion_pof_reunida_cueanexo_cuof",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizacionpof",
            constraint=models.CheckConstraint(
                condition=models.Q(("cueanexo", ""), _negated=True),
                name="ck_localizacion_pof_cueanexo_no_vacio",
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotpadronlocalizacionpof",
            index=models.Index(
                fields=["localizacion", "fecha_snapshot"],
                name="idx_snapshot_padron_loc_fecha",
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotpadronlocalizacionpof",
            index=models.Index(
                fields=["localizacion", "vigente"], name="idx_snap_padron_loc_vig"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotpadronlocalizacionpof",
            index=models.Index(
                fields=["estado_padron"], name="idx_snapshot_padron_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotpadronlocalizacionpof",
            index=models.Index(
                fields=["tipo_snapshot"], name="idx_snapshot_padron_tipo"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotpadronlocalizacionpof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("localizacion",),
                name="uq_snapshot_padron_loc_vigente",
            ),
        ),
    ]