# Generated by Django 5.2.15 on 2026-06-24 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localizacionpof",
            options={
                "verbose_name": "Localización POF",
                "verbose_name_plural": "Localizaciones POF",
            },
        ),
        migrations.AlterModelOptions(
            name="snapshotpadronlocalizacionpof",
            options={
                "ordering": ["-fecha_snapshot"],
                "verbose_name": "Snapshot padrón localización POF",
                "verbose_name_plural": "Snapshots padrón localización POF",
            },
        ),
        migrations.AlterModelOptions(
            name="vcapaunicaofertasant",
            options={
                "managed": False,
                "verbose_name": "Vista capa única oferta",
                "verbose_name_plural": "Vista capa única ofertas",
            },
        ),
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="origen_datos",
            field=models.CharField(
                choices=[
                    ("PADRON", "Ingreso por padrón"),
                    ("MANUAL", "Ingreso manual"),
                ],
                default="PADRON",
                max_length=20,
                verbose_name="Origen de datos",
            ),
        ),
        migrations.AlterField(
            model_name="cargopof",
            name="ceic",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Código CEIC asociado al cargo.",
                verbose_name="CEIC",
            ),
        ),
        migrations.AlterField(
            model_name="cargopof",
            name="localizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos",
                to="reunidas_pof.localizacionpof",
                verbose_name="Localización POF",
            ),
        ),
        migrations.AlterField(
            model_name="cargopof",
            name="unidad_cantidad",
            field=models.CharField(
                choices=[
                    ("CARGO", "Cargo"),
                    ("HORA_CATEDRA", "Hora cátedra"),
                    ("Otro", "Otro"),
                ],
                default="CARGO",
                max_length=20,
                verbose_name="Unidad de cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="localizacionpof",
            name="cueanexo",
            field=models.CharField(
                db_index=True,
                help_text="CUEANEXO completo de 9 dígitos.",
                max_length=20,
                verbose_name="CUEANEXO",
            ),
        ),
        migrations.AlterField(
            model_name="lotecargapof",
            name="fecha",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de operación"
            ),
        ),
        migrations.AlterField(
            model_name="lotecargapof",
            name="localizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_carga",
                to="reunidas_pof.localizacionpof",
                verbose_name="Localización POF",
            ),
        ),
        migrations.AlterField(
            model_name="lotecargapof",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="Observación"),
        ),
        migrations.AlterField(
            model_name="lotecargapof",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("ALTA", "Alta"),
                    ("MODIFICACION", "Modificación"),
                    ("AFECTACION", "Afectación"),
                    ("DESAFECTACION", "Desafectación"),
                ],
                default="ALTA",
                max_length=40,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="movimientocargopof",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="Observación"),
        ),
        migrations.AlterField(
            model_name="movimientocargopof",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ALTA", "Alta"),
                    ("MODIFICACION", "Modificación"),
                    ("AFECTACION", "Afectación"),
                    ("DESAFECTACION", "Desafectación"),
                ],
                max_length=40,
                verbose_name="Tipo de movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="reunidapof",
            name="anio",
            field=models.PositiveSmallIntegerField(
                help_text="Año de la Reunida POF.", verbose_name="Año"
            ),
        ),
        migrations.AlterField(
            model_name="reunidapof",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("PRIMARIA", "Primaria"),
                    ("ESPECIAL", "Educación Especial"),
                    ("FISICA", "Educación Física"),
                    ("ADULTOS", "Adultos"),
                    ("TERCIARIO", "Terciario"),
                    ("BIBLIOTECA", "Biblioteca"),
                ],
                max_length=30,
                verbose_name="Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="acronimo",
            field=models.TextField(blank=True, verbose_name="Acrónimo"),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="ambito",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ámbito"),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="categoria",
            field=models.TextField(blank=True, verbose_name="Categoría"),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="datos_padron",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Datos completos del padrón"
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="estado_establecimiento_padron",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Estado establecimiento padrón"
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="estado_localizacion_padron",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Estado localización padrón"
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="estado_oferta_padron",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Estado oferta padrón"
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="estado_padron",
            field=models.CharField(
                choices=[
                    ("SIN_VERIFICAR", "Sin verificar"),
                    ("VIGENTE", "Vigente"),
                    ("MODIFICADO", "Modificado"),
                    ("BAJA", "Baja"),
                    ("NO_ENCONTRADO", "No encontrado"),
                ],
                default="SIN_VERIFICAR",
                max_length=30,
                verbose_name="Estado del padrón",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="localizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshots_padron",
                to="reunidas_pof.localizacionpof",
                verbose_name="Localización POF",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="numero_establecimiento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número del establecimiento"
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="Región"),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="tipo_snapshot",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("VERIFICACION", "Verificación"),
                    ("SINCRONIZACION", "Sincronización"),
                ],
                default="INICIAL",
                max_length=30,
                verbose_name="Tipo de snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="ubicacion",
            field=models.TextField(blank=True, verbose_name="Ubicación"),
        ),
        migrations.AlterField(
            model_name="snapshotpadronlocalizacionpof",
            name="ubicacion_localidad_departamento",
            field=models.TextField(
                blank=True, verbose_name="Ubicación localidad/departamento"
            ),
        ),
    ]
