# Generated by Django 5.2.15 on 2026-06-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0002_alter_localizacionpof_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProyectosEspecialesPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        help_text="Año de los Proyectos Especiales POF.",
                        verbose_name="Año",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre libre del proyecto, programa, dispositivo o agrupador.",
                        max_length=255,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "resolucion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Resolución"
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="Observación"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Proyectos Especiales POF",
                "verbose_name_plural": "Proyectos Especiales POF",
                "db_table": '"reunidas_pof"."proyectos_especiales_pof"',
                "ordering": ["-anio", "nombre"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="localizacionpof",
            name="uq_localizacion_pof_reunida_cueanexo_cuof",
        ),
        migrations.RemoveConstraint(
            model_name="localizacionpof",
            name="ck_localizacion_pof_cueanexo_no_vacio",
        ),
        migrations.RemoveIndex(
            model_name="reunidapof",
            name="idx_reunida_pof_estado",
        ),
        migrations.RemoveField(
            model_name="reunidapof",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="reunidapof",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="reunidapof",
            name="fecha_apertura",
        ),
        migrations.RemoveField(
            model_name="reunidapof",
            name="fecha_cierre",
        ),
        migrations.AddField(
            model_name="movimientocargopof",
            name="snapshot_padron",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot de padrón/localización vigente al momento del movimiento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_cargos",
                to="reunidas_pof.snapshotpadronlocalizacionpof",
                verbose_name="Snapshot padrón",
            ),
        ),
        migrations.AlterField(
            model_name="cargopof",
            name="unidad_cantidad",
            field=models.CharField(
                choices=[
                    ("CARGO", "Cargo"),
                    ("HORA_CATEDRA", "Hora cátedra"),
                    ("OTRO", "Otro"),
                ],
                default="CARGO",
                max_length=20,
                verbose_name="Unidad de cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="localizacionpof",
            name="cueanexo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="CUEANEXO completo de 9 dígitos. Obligatorio para Reunidas; opcional para Proyectos Especiales POF.",
                max_length=20,
                verbose_name="CUEANEXO",
            ),
        ),
        migrations.AlterField(
            model_name="localizacionpof",
            name="cuof",
            field=models.CharField(max_length=50, verbose_name="CUOF"),
        ),
        migrations.AlterField(
            model_name="localizacionpof",
            name="reunida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localizaciones",
                to="reunidas_pof.reunidapof",
                verbose_name="Reunida POF",
            ),
        ),
        migrations.AlterField(
            model_name="lotecargapof",
            name="reunida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_carga",
                to="reunidas_pof.reunidapof",
                verbose_name="Reunida POF",
            ),
        ),
        migrations.AlterField(
            model_name="reunidapof",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("PRIMARIA", "Primaria"),
                    ("SECUNDARIA", "Secundaria"),
                    ("ESPECIAL", "Educación Especial"),
                    ("FISICA", "Educación Física"),
                    ("ADULTOS", "Adultos"),
                    ("TERCIARIO", "Terciario"),
                    ("BIBLIOTECA", "Biblioteca"),
                ],
                max_length=30,
                verbose_name="Nivel",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocargopof",
            index=models.Index(
                fields=["snapshot_padron", "fecha"], name="idx_mov_cargo_pof_snap_fecha"
            ),
        ),
        migrations.AddField(
            model_name="proyectosespecialespof",
            name="proyecto_base_anterior",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto Especial POF del año anterior usado como base, si corresponde.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_derivados",
                to="reunidas_pof.proyectosespecialespof",
                verbose_name="Proyecto base anterior",
            ),
        ),
        migrations.AddField(
            model_name="localizacionpof",
            name="proyecto_especial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localizaciones",
                to="reunidas_pof.proyectosespecialespof",
                verbose_name="Proyectos Especiales POF",
            ),
        ),
        migrations.AddField(
            model_name="lotecargapof",
            name="proyecto_especial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_carga",
                to="reunidas_pof.proyectosespecialespof",
                verbose_name="Proyectos Especiales POF",
            ),
        ),
        migrations.AddIndex(
            model_name="localizacionpof",
            index=models.Index(
                fields=["proyecto_especial", "cuof"], name="idx_loc_pof_proyecto_cuof"
            ),
        ),
        migrations.AddIndex(
            model_name="lotecargapof",
            index=models.Index(
                fields=["proyecto_especial", "localizacion"],
                name="idx_lote_carga_pof_proy_loc",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizacionpof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("proyecto_especial__isnull", True), ("reunida__isnull", False)
                    ),
                    models.Q(
                        ("proyecto_especial__isnull", False), ("reunida__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="ck_localizacion_pof_una_cabecera",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizacionpof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reunida__isnull", False)),
                fields=("reunida", "cueanexo", "cuof"),
                name="uq_loc_pof_reunida_cueanexo_cuof",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizacionpof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("proyecto_especial__isnull", False)),
                fields=("proyecto_especial", "cuof"),
                name="uq_loc_pof_proyecto_cuof",
            ),
        ),
        migrations.AddConstraint(
            model_name="lotecargapof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("proyecto_especial__isnull", True), ("reunida__isnull", False)
                    ),
                    models.Q(
                        ("proyecto_especial__isnull", False), ("reunida__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="ck_lote_carga_pof_una_cabecera",
            ),
        ),
        migrations.AddIndex(
            model_name="proyectosespecialespof",
            index=models.Index(
                fields=["anio", "nombre"], name="idx_proy_esp_pof_anio_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="proyectosespecialespof",
            index=models.Index(
                fields=["proyecto_base_anterior"], name="idx_proy_esp_pof_base_ant"
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectosespecialespof",
            constraint=models.CheckConstraint(
                condition=models.Q(("anio__gt", 0)),
                name="ck_proyectos_especiales_pof_anio_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectosespecialespof",
            constraint=models.UniqueConstraint(
                fields=("anio", "nombre", "resolucion"),
                name="uq_proyectos_especiales_pof_anio_nombre_res",
            ),
        ),
    ]
