# Generated by Django 5.2.15 on 2026-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0003_proyectosespecialespof_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PofRolUsuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Rol de usuario POF",
                "verbose_name_plural": "Roles de usuario POF",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PofUsuarioPerfil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Perfil de usuario POF",
                "verbose_name_plural": "Perfiles de usuario POF",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="proyectosespecialespof",
            name="ck_proyectos_especiales_pof_anio_gt_0",
        ),
        migrations.RemoveConstraint(
            model_name="reunidapof",
            name="ck_reunida_pof_anio_gt_0",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "reunidas_pof"."lote_carga_pof" '
                        'DROP COLUMN IF EXISTS "observacion";'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "reunidas_pof"."lote_carga_pof" '
                        'ADD COLUMN IF NOT EXISTS "observacion" text NOT NULL DEFAULT \'\';'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="lotecargapof",
                    name="observacion",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "reunidas_pof"."cargo_pof" '
                        'ADD COLUMN IF NOT EXISTS "observacion" text NOT NULL DEFAULT \'\';'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "reunidas_pof"."cargo_pof" '
                        'DROP COLUMN IF EXISTS "observacion";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="cargopof",
                    name="observacion",
                    field=models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Observación",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cargopof",
            name="unidad_cantidad",
            field=models.CharField(
                choices=[("CARGO", "Cargo"), ("HORA_CATEDRA", "Hora cátedra")],
                default="CARGO",
                max_length=20,
                verbose_name="Unidad de cantidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectosespecialespof",
            constraint=models.CheckConstraint(
                condition=models.Q(("anio__gte", 1000), ("anio__lte", 9999)),
                name="ck_proy_esp_pof_anio_4_dig",
            ),
        ),
        migrations.AddConstraint(
            model_name="reunidapof",
            constraint=models.CheckConstraint(
                condition=models.Q(("anio__gte", 1000), ("anio__lte", 9999)),
                name="ck_reunida_pof_anio_4_dig",
            ),
        ),
    ]
