# Generated by Django 5.2.15 on 2026-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0004_pofrolusuario_pofusuarioperfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reunidapof",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIAL", "Inicial"),
                    ("PRIMARIA", "Primaria"),
                    ("SECUNDARIA", "Secundaria"),
                    ("SECUNDARIA_TECNICA", "Secundaria Técnica"),
                    ("ESPECIAL", "Educación Especial"),
                    ("FISICA", "Educación Física"),
                    ("ADULTOS", "Adultos"),
                    ("TERCIARIO", "Terciario"),
                    ("BIBLIOTECA", "Biblioteca"),
                ],
                max_length=30,
                verbose_name="Nivel",
            ),
        ),
    ]
