# Generated by Django 5.2.15 on 2026-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0006_cargo_pof_eliminacion_funcional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizacionpof",
            name="cui",
            field=models.CharField(blank=True, max_length=100, verbose_name="CUI"),
        ),
        migrations.AlterField(
            model_name="localizacionpof",
            name="cuof",
            field=models.CharField(max_length=100, verbose_name="CUOF"),
        ),
    ]
