# Generated by Django 5.2.15 on 2026-07-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0007_alter_localizacionpof_cui_alter_localizacionpof_cuof"),
    ]

    operations = [
        migrations.AddField(
            model_name="reunidapof",
            name="reunida_base_anterior",
            field=models.ForeignKey(
                blank=True,
                help_text="Reunida POF del mismo nivel y del año inmediatamente anterior usada como base, si corresponde.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reunidas_derivadas",
                to="reunidas_pof.reunidapof",
                verbose_name="Reunida base anterior",
            ),
        ),
    ]
