# Generated by Django 5.2.16 on 2026-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0008_reunidapof_reunida_base_anterior"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargopof",
            name="oferta",
            field=models.TextField(blank=True, default="", verbose_name="Ofertas"),
        ),
        migrations.AddField(
            model_name="cargopof",
            name="ofertas_seleccionadas",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ofertas seleccionadas"
            ),
        ),
    ]
