# Generated by Django 5.2.16 on 2026-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0009_cargopof_oferta_cargopof_ofertas_seleccionadas"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cargopof",
            name="ck_cargo_pof_cantidad_gt_0",
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gte", 0)),
                name="ck_cargo_pof_cantidad_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargopof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado_pof", "DESAFECTADO"), ("cantidad__gt", 0), _connector="OR"
                ),
                name="ck_cargo_pof_afectado_cant_gt0",
            ),
        ),
    ]
