# Generated by Django 5.2.16 on 2026-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0010_remove_cargopof_ck_cargo_pof_cantidad_gt_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotecargapof",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("AFECTADO", "Afectado"),
                    ("MODIFICACION", "Modificación"),
                    ("AFECTACION", "Afectación"),
                    ("DESAFECTACION", "Desafectación"),
                ],
                default="AFECTADO",
                max_length=40,
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.AlterField(
            model_name="movimientocargopof",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("AFECTADO", "Afectado"),
                    ("MODIFICACION", "Modificación"),
                    ("AFECTACION", "Afectación"),
                    ("DESAFECTACION", "Desafectación"),
                ],
                max_length=40,
                verbose_name="Tipo de movimiento",
            ),
        ),
    ]
