# Generated by Django 5.2.16 on 2026-09-18 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0012_alter_lotecargapof_tipo_operacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="puntos_zona_educativa",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puntos Zona Educativa"
            ),
        ),
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="zona_educativa",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Zona Educativa"
            ),
        ),
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="zona_educativa_tipo",
            field=models.CharField(
                blank=True,
                choices=[("URBANA", "Urbana"), ("RURAL", "Rural")],
                default="",
                max_length=10,
                verbose_name="Tipo de Zona Educativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotpadronlocalizacionpof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("puntos_zona_educativa__isnull", True),
                        ("zona_educativa", ""),
                        ("zona_educativa_tipo", ""),
                    ),
                    models.Q(
                        ("zona_educativa_tipo__in", ["URBANA", "RURAL"]),
                        models.Q(("zona_educativa", ""), _negated=True),
                        ("puntos_zona_educativa__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="ck_snapshot_pof_zona_integridad",
            ),
        ),
    ]
