# Generated by Django 5.2.17 on 2026-09-23 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reunidas_pof",
            "0013_snapshotpadronlocalizacionpof_puntos_zona_educativa_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cueanexo",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="CUEANEXO"
                    ),
                ),
                (
                    "cuof",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="CUOF"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código Anexo POF",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "proyecto_especial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_anexo_pof",
                        to="reunidas_pof.proyectosespecialespof",
                        verbose_name="Proyecto Especial POF",
                    ),
                ),
                (
                    "reunida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_anexo_pof",
                        to="reunidas_pof.reunidapof",
                        verbose_name="Reunida POF",
                    ),
                ),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_anexo_pof_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de última actualización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Anexo POF",
                "verbose_name_plural": "Asignaciones de Anexo POF",
                "db_table": '"reunidas_pof"."asignacion_anexo_pof"',
            },
        ),
        migrations.CreateModel(
            name="HistorialAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_anterior",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código anterior",
                    ),
                ),
                (
                    "codigo_nuevo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código nuevo",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("CARGA", "Carga"),
                            ("GESTION", "Gestión"),
                            ("HERENCIA", "Herencia"),
                        ],
                        max_length=20,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="reunidas_pof.asignacionanexopof",
                        verbose_name="Asignación Anexo POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_anexos_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Anexo POF",
                "verbose_name_plural": "Historial de Anexos POF",
                "db_table": '"reunidas_pof"."historial_anexo_pof"',
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="asignacionanexopof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cuof", ""),
                        ("proyecto_especial__isnull", True),
                        ("reunida__isnull", False),
                        models.Q(("cueanexo", ""), _negated=True),
                    ),
                    models.Q(
                        ("cueanexo", ""),
                        ("proyecto_especial__isnull", False),
                        ("reunida__isnull", True),
                        models.Q(("cuof", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_anexo_pof_identidad_cabecera",
            ),
        ),
        migrations.AddConstraint(
            model_name="asignacionanexopof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reunida__isnull", False)),
                fields=("reunida", "cueanexo"),
                name="uq_anexo_pof_reunida_cue",
            ),
        ),
        migrations.AddConstraint(
            model_name="asignacionanexopof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("proyecto_especial__isnull", False)),
                fields=("proyecto_especial", "cuof"),
                name="uq_anexo_pof_proyecto_cuof",
            ),
        ),
        migrations.AddIndex(
            model_name="historialanexopof",
            index=models.Index(
                fields=["asignacion", "fecha"], name="idx_hist_anexo_pof_asig_fecha"
            ),
        ),
        migrations.AddConstraint(
            model_name="historialanexopof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("codigo_anterior", models.F("codigo_nuevo")), _negated=True
                ),
                name="ck_hist_anexo_pof_cambio_real",
            ),
        ),
    ]
