# Generated by Django 5.2.17 on 2026-09-23 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0014_asignacionanexopof_historialanexopof_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código Anexo POF"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogos_anexo_pof_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogos_anexo_pof_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de última actualización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código Anexo POF",
                "verbose_name_plural": "Catálogo de Anexo POF",
                "db_table": '"reunidas_pof"."catalogo_anexo_pof"',
                "ordering": ["codigo", "id"],
            },
        ),
        migrations.CreateModel(
            name="AsociacionAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cue",
                    models.CharField(
                        blank=True, default="", max_length=7, verbose_name="CUE"
                    ),
                ),
                (
                    "cuof",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="CUOF"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asociaciones_anexo_pof_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de última actualización",
                    ),
                ),
                (
                    "codigo_catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asociaciones",
                        to="reunidas_pof.catalogoanexopof",
                        verbose_name="Código Anexo POF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asociación Anexo POF",
                "verbose_name_plural": "Asociaciones Anexo POF",
                "db_table": '"reunidas_pof"."asociacion_anexo_pof"',
            },
        ),
        migrations.CreateModel(
            name="HistorialAsociacionAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ASOCIAR", "Asociar"),
                            ("DESACTIVAR", "Desactivar"),
                            ("REACTIVAR", "Reactivar"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("ADMINISTRACION", "Administración"),
                            ("MIGRACION_LEGACY", "Migración legacy"),
                        ],
                        max_length=30,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "asociacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="reunidas_pof.asociacionanexopof",
                        verbose_name="Asociación Anexo POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_asociaciones_anexo_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de asociación Anexo POF",
                "verbose_name_plural": "Historial de asociaciones Anexo POF",
                "db_table": '"reunidas_pof"."historial_asociacion_anexo_pof"',
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCatalogoAnexoPof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREAR", "Crear"),
                            ("DESACTIVAR", "Desactivar"),
                            ("REACTIVAR", "Reactivar"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("ADMINISTRACION", "Administración"),
                            ("MIGRACION_LEGACY", "Migración legacy"),
                        ],
                        max_length=30,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="reunidas_pof.catalogoanexopof",
                        verbose_name="Código Anexo POF",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_catalogo_anexo_pof",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de catálogo Anexo POF",
                "verbose_name_plural": "Historial de catálogo Anexo POF",
                "db_table": '"reunidas_pof"."historial_catalogo_anexo_pof"',
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="asociacionanexopof",
            index=models.Index(
                fields=["cue", "activo"], name="idx_asoc_anexo_cue_activo"
            ),
        ),
        migrations.AddIndex(
            model_name="asociacionanexopof",
            index=models.Index(
                fields=["cuof", "activo"], name="idx_asoc_anexo_cuof_activo"
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionanexopof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(models.Q(("cue", ""), _negated=True), ("cuof", "")),
                    models.Q(("cue", ""), models.Q(("cuof", ""), _negated=True)),
                    _connector="OR",
                ),
                name="ck_asoc_anexo_pof_propietario",
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionanexopof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cue", ""), _negated=True),
                fields=("cue", "codigo_catalogo"),
                name="uq_asoc_anexo_pof_cue_codigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionanexopof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cuof", ""), _negated=True),
                fields=("cuof", "codigo_catalogo"),
                name="uq_asoc_anexo_pof_cuof_codigo",
            ),
        ),
        migrations.AddIndex(
            model_name="historialasociacionanexopof",
            index=models.Index(
                fields=["asociacion", "fecha"], name="idx_hist_asoc_anexo_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="historialcatalogoanexopof",
            index=models.Index(
                fields=["catalogo", "fecha"], name="idx_hist_cat_anexo_fecha"
            ),
        ),
    ]
