# Generated by Django 5.2.17 on 2026-09-30 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reunidas_pof", "0015_catalogoanexopof_asociacionanexopof_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asociacionanexopof",
            name="ck_asoc_anexo_pof_propietario",
        ),
        migrations.RemoveConstraint(
            model_name="asociacionanexopof",
            name="uq_asoc_anexo_pof_cue_codigo",
        ),
        migrations.RemoveIndex(
            model_name="asociacionanexopof",
            name="idx_asoc_anexo_cue_activo",
        ),
        migrations.RemoveField(
            model_name="asociacionanexopof",
            name="cue",
        ),
        migrations.AddField(
            model_name="asociacionanexopof",
            name="cueanexo",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="CUEANEXO"
            ),
        ),
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="observacion_zona_educativa",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Observación del cambio de Zona Educativa",
            ),
        ),
        migrations.AddField(
            model_name="snapshotpadronlocalizacionpof",
            name="zona_educativa_evento",
            field=models.BooleanField(
                default=False, verbose_name="Evento explícito de Zona Educativa"
            ),
        ),
        migrations.AddIndex(
            model_name="asociacionanexopof",
            index=models.Index(
                fields=["cueanexo", "activo"], name="idx_asoc_anexo_cueanexo_activo"
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionanexopof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(models.Q(("cueanexo", ""), _negated=True), ("cuof", "")),
                    models.Q(("cueanexo", ""), models.Q(("cuof", ""), _negated=True)),
                    _connector="OR",
                ),
                name="ck_asoc_anexo_pof_propietario",
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionanexopof",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cueanexo", ""), _negated=True),
                fields=("cueanexo", "codigo_catalogo"),
                name="uq_asoc_anexo_pof_cueanexo_codigo",
            ),
        ),
    ]
