# Generated by Django 5.2.17 on 2026-10-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reunidas_pof",
            "0016_remove_asociacionanexopof_ck_asoc_anexo_pof_propietario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cargopof",
            name="cargo_origen",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Cargo de la cabecera base que dio origen a esta copia.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos_derivados",
                to="reunidas_pof.cargopof",
                verbose_name="Cargo de origen",
            ),
        ),
    ]
