# Generated by Django 4.2.5 on 2024-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchNoramtiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=100)),
                ("tipo_norma", models.CharField(max_length=100)),
                ("nro", models.CharField(max_length=50)),
                ("año", models.IntegerField()),
                ("archivo", models.FileField(upload_to="normativa/")),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
