# Generated by Django 5.1.1 on 2024-12-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("dni", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materia",
                    models.CharField(
                        choices=[("Lengua", "Lengua"), ("Matematicas", "Matematicas")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluacionAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_lengua", models.IntegerField(default=0)),
                ("puntaje_matematica", models.IntegerField(default=0)),
                ("puntaje_total", models.IntegerField(default=0)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="evaluaciones.alumno",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.evaluacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("puntaje", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Unica", "Opción Única"),
                            ("Multiple", "Opción Múltiple"),
                        ],
                        max_length=10,
                    ),
                ),
                ("respuesta_correcta", models.CharField(max_length=255)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="evaluaciones.evaluacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opcion_texto", models.CharField(max_length=255)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="evaluaciones.pregunta",
                    ),
                ),
            ],
        ),
    ]
