# Generated by Django 5.1.1 on 2024-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones", "0002_alter_pregunta_puntaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcionrespuesta",
            name="correcta",
            field=models.BooleanField(default=False),
        ),
    ]
