# Generated by Django 5.1.1 on 2024-12-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones", "0003_opcionrespuesta_correcta"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregunta",
            name="texto_base",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("unica", "Opción Única"),
                    ("multiple", "Opción Múltiple"),
                    ("texto_clasificar", "Texto Clasificar"),
                ],
                max_length=20,
            ),
        ),
    ]
