# Generated by Django 5.1.1 on 2025-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones", "0004_pregunta_texto_base_alter_pregunta_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="ap_tutor",
            field=models.CharField(default=220093000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumno",
            name="cueanexo",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumno",
            name="dni_tutor",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
