# Generated by Django 5.2.14 on 2026-05-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bnhpersonas", "0005_tipoos_c_os_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("apellidos", models.CharField(max_length=150)),
                ("nombres", models.CharField(max_length=150)),
                (
                    "nro_doc",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "cuil",
                    models.CharField(
                        blank=True, db_index=True, max_length=11, null=True
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                ("lugar_nacimiento", models.CharField(max_length=100)),
                ("lugar_residencia", models.CharField(max_length=150)),
                ("est_civil", models.CharField(max_length=20)),
                ("tel", models.CharField(max_length=20)),
                ("celular", models.CharField(max_length=20)),
                ("email", models.CharField(blank=True, max_length=150)),
                ("talla", models.DecimalField(decimal_places=2, max_digits=5)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        db_index=True,
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "discapacidad",
                    models.ForeignKey(
                        db_column="cd_discapacidad",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="bnhpersonas.tipodiscapacidad",
                    ),
                ),
                (
                    "loc_residencia",
                    models.ForeignKey(
                        db_column="loc_residencia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_localidad_residencia",
                        to="bnhpersonas.localidades",
                    ),
                ),
                (
                    "nivel_formacion",
                    models.ForeignKey(
                        db_column="c_nivel_formacion",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="bnhpersonas.nivelformacion",
                    ),
                ),
                (
                    "pais_nacimiento",
                    models.ForeignKey(
                        db_column="pais_nacimiento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_pais_nacimiento",
                        to="bnhpersonas.pais",
                    ),
                ),
                (
                    "pais_residencia",
                    models.ForeignKey(
                        db_column="pais_residencia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_pais_residencia",
                        to="bnhpersonas.pais",
                    ),
                ),
                (
                    "prov_nacimiento",
                    models.ForeignKey(
                        db_column="prov_nacimiento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_provincia_nacimiento",
                        to="bnhpersonas.provincias",
                    ),
                ),
                (
                    "prov_residencia",
                    models.ForeignKey(
                        db_column="prov_residencia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_provincia_residencia",
                        to="bnhpersonas.provincias",
                    ),
                ),
                (
                    "pueblo_indigena",
                    models.ForeignKey(
                        db_column="cd_pueblo_indigena",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="bnhpersonas.tipocomunidadoriginaria",
                    ),
                ),
                (
                    "sexo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.sexo",
                    ),
                ),
                (
                    "tipo_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.documentotipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "db_table": '"bnh_alumno"."alumnos"',
            },
        ),
        migrations.CreateModel(
            name="Discapacidad",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("observaciones", models.TextField(blank=True)),
                ("certificado_cud", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_alumno",
                    models.ForeignKey(
                        db_column="id_alumno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discapacidades",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "id_discapacidad",
                    models.ForeignKey(
                        db_column="id_discapacidad",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_discapacidad",
                        to="bnhpersonas.tipodiscapacidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discapacidad",
                "verbose_name_plural": "Discapacidades",
                "db_table": '"bnh_alumno"."discapacidad"',
            },
        ),
        migrations.CreateModel(
            name="ObraSocial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_obra", models.CharField(max_length=150)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True)),
                ("estado", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_alumno",
                    models.ForeignKey(
                        db_column="id_alumno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obras_sociales",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "tipo_obra",
                    models.ForeignKey(
                        db_column="tipo_obra",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obras_sociales",
                        to="bnhpersonas.tipoos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obra social",
                "verbose_name_plural": "Obras sociales",
                "db_table": '"bnh_alumno"."obra_social"',
            },
        ),
        migrations.CreateModel(
            name="PlanesSociales",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=150)),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("estado", models.CharField(max_length=20)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_alumno",
                    models.ForeignKey(
                        db_column="id_alumno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_sociales",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "id_beneficio",
                    models.ForeignKey(
                        db_column="id_beneficio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_sociales",
                        to="bnhpersonas.tipoplanessociales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan social",
                "verbose_name_plural": "Planes sociales",
                "db_table": '"bnh_alumno"."planes_sociales"',
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cuil_tutor",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("apellidos", models.CharField(max_length=150)),
                ("nombres", models.CharField(max_length=150)),
                (
                    "nro_doc",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("fecha_nac", models.DateField()),
                ("ocupacion", models.CharField(max_length=100)),
                ("fecha_actualiza", models.DateField(auto_now=True)),
                ("cod_postal", models.CharField(max_length=20)),
                ("calle", models.CharField(max_length=150)),
                ("nro", models.CharField(max_length=20)),
                ("piso", models.CharField(blank=True, max_length=10)),
                ("dpto", models.CharField(blank=True, max_length=10)),
                ("mail", models.EmailField(max_length=150)),
                ("tel", models.CharField(max_length=20)),
                ("celular", models.CharField(max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        db_index=True,
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                (
                    "loc_resid",
                    models.ForeignKey(
                        db_column="loc_resid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutores_localidad_residencia",
                        to="bnhpersonas.localidades",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.nacionalidad",
                    ),
                ),
                (
                    "pais_nac",
                    models.ForeignKey(
                        db_column="pais_nac",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutores_pais_nacimiento",
                        to="bnhpersonas.pais",
                    ),
                ),
                (
                    "prov_resid",
                    models.ForeignKey(
                        db_column="prov_resid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutores_provincia_residencia",
                        to="bnhpersonas.provincias",
                    ),
                ),
                (
                    "tipo_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.documentotipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
                "db_table": '"bnh_alumno"."tutores"',
            },
        ),
        migrations.CreateModel(
            name="Parental",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "id_alumno",
                    models.ForeignKey(
                        db_column="id_alumno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parentales",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "parentesco",
                    models.ForeignKey(
                        db_column="id_parentesco",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parentales",
                        to="bnhpersonas.relacionparentesco",
                    ),
                ),
                (
                    "id_tutor",
                    models.ForeignKey(
                        db_column="id_tutor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parentales",
                        to="bnhalumnos.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parental",
                "verbose_name_plural": "Parentales",
                "db_table": '"bnh_alumno"."parental"',
            },
        ),
        migrations.AddIndex(
            model_name="alumno",
            index=models.Index(fields=["nro_doc"], name="idx_alumnos_nro_doc"),
        ),
        migrations.AddIndex(
            model_name="alumno",
            index=models.Index(fields=["email"], name="idx_alumnos_email"),
        ),
        migrations.AddIndex(
            model_name="discapacidad",
            index=models.Index(fields=["id_alumno"], name="idx_discapacidad_alumno"),
        ),
        migrations.AddIndex(
            model_name="discapacidad",
            index=models.Index(
                fields=["id_discapacidad", "id_alumno"],
                name="idx_discapacidad_alumno_tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="obrasocial",
            index=models.Index(fields=["id_alumno"], name="idx_obra_social_alumno"),
        ),
        migrations.AddIndex(
            model_name="planessociales",
            index=models.Index(fields=["id_alumno"], name="idx_planes_alumno"),
        ),
        migrations.AddIndex(
            model_name="tutor",
            index=models.Index(fields=["cuil_tutor"], name="idx_tutores_cuil"),
        ),
        migrations.AddIndex(
            model_name="tutor",
            index=models.Index(fields=["nro_doc"], name="idx_tutores_nro_doc"),
        ),
        migrations.AddIndex(
            model_name="parental",
            index=models.Index(fields=["id_alumno"], name="idx_parental_alumno"),
        ),
        migrations.AddIndex(
            model_name="parental",
            index=models.Index(fields=["id_tutor"], name="idx_parental_tutor"),
        ),
        migrations.AddConstraint(
            model_name="parental",
            constraint=models.UniqueConstraint(
                fields=("id_alumno", "id_tutor"), name="uq_parental_alumno_tutor"
            ),
        ),
    ]
