# Generated by Django 5.2.14 on 2026-05-29 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="lugar_residencia",
        ),
    ]
