# Generated by Django 5.2.14 on 2026-05-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0002_remove_alumno_lugar_residencia"),
        ("bnhpersonas", "0005_tipoos_c_os_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="lengua_originaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.tipolenguaoriginaria",
            ),
        ),
    ]
