# Generated by Django 5.2.14 on 2026-05-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0003_alumno_lengua_originaria"),
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="est_civil",
            field=models.ForeignKey(
                db_column="est_civil",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos",
                to="bnhpersonas.estadosciviles",
            ),
        ),
    ]
