# Generated by Django 5.2.14 on 2026-05-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0004_alter_alumno_est_civil"),
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="lugar_nacimiento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="prov_nacimiento",
            field=models.ForeignKey(
                blank=True,
                db_column="prov_nacimiento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_provincia_nacimiento",
                to="bnhpersonas.provincias",
            ),
        ),
    ]
