# Generated by Django 5.2.14 on 2026-06-01 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0006_replace_lugar_nacimiento_with_loc_nacimiento"),
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="celular",
        ),
        migrations.RemoveField(
            model_name="alumno",
            name="tel",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="celular",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="tel",
        ),
        migrations.AddField(
            model_name="alumno",
            name="codigo_area",
            field=models.ForeignKey(
                blank=True,
                db_column="codigo_area",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_codigo_area",
                to="bnhpersonas.codareastelefonos",
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="es_celular",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6,8}$",
                        message="Ingrese solo el número local (6 a 8 dígitos, sin código de área)",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="telefono_normalizado",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutor",
            name="codigo_area",
            field=models.ForeignKey(
                blank=True,
                db_column="codigo_area",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutores_codigo_area",
                to="bnhpersonas.codareastelefonos",
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="es_celular",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6,8}$",
                        message="Ingrese solo el número local (6 a 8 dígitos, sin código de área)",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="telefono_normalizado",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="mail",
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
