# Generated by Django 5.2.14 on 2026-06-02 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0007_remove_alumno_celular_remove_alumno_tel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="parental",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="parental",
            name="fecha_desde",
        ),
        migrations.RemoveField(
            model_name="parental",
            name="fecha_hasta",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="estado",
        ),
    ]
