# Generated by Django 5.2.14 on 2026-06-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0008_remove_alumno_estado_remove_parental_activo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoObraSocial",
            fields=[
                ("c_os", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_os", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Catálogo obra social",
                "verbose_name_plural": "Catálogo obras sociales",
                "db_table": '"bnh_alumno"."catalogo_obra_social"',
                "ordering": ["descrip_os"],
            },
        ),
        migrations.AlterField(
            model_name="obrasocial",
            name="nombre_obra",
            field=models.ForeignKey(
                db_column="nombre_obra",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obras_sociales",
                to="bnhalumnos.catalogoobrasocial",
            ),
        ),
    ]
