# Generated by Django 5.2.14 on 2026-06-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0009_remove_obrasocial_nombre_obra"),
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoSinoTipo",
            fields=[
                ("codigo", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Catálogo Sí/No/Sin información",
                "verbose_name_plural": "Catálogo Sí/No/Sin información",
                "db_table": '"bnh_alumno"."catalogo_sino_tipo"',
                "ordering": ["codigo"],
            },
        ),
        migrations.RemoveField(
            model_name="alumno",
            name="discapacidad",
        ),
        migrations.RemoveField(
            model_name="alumno",
            name="pueblo_indigena",
        ),
        migrations.AddField(
            model_name="alumno",
            name="comunidad_originaria",
            field=models.ForeignKey(
                blank=True,
                db_column="id_comunidad_originaria",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_comunidad_originaria",
                to="bnhpersonas.tipocomunidadoriginaria",
            ),
        ),
        migrations.AlterField(
            model_name="discapacidad",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discapacidad",
            name="porcentaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="ocupacion",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="alumno",
            name="pertenece_pueblo_indigena",
            field=models.ForeignKey(
                db_column="cd_pueblo_indigena",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_pueblo_indigena",
                to="bnhalumnos.catalogosinotipo",
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="tiene_discapacidad",
            field=models.ForeignKey(
                db_column="cd_discapacidad",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_discapacidad_sino",
                to="bnhalumnos.catalogosinotipo",
            ),
        ),
    ]
