# Generated by Django 5.2.14 on 2026-06-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0010_catalogosinotipo_remove_alumno_discapacidad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BnhRolUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Rol de usuario",
                "verbose_name_plural": "Roles de usuario",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BnhUsuarioPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario para BNH Alumnos",
                "verbose_name_plural": "Perfiles de usuario para BNH Alumnos",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="alumno",
            name="cuil_usuario_modificacion",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=11
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="id_persona_jurisdiccional",
            field=models.CharField(
                blank=True, db_index=True, max_length=80, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="lugar_nacimiento",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="alumno",
            name="tiene_ppi",
            field=models.ForeignKey(
                db_column="c_ppi",
                default=-2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_ppi",
                to="bnhalumnos.catalogosinotipo",
                verbose_name="Proyecto Pedagógico Individual",
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="usuario_modificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="pertenece_pueblo_indigena",
            field=models.ForeignKey(
                db_column="cd_pueblo_indigena",
                default=-2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_pueblo_indigena",
                to="bnhalumnos.catalogosinotipo",
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="tiene_discapacidad",
            field=models.ForeignKey(
                db_column="cd_discapacidad",
                default=-2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_discapacidad_sino",
                to="bnhalumnos.catalogosinotipo",
            ),
        ),
    ]
