# Generated by Django 5.2.14 on 2026-06-10 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0011_bnhrolusuario_bnhusuarioperfil_and_more"),
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="nivel_formacion",
        ),
        migrations.AddField(
            model_name="tutor",
            name="nivel_formacion",
            field=models.ForeignKey(
                blank=True,
                db_column="c_nivel_formacion",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutores",
                to="bnhpersonas.nivelformacion",
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="es_celular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="codigo_area",
            field=models.ForeignKey(
                db_column="codigo_area",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutores_codigo_area",
                to="bnhpersonas.codareastelefonos",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="es_celular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefono",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6,8}$",
                        message="Ingrese solo el número local (6 a 8 dígitos, sin código de área)",
                    )
                ],
            ),
        ),
    ]
