# Generated by Django 5.2.16 on 2026-09-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        ("bnhpersonas", "0019_integridad"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoObraSocial",
            fields=[
                ("c_os", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_os", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo de obra social",
                "verbose_name_plural": "Tipos de obra social",
                "db_table": '"bnh_alumno"."tipo_obra_social"',
                "ordering": ["c_os"],
            },
        ),
        migrations.AddField(
            model_name="alumno",
            name="nacionalidad",
            field=models.ForeignKey(
                db_column="c_nacionalidad",
                default=-2,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.nacionalidad",
            ),
        ),
        migrations.AlterField(
            model_name="obrasocial",
            name="tipo_obra",
            field=models.ForeignKey(
                db_column="tipo_obra",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obras_sociales",
                to="bnhalumnos.tipoobrasocial",
            ),
        ),
    ]
