# Generated by Django 5.2.17 on 2026-09-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhalumnos", "0013_tipoobrasocial_alumno_nacionalidad_and_more"),
        ("bnhpersonas", "0032_alinea_estado_tipoos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="id_persona_sge",
            field=models.PositiveBigIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="id_persona_jurisdiccional",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="loc_residencia",
            field=models.ForeignKey(
                blank=True,
                db_column="loc_residencia",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_localidad_residencia",
                to="bnhpersonas.localidades",
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="nro_doc",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="prov_residencia",
            field=models.ForeignKey(
                blank=True,
                db_column="prov_residencia",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos_provincia_residencia",
                to="bnhpersonas.provincias",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="cuil_tutor",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nro_doc",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="alumno",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cuil__isnull", False), models.Q(("cuil", ""), _negated=True)
                ),
                fields=("cuil",),
                name="uq_bnh_alumno_cuil_informado",
            ),
        ),
        migrations.AddConstraint(
            model_name="alumno",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nro_doc__isnull", False), models.Q(("nro_doc", ""), _negated=True)
                ),
                fields=("tipo_doc", "nro_doc"),
                name="uq_bnh_alumno_tipo_documento",
            ),
        ),
        migrations.AddConstraint(
            model_name="tutor",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cuil_tutor__isnull", False),
                    models.Q(("cuil_tutor", ""), _negated=True),
                ),
                fields=("cuil_tutor",),
                name="uq_bnh_tutor_cuil_informado",
            ),
        ),
        migrations.AddConstraint(
            model_name="tutor",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nro_doc__isnull", False), models.Q(("nro_doc", ""), _negated=True)
                ),
                fields=("tipo_doc", "nro_doc"),
                name="uq_bnh_tutor_tipo_documento",
            ),
        ),
    ]
