# Generated by Django 4.2.5 on 2024-05-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsuntoRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niveles", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="TNormativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_norma", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="ArchRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=10)),
                ("nro_normativa", models.CharField(max_length=100)),
                ("año", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("archivo", models.FileField(upload_to="archivo_normativa/")),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "asunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archivar.asuntoregister",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archivar.nivel"
                    ),
                ),
                (
                    "t_norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archivar.tnormativa",
                    ),
                ),
            ],
        ),
    ]
