# Generated by Django 5.1.1 on 2025-02-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archivar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archregister",
            name="año",
        ),
        migrations.AddField(
            model_name="archregister",
            name="anio",
            field=models.IntegerField(default=2024, verbose_name="año"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="archregister",
            name="asunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archivar.asuntoregister",
                verbose_name="asunto",
            ),
        ),
        migrations.AlterField(
            model_name="archregister",
            name="cueanexo",
            field=models.CharField(max_length=10, verbose_name="cueanexo"),
        ),
        migrations.AlterField(
            model_name="archregister",
            name="descripcion",
            field=models.TextField(verbose_name="descripcion"),
        ),
        migrations.AlterField(
            model_name="archregister",
            name="nivel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archivar.nivel",
                verbose_name="nivel",
            ),
        ),
        migrations.AlterField(
            model_name="archregister",
            name="nro_normativa",
            field=models.CharField(max_length=100, verbose_name="nro_normativa"),
        ),
        migrations.AlterField(
            model_name="archregister",
            name="t_norma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archivar.tnormativa",
                verbose_name="t_norma",
            ),
        ),
    ]
