# Generated by Django 5.1.1 on 2025-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archivar", "0002_remove_archregister_año_archregister_anio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asuntoregister",
            name="asunto",
            field=models.CharField(max_length=150, verbose_name="asunto"),
        ),
        migrations.AlterField(
            model_name="nivel",
            name="niveles",
            field=models.CharField(max_length=150, verbose_name="niveles"),
        ),
        migrations.AlterField(
            model_name="tnormativa",
            name="t_norma",
            field=models.CharField(max_length=150, verbose_name="t_norma"),
        ),
    ]
