# Generated by Django 5.1.1 on 2025-05-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archivar", "0004_vcapaunicaofertascuicuof"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsuntoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=150, verbose_name="asunto")),
            ],
            options={
                "verbose_name": "Asunto_Evaluacion",
                "verbose_name_plural": "Asuntos_Evaluacion",
                "db_table": "asunto_evaluacion",
            },
        ),
        migrations.CreateModel(
            name="TEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_evaluacion",
                    models.CharField(max_length=150, verbose_name="t_norma"),
                ),
            ],
            options={
                "verbose_name": "Tipo_Evaluacion",
                "verbose_name_plural": "Tipos_Evaluacion",
                "db_table": "t_evaluacion",
            },
        ),
        migrations.CreateModel(
            name="ArchModelosEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("01", "Enero"),
                            ("02", "Febrero"),
                            ("03", "Marzo"),
                            ("04", "Abril"),
                            ("05", "Mayo"),
                            ("06", "Junio"),
                            ("07", "Julio"),
                            ("08", "Agosto"),
                            ("09", "Septiembre"),
                            ("10", "Octubre"),
                            ("11", "Noviembre"),
                            ("12", "Diciembre"),
                        ],
                        max_length=25,
                        verbose_name="mes",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="año")),
                ("descripcion", models.TextField(verbose_name="descripcion")),
                ("archivo", models.FileField(upload_to="archivo_evaluacion/")),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "asunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archivar.asuntoregister",
                        verbose_name="asunto",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archivar.nivel",
                        verbose_name="nivel",
                    ),
                ),
                (
                    "t_eval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archivar.tevaluacion",
                        verbose_name="t_evaluacion",
                    ),
                ),
            ],
        ),
    ]
