# Generated by Django 5.1.1 on 2025-05-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archivar", "0005_asuntoevaluacion_tevaluacion_archmodelosevaluacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archmodelosevaluacion",
            name="asunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archivar.asuntoevaluacion",
                verbose_name="asunto",
            ),
        ),
    ]
