# Generated by Django 5.1.1 on 2024-11-12 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambito",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_ambito",
                    models.CharField(max_length=50, verbose_name="denominacion_ambito"),
                ),
            ],
            options={
                "verbose_name": "Ambito",
                "verbose_name_plural": "Ambitos",
                "db_table": "Ambito_pof",
            },
        ),
        migrations.CreateModel(
            name="CargosHoras",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "ceic",
                    models.ImageField(default=0, upload_to="", verbose_name="ceic"),
                ),
                (
                    "denom_cargoshoras",
                    models.CharField(
                        max_length=255, verbose_name="denominacion_cargoshoras"
                    ),
                ),
            ],
            options={
                "verbose_name": "CargoHoras",
                "verbose_name_plural": "CargosHoras",
                "db_table": "CargosHoras_pof",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_categoria",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "Categoria_pof",
            },
        ),
        migrations.CreateModel(
            name="DepartamentoLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_departamento",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_departamento"
                    ),
                ),
                (
                    "denom_localidad",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "DepartamentoLocalidad",
                "verbose_name_plural": "DepartamentosLocalidades",
                "db_table": "DptosLoc_pof",
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_jornada",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_jornada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada",
                "verbose_name_plural": "Jornadas",
                "db_table": "Jornadas_pof",
            },
        ),
        migrations.CreateModel(
            name="Modalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_modalidad",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_modalidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modalidad",
                "verbose_name_plural": "Modalidades",
                "db_table": "Modalidad_pof",
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_nivel",
                    models.CharField(max_length=50, verbose_name="denominacion_nivel"),
                ),
            ],
            options={
                "verbose_name": "Nivel",
                "verbose_name_plural": "Niveles",
                "db_table": "Nivel_pof",
            },
        ),
        migrations.CreateModel(
            name="Regional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_regional",
                    models.CharField(
                        max_length=50, verbose_name="denominacion_regional"
                    ),
                ),
            ],
            options={
                "verbose_name": "Regional",
                "verbose_name_plural": "Regionales",
                "db_table": "Regionales_pof",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_sector",
                    models.CharField(max_length=50, verbose_name="denominacion_sector"),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
                "db_table": "Sector_pof",
            },
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "denom_zona",
                    models.CharField(max_length=255, verbose_name="denominacion_zona"),
                ),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
                "db_table": "Zonas_pof",
            },
        ),
        migrations.CreateModel(
            name="UnidadServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cue",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Este campo debe contener solo dígitos.",
                                regex="^\\d+$",
                            )
                        ],
                        verbose_name="Cue",
                    ),
                ),
                (
                    "anexo",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Este campo debe contener solo dígitos.",
                                regex="^\\d+$",
                            )
                        ],
                        verbose_name="Anexo",
                    ),
                ),
                ("cuof", models.IntegerField(default=0, verbose_name="Cuof")),
                (
                    "cuof_anexo",
                    models.IntegerField(default=0, verbose_name="Cuof_Anexo"),
                ),
                (
                    "cui",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Este campo debe contener solo dígitos.",
                                regex="^\\d+$",
                            )
                        ],
                        verbose_name="Cui",
                    ),
                ),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "ubicacion",
                    models.CharField(max_length=255, verbose_name="Ubicacion"),
                ),
                ("nro", models.IntegerField(default=0, verbose_name="Nro")),
                (
                    "ambito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.ambito",
                        verbose_name="Ambito",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamento_unidad",
                        to="pof.departamentolocalidad",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.jornada",
                        verbose_name="Jornada",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localidad_unidad",
                        to="pof.departamentolocalidad",
                        verbose_name="Localidad",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.modalidad",
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.nivel",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.regional",
                        verbose_name="Regional",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.sector",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pof.zona",
                        verbose_name="Zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad_Servicio",
                "verbose_name_plural": "Unidades_Servicios",
                "db_table": "UnidadesServicio_pof",
            },
        ),
    ]
