# Generated by Django 5.1.1 on 2024-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pof", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoshoras",
            name="estado",
            field=models.BooleanField(default=True, verbose_name="estado"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras",
            name="nivel",
            field=models.CharField(default=1, max_length=50, verbose_name="nivel"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras",
            name="puntos",
            field=models.ImageField(default=0, upload_to="", verbose_name="puntos"),
            preserve_default=False,
        ),
    ]
