# Generated by Django 5.1.1 on 2024-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pof", "0004_unidadservicio_cueanexo_asignacionpof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoshoras",
            name="ceic",
            field=models.IntegerField(default=0, verbose_name="ceic"),
        ),
        migrations.AlterField(
            model_name="cargoshoras",
            name="puntos",
            field=models.IntegerField(verbose_name="puntos"),
        ),
    ]
