# Generated by Django 5.1.1 on 2024-11-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pof", "0005_alter_cargoshoras_ceic_alter_cargoshoras_puntos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoshoras",
            name="nivel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pof.nivel",
                verbose_name="nivel",
            ),
        ),
    ]
