# Generated by Django 5.1.1 on 2024-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pof", "0006_alter_cargoshoras_nivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleasignacionpof",
            name="cant_car",
            field=models.IntegerField(default=0, verbose_name="Cant_cargos"),
        ),
        migrations.AddField(
            model_name="detalleasignacionpof",
            name="cant_hs",
            field=models.IntegerField(default=0, verbose_name="Cant_horas"),
        ),
    ]
