# Generated by Django 5.2.16 on 2026-07-28 14:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecialDocenteBnh",
            fields=[
                (
                    "cuil",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("apellido", models.CharField(blank=True, max_length=150, null=True)),
                ("nombre", models.CharField(blank=True, max_length=150, null=True)),
                ("estado", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": '"bnh"."personas"',
                "ordering": ["apellido", "nombre", "cuil"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EspecialPadronOferta",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(blank=True, max_length=9, null=True)),
                ("nom_est", models.TextField(blank=True, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("acronimo", models.CharField(blank=True, max_length=50, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.TextField(blank=True, null=True)),
                ("ambito", models.TextField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("region_loc", models.TextField(blank=True, null=True)),
                ("ref_loc", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("numero", models.TextField(blank=True, null=True)),
                ("localidad", models.TextField(blank=True, null=True)),
                ("departamento", models.TextField(blank=True, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("resploc_cuitcuil", models.TextField(blank=True, null=True)),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Oferta Especial desde Padrón",
                "verbose_name_plural": "Ofertas Especial desde Padrón",
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EspecialRolUsuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Rol de usuario Especial",
                "verbose_name_plural": "Roles de usuario Especial",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EspecialUsuarioPerfil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Perfil de usuario Especial",
                "verbose_name_plural": "Perfiles de usuario Especial",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CatalogoTipoEstructuraEspecial",
            fields=[
                (
                    "cd_tipoestructuraespecial",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de estructura especial",
                "verbose_name_plural": "Tipos de estructuras especiales",
                "db_table": '"especial"."catalogo_tipo_estructura"',
            },
        ),
        migrations.CreateModel(
            name="CatalogoTipoRangoEtario",
            fields=[
                (
                    "cd_tiporangoetario",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de rango etario",
                "verbose_name_plural": "Tipos de rangos etarios",
                "db_table": '"especial"."catalogo_rango_etario"',
            },
        ),
        migrations.CreateModel(
            name="ModalidadDictadoTipo",
            fields=[
                (
                    "cd_modalidad_dictado",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de modalidad de cursado",
                "verbose_name_plural": "Tipos de modalidad de cursado",
                "db_table": '"especial"."modalidad_dictado_tipo"',
            },
        ),
        migrations.CreateModel(
            name="SeccionTipo",
            fields=[
                (
                    "cd_tipo_seccion",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de sección",
                "verbose_name_plural": "Tipos de sección",
                "db_table": '"especial"."seccion_tipo"',
            },
        ),
        migrations.CreateModel(
            name="SinoTipo",
            fields=[
                ("cd_sino", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Si/No/Sin info",
                "verbose_name_plural": "Si/No/Sin info",
                "db_table": '"especial"."sino_tipo"',
            },
        ),
        migrations.CreateModel(
            name="TurnoTipo",
            fields=[
                ("cd_turno", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "db_table": '"especial"."turno_tipo"',
            },
        ),
        migrations.CreateModel(
            name="EspecialCiclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=120)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("actual", models.BooleanField(default=False)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo Especial",
                "verbose_name_plural": "Ciclos Especial",
                "db_table": '"especial"."ciclos"',
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="EspecialAlumnoBanco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                (
                    "alumno_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "alumno_documento_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                (
                    "alumno_cuil_snapshot",
                    models.CharField(blank=True, editable=False, max_length=11),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bancos_especial",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_banco_especial",
                        to="especial.especialciclo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno en Banco Especial",
                "verbose_name_plural": "Alumnos en Banco Especial",
                "db_table": '"especial"."alumno_banco"',
            },
        ),
        migrations.CreateModel(
            name="EspecialDocenteBanco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("docente_cuil", models.CharField(db_index=True, max_length=11)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                (
                    "docente_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "docente_dni_snapshot",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "docente_estado_bnh_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docentes_banco_especial",
                        to="especial.especialciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente en Banco Especial",
                "verbose_name_plural": "Docentes en Banco Especial",
                "db_table": '"especial"."docente_banco"',
            },
        ),
        migrations.CreateModel(
            name="SeccionEspecial",
            fields=[
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("nombre_seccion", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("capacidad_total", models.PositiveIntegerField()),
                (
                    "lugar_dictado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("cerrado", "Cerrado"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "turno_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=80),
                ),
                (
                    "tipo_seccion_snapshot",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "estructura_snapshot",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.especialciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        db_column="cd_modalidad_dictado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.modalidaddictadotipo",
                    ),
                ),
                (
                    "rango_etario",
                    models.ForeignKey(
                        db_column="cd_tiporangoetario",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.catalogotiporangoetario",
                    ),
                ),
                (
                    "tipo_estructura_especial",
                    models.ForeignKey(
                        db_column="cd_tipoestructuraespecial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.catalogotipoestructuraespecial",
                    ),
                ),
                (
                    "cd_tipo_seccion",
                    models.ForeignKey(
                        db_column="cd_tipo_seccion",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.secciontipo",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        db_column="cd_turno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.turnotipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Educación Especial",
                "verbose_name_plural": "Secciones de Educación Especial",
                "db_table": '"especial"."seccion"',
            },
        ),
        migrations.CreateModel(
            name="DocenteSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("docente_cuil", models.CharField(db_index=True, max_length=11)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("titular", "Titular"),
                            ("suplente", "Suplente"),
                            ("apoyo", "Apoyo"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                (
                    "docente_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "docente_dni_snapshot",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "docente_estado_bnh_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docentes",
                        to="especial.seccionespecial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente de Sección Especial",
                "verbose_name_plural": "Docentes de Secciones Especiales",
                "db_table": '"especial"."docente_seccion"',
            },
        ),
        migrations.CreateModel(
            name="AlumnoSeccion",
            fields=[
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("baja", "Baja")],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones_especial",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="especial.seccionespecial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno de Educación Especial",
                "verbose_name_plural": "Alumnos de Educación Especial",
                "db_table": '"especial"."alumno_seccion"',
            },
        ),
        migrations.AddConstraint(
            model_name="especialciclo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actual", True)),
                fields=("actual",),
                name="uq_especial_ciclo_actual",
            ),
        ),
        migrations.AddIndex(
            model_name="especialalumnobanco",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_esp_alum_banco_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="especialalumnobanco",
            index=models.Index(
                fields=["alumno", "estado"], name="idx_esp_alum_banco_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="especialalumnobanco",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("cueanexo", "ciclo", "alumno"),
                name="uq_esp_alumno_banco_act",
            ),
        ),
        migrations.AddIndex(
            model_name="especialdocentebanco",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_esp_doc_banco_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="especialdocentebanco",
            index=models.Index(
                fields=["docente_cuil", "estado"], name="idx_esp_doc_banco_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="especialdocentebanco",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("cueanexo", "ciclo", "docente_cuil"),
                name="uq_esp_docente_banco_act",
            ),
        ),
        migrations.AddIndex(
            model_name="docenteseccion",
            index=models.Index(
                fields=["docente_cuil", "estado"], name="idx_esp_doc_sec_cuil_est"
            ),
        ),
        migrations.AddIndex(
            model_name="docenteseccion",
            index=models.Index(
                fields=["seccion", "estado"], name="idx_esp_doc_sec_grp_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="docenteseccion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("seccion", "docente_cuil"),
                name="uq_esp_doc_sec_cuil_act",
            ),
        ),
        migrations.AddConstraint(
            model_name="docenteseccion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("seccion", "rol"),
                name="uq_esp_doc_sec_rol_act",
            ),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(fields=["estado"], name="idx_esp_alsec_est"),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(
                fields=["alumno", "estado"], name="idx_esp_alsec_alum_est"
            ),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(
                fields=["seccion", "estado"], name="idx_esp_alsec_sec_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="alumnoseccion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("alumno", "seccion"),
                name="uq_esp_alumno_seccion_abierta",
            ),
        ),
        migrations.AddIndex(
            model_name="seccionespecial",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_esp_sec_cue_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="seccionespecial",
            index=models.Index(
                fields=["cueanexo", "estado"], name="idx_esp_sec_cue_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="seccionespecial",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo", "nombre_seccion", "cd_tipo_seccion"),
                name="uq_esp_sec_cue_cic_nom_tipo",
            ),
        ),
    ]
