# Generated by Django 5.2.15 on 2026-06-30 13:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecialPadronOferta",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(blank=True, max_length=9, null=True)),
                ("nom_est", models.TextField(blank=True, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("acronimo", models.CharField(blank=True, max_length=50, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.TextField(blank=True, null=True)),
                ("ambito", models.TextField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("region_loc", models.TextField(blank=True, null=True)),
                ("ref_loc", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("numero", models.TextField(blank=True, null=True)),
                ("localidad", models.TextField(blank=True, null=True)),
                ("departamento", models.TextField(blank=True, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("resploc_cuitcuil", models.TextField(blank=True, null=True)),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Oferta Especial desde Padrón",
                "verbose_name_plural": "Ofertas Especial desde Padrón",
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EspecialRolUsuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Rol de usuario Especial",
                "verbose_name_plural": "Roles de usuario Especial",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EspecialUsuarioPerfil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Perfil de usuario Especial",
                "verbose_name_plural": "Perfiles de usuario Especial",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CatalogoTipoEstructuraEspecial",
            fields=[
                (
                    "cd_tipoestructuraespecial",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de estructura especial",
                "verbose_name_plural": "Tipos de estructuras especiales",
                "db_table": "catalogo_tipo_estructura_especial",
            },
        ),
        migrations.CreateModel(
            name="CatalogoTipoRangoEtario",
            fields=[
                (
                    "cd_tiporangoetario",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de rango etario",
                "verbose_name_plural": "Tipos de rangos etarios",
                "db_table": "catalogo_tipo_rango_etario",
            },
        ),
        migrations.CreateModel(
            name="ModalidadDictadoTipo",
            fields=[
                (
                    "cd_modalidad_dictado",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de modalidad de cursado",
                "verbose_name_plural": "Tipos de modalidad de cursado",
                "db_table": "modalidad_dictado_tipo",
            },
        ),
        migrations.CreateModel(
            name="seccion_tipo",
            fields=[
                (
                    "cd_tipo_seccion",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de sección",
                "verbose_name_plural": "Tipos de sección",
                "db_table": "seccion_tipo",
            },
        ),
        migrations.CreateModel(
            name="SinoTipo",
            fields=[
                ("cd_sino", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Si/No/Sin info",
                "verbose_name_plural": "Si/No/Sin info",
                "db_table": "sino_tipo",
            },
        ),
        migrations.CreateModel(
            name="TurnoTipo",
            fields=[
                ("cd_turno", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "db_table": "turno_tipo",
            },
        ),
        migrations.CreateModel(
            name="EspecialCiclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=120)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("actual", models.BooleanField(default=False)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo Especial",
                "verbose_name_plural": "Ciclos Especial",
                "db_table": "especial_ciclos",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="SeccionEspecial",
            fields=[
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("nombre_seccion", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("capacidad_total", models.PositiveIntegerField()),
                (
                    "lugar_dictado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("cerrado", "Cerrado"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_tipo_seccion",
                    models.ForeignKey(
                        db_column="cd_tipo_seccion",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.seccion_tipo",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.especialciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        db_column="cd_modalidad_dictado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.modalidaddictadotipo",
                    ),
                ),
                (
                    "rango_etario",
                    models.ForeignKey(
                        db_column="cd_tiporangoetario",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.catalogotiporangoetario",
                    ),
                ),
                (
                    "tipo_estructura_especial",
                    models.ForeignKey(
                        db_column="cd_tipoestructuraespecial",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.catalogotipoestructuraespecial",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        db_column="cd_turno",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones",
                        to="especial.turnotipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Educación Especial",
                "verbose_name_plural": "Secciones de Educación Especial",
                "db_table": "especial_seccion",
            },
        ),
        migrations.CreateModel(
            name="AlumnoSeccion",
            fields=[
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones_especial",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="especial.seccionespecial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno de Educación Especial",
                "verbose_name_plural": "Alumnos de Educación Especial",
                "db_table": "especial_alumnoseccion",
            },
        ),
        migrations.AddConstraint(
            model_name="especialciclo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actual", True)),
                fields=("actual",),
                name="uq_especial_ciclo_actual",
            ),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(fields=["estado"], name="idx_esp_alsec_est"),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(
                fields=["alumno", "estado"], name="idx_esp_alsec_alum_est"
            ),
        ),
        migrations.AddIndex(
            model_name="alumnoseccion",
            index=models.Index(
                fields=["seccion", "estado"], name="idx_esp_alsec_sec_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="alumnoseccion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado__in", ["activo", "inactivo"])),
                fields=("alumno", "seccion"),
                name="uq_esp_alumno_seccion_abierta",
            ),
        ),
        migrations.AddIndex(
            model_name="seccionespecial",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_esp_sec_cue_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="seccionespecial",
            index=models.Index(
                fields=["cueanexo", "estado"], name="idx_esp_sec_cue_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="seccionespecial",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo", "nombre_seccion", "cd_tipo_seccion"),
                name="uq_esp_sec_cue_cic_nom_tipo",
            ),
        ),
    ]
