# Generated by Django 5.2.16 on 2026-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialciclo",
            name="cerrado",
            field=models.BooleanField(default=False),
        ),
    ]
