# Generated by Django 5.2.17 on 2026-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialalumnobanco",
            name="matricula_compartida",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
