# Generated by Django 5.2.17 on 2026-08-13 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0002_especialalumnobanco_matricula_compartida"),
        ("especial", "0002_especialciclo_cerrado"),
    ]

    operations = []
