# Generated by Django 5.2.17
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("especial", "0003_merge_20260812_2335"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecialTrasladoDocente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("docente_cuil", models.CharField(db_index=True, max_length=11)),
                ("docente_nombre_snapshot", models.CharField(blank=True, max_length=255)),
                ("docente_dni_snapshot", models.CharField(blank=True, max_length=20)),
                ("cueanexo_origen", models.CharField(db_index=True, max_length=9)),
                ("cueanexo_destino", models.CharField(db_index=True, max_length=9)),
                ("estado", models.CharField(choices=[("en_transito", "En tránsito"), ("aplicado", "Aplicado"), ("cancelado", "Cancelado")], db_index=True, default="en_transito", max_length=20)),
                ("fecha_solicitud", models.DateField(default=django.utils.timezone.localdate)),
                ("fecha_aplicacion", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("actualizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="especial_trasladodocente_actualizados", to=settings.AUTH_USER_MODEL)),
                ("creado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="especial_trasladodocente_creados", to=settings.AUTH_USER_MODEL)),
                ("ciclo_destino", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="traslados_docentes_destino", to="especial.especialciclo")),
                ("ciclo_origen", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="traslados_docentes_origen", to="especial.especialciclo")),
            ],
            options={
                "db_table": '"especial"."traslado_docente"',
            },
        ),
        migrations.AddConstraint(
            model_name="especialtrasladodocente",
            constraint=models.UniqueConstraint(condition=models.Q(("estado", "en_transito")), fields=("docente_cuil", "cueanexo_destino", "ciclo_destino"), name="uq_esp_traslado_docente_transito"),
        ),
        migrations.AddIndex(
            model_name="especialtrasladodocente",
            index=models.Index(fields=["cueanexo_destino", "ciclo_destino", "estado"], name="idx_esp_tras_doc_dest"),
        ),
    ]
