# Generated by Django 5.0 on 2026-08-13

from django.db import migrations, models


def reemplazar_rol_apoyo(apps, schema_editor):
    DocenteSeccion = apps.get_model("especial", "DocenteSeccion")
    DocenteSeccion.objects.filter(rol="apoyo").update(rol="interino")


def restaurar_rol_apoyo(apps, schema_editor):
    DocenteSeccion = apps.get_model("especial", "DocenteSeccion")
    DocenteSeccion.objects.filter(rol="interino").update(rol="apoyo")


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0004_especialtrasladodocente"),
    ]

    operations = [
        migrations.RunPython(
            reemplazar_rol_apoyo,
            restaurar_rol_apoyo,
        ),
        migrations.AlterField(
            model_name="docenteseccion",
            name="rol",
            field=models.CharField(
                choices=[
                    ("titular", "Titular"),
                    ("suplente", "Suplente"),
                    ("interino", "Interino"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
