# Generated by Django 5.2 on 2026-08-20

from django.db import migrations, models
from django.db.models import Count


def eliminar_asignaciones_duplicadas(apps, schema_editor):
    """
    Conserva la asignación más nueva de cada docente en cada sección.

    Los registros anteriores no representan historial funcional: la relación
    docente-sección debe ser única, independientemente de su estado.
    """
    DocenteSeccion = apps.get_model("especial", "DocenteSeccion")

    grupos_duplicados = (
        DocenteSeccion.objects
        .values("seccion_id", "docente_cuil")
        .annotate(cantidad=Count("id"))
        .filter(cantidad__gt=1)
    )

    for grupo in grupos_duplicados:
        asignaciones = list(
            DocenteSeccion.objects
            .filter(
                seccion_id=grupo["seccion_id"],
                docente_cuil=grupo["docente_cuil"],
            )
            .order_by("-creado_en", "-id")
        )
        for asignacion in asignaciones[1:]:
            asignacion.delete()


def restaurar_asignaciones_duplicadas(apps, schema_editor):
    # La eliminación de duplicados no puede revertirse sin una copia previa.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0005_docenteseccion_interino"),
    ]

    operations = [
        migrations.RunPython(
            eliminar_asignaciones_duplicadas,
            restaurar_asignaciones_duplicadas,
        ),
        migrations.RemoveConstraint(
            model_name="docenteseccion",
            name="uq_esp_doc_sec_cuil_act",
        ),
        migrations.AddConstraint(
            model_name="docenteseccion",
            constraint=models.UniqueConstraint(
                fields=("seccion", "docente_cuil"),
                name="uq_esp_doc_sec_cuil",
            ),
        ),
    ]
