# Generated by Django 5.2 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0006_unica_asignacion_docente_seccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="seccionespecial",
            name="oferta",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Oferta educativa seleccionada para esta sección.",
                max_length=255,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="seccionespecial",
            name="uq_esp_sec_cue_cic_nom_tipo",
        ),
        migrations.AddConstraint(
            model_name="seccionespecial",
            constraint=models.UniqueConstraint(
                fields=(
                    "cueanexo",
                    "ciclo",
                    "nombre_seccion",
                    "cd_tipo_seccion",
                    "oferta",
                ),
                name="uq_esp_sec_cue_cic_nom_tipo",
            ),
        ),
    ]
