# Generated by Django 5.2 on 2026-09-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cef", "0013_alter_cefturno_options_and_more"),
        ("especial", "0007_oferta_seccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecialDatosCUEAnexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="especial_especialdatoscueanexo_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficio_alimentario_gratuito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_especial_beneficio",
                        to="cef.cefbeneficiosinotipo",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_cueanexo",
                        to="especial.especialciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="especial_especialdatoscueanexo_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "espacio_comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_especial_espacio",
                        to="cef.cefespaciocomedortipo",
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_especial_fuente",
                        to="cef.ceffuentefinanciamientotipo",
                    ),
                ),
                (
                    "prestacion_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_especial_prestacion",
                        to="cef.cefprestaciontipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datos CUE-Anexo Especial",
                "verbose_name_plural": "Datos CUE-Anexo Especial",
                "db_table": '"especial"."datos_cueanexo"',
                "ordering": ["cueanexo", "-ciclo__anio"],
            },
        ),
        migrations.AddConstraint(
            model_name="especialdatoscueanexo",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo"),
                name="uq_esp_datos_cue_cic",
            ),
        ),
        migrations.AddIndex(
            model_name="especialdatoscueanexo",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_esp_datos_cue_cic"
            ),
        ),
    ]
