# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def vincular_inscripciones_a_periodos_banco(apps, schema_editor):
    """Asocia registros históricos al período más probable del banco.

    Las inscripciones creadas antes de esta migración no guardaban una
    referencia al período del banco. Se usa el mismo alumno, CUE-Anexo,
    ciclo, intervalo de fechas y orden de creación para recuperarla.
    """
    AlumnoSeccion = apps.get_model("especial", "AlumnoSeccion")
    EspecialAlumnoBanco = apps.get_model("especial", "EspecialAlumnoBanco")

    for inscripcion in AlumnoSeccion.objects.filter(alumno_banco__isnull=True).iterator():
        bancos = EspecialAlumnoBanco.objects.filter(
            alumno_id=inscripcion.alumno_id,
            cueanexo=inscripcion.seccion.cueanexo,
            ciclo_id=inscripcion.seccion.ciclo_id,
            fecha_alta__lte=inscripcion.fecha_inscripcion,
        )
        fecha_fin = inscripcion.fecha_baja or inscripcion.fecha_inscripcion
        bancos = bancos.filter(
            Q(fecha_baja__isnull=True) | Q(fecha_baja__gte=fecha_fin)
        )
        banco = bancos.filter(creado_en__lte=inscripcion.creado_en).order_by(
            "-creado_en", "-pk"
        ).first() or bancos.order_by("-creado_en", "-pk").first()
        if banco:
            AlumnoSeccion.objects.filter(pk=inscripcion.pk).update(alumno_banco_id=banco.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0008_especialdatoscueanexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnoseccion",
            name="alumno_banco",
            field=models.ForeignKey(
                blank=True,
                help_text="Período del banco de alumnos al que pertenece esta inscripción.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones_seccion",
                to="especial.especialalumnobanco",
            ),
        ),
        migrations.RunPython(vincular_inscripciones_a_periodos_banco, migrations.RunPython.noop),
    ]
