# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0009_alumnoseccion_alumno_banco"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="docenteseccion",
            name="uq_esp_doc_sec_cuil",
        ),
        migrations.AddConstraint(
            model_name="docenteseccion",
            constraint=models.UniqueConstraint(
                condition=Q(estado="activo"),
                fields=("seccion", "docente_cuil"),
                name="uq_esp_doc_sec_cuil",
            ),
        ),
    ]
