# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def vincular_asignaciones_a_periodos_banco(apps, schema_editor):
    """Vincula asignaciones existentes con su período de banco probable."""
    DocenteSeccion = apps.get_model("especial", "DocenteSeccion")
    EspecialDocenteBanco = apps.get_model("especial", "EspecialDocenteBanco")

    for asignacion in DocenteSeccion.objects.filter(docente_banco__isnull=True).iterator():
        bancos = EspecialDocenteBanco.objects.filter(
            cueanexo=asignacion.seccion.cueanexo,
            ciclo_id=asignacion.seccion.ciclo_id,
            docente_cuil=asignacion.docente_cuil,
        )
        if asignacion.fecha_desde:
            bancos = bancos.filter(fecha_alta__lte=asignacion.fecha_desde)
            fecha_fin = asignacion.fecha_hasta or asignacion.fecha_desde
            bancos = bancos.filter(
                Q(fecha_baja__isnull=True) | Q(fecha_baja__gte=fecha_fin)
            )
        banco = bancos.filter(creado_en__lte=asignacion.creado_en).order_by(
            "-creado_en", "-pk"
        ).first() or bancos.order_by("-creado_en", "-pk").first()
        if banco:
            DocenteSeccion.objects.filter(pk=asignacion.pk).update(
                docente_banco_id=banco.pk
            )


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0010_historial_asignaciones_docente"),
    ]

    operations = [
        migrations.AddField(
            model_name="docenteseccion",
            name="docente_banco",
            field=models.ForeignKey(
                blank=True,
                help_text="Período del banco al que pertenece esta asignación.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaciones_seccion",
                to="especial.especialdocentebanco",
            ),
        ),
        migrations.RunPython(
            vincular_asignaciones_a_periodos_banco,
            migrations.RunPython.noop,
        ),
    ]
