# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0011_historial_asignaciones_docente_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docenteseccion",
            name="docente_banco",
            field=models.ForeignKey(
                blank=True,
                help_text="Período del banco al que pertenece esta asignación.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaciones_banco",
                to="especial.especialdocentebanco",
            ),
        ),
    ]
