# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("especial", "0012_renombrar_relacion_docente_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumnoseccion",
            name="alumno_banco",
            field=models.ForeignKey(
                blank=True,
                help_text="Período del banco de alumnos al que pertenece esta inscripción.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones_banco",
                to="especial.especialalumnobanco",
            ),
        ),
    ]
