# Generated by Django 5.2.17 on 2026-09-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0014_tipo_inclusion_alumno_seccion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialdatoscueanexo",
            options={"ordering": ["cueanexo", "-ciclo__anio"]},
        ),
        migrations.AlterField(
            model_name="especialdatoscueanexo",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="especialdatoscueanexo",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="especialtrasladodocente",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="especialtrasladodocente",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterConstraint(
            model_name="especialciclo",
            name="uq_especial_ciclo_actual",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actual", True)),
                fields=("actual",),
                name="uq_especial_ciclo_actual",
                violation_error_message="Ya existe un ciclo marcado como actual. Desmarcá «Ciclo actual» o elegí otro ciclo.",
            ),
        ),
    ]
