# Generated by Django 5.2.17 on 2026-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0015_alter_especialdatoscueanexo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="especialrolusuario",
            table='"public"."usuarios_rol"',
        ),
        migrations.AlterModelTable(
            name="especialusuarioperfil",
            table='"public"."usuarios_perfilusuario"',
        ),
    ]
