# Generated by Django 5.2.17 on 2026-10-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("especial", "0016_alter_especialrolusuario_table_and_more"),
        ("bnhpersonas", "0037_ceic_opcional_no_corresponde"),
    ]

    operations = [
        migrations.AddField(
            model_name="docenteseccion",
            name="cargo_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="Cargo BNH validado utilizado para esta asignación.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaciones_especiales",
                to="bnhpersonas.registroactividades",
            ),
        ),
        migrations.AddField(
            model_name="docenteseccion",
            name="cargo_ceic_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="docenteseccion",
            name="cargo_situacion_revista_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="docenteseccion",
            name="cargo_turno_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name="docenteseccion",
            name="cargo_nivel_curricular_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
