# Generated by Django 5.1.1 on 2025-02-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="Total")),
            ],
            options={
                "verbose_name": "Asignacion",
                "verbose_name_plural": "Asignaciones",
                "db_table": "Asignacion_Representadas",
                "ordering": ["replegales"],
            },
        ),
        migrations.CreateModel(
            name="EscuelasRepresentadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("region", models.CharField(max_length=100, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Escuela_Representada",
                "verbose_name_plural": "Escuelas_Representadas",
                "db_table": "escuelas_representadas",
            },
        ),
        migrations.CreateModel(
            name="RepresentantesLegales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                ("cuil", models.CharField(max_length=11, verbose_name="CUIL")),
                ("apellido", models.CharField(max_length=255, verbose_name="Apellido")),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                (
                    "f_nac",
                    models.DateField(default="1900-01-01", verbose_name="Fecha_Nac"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=9,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "sit_revista",
                    models.CharField(
                        choices=[
                            ("Titular", "Titular"),
                            ("Interino", "Interino"),
                            ("Suplente", "Suplente"),
                            ("Contratado", "Contratado"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Sit_Revista",
                    ),
                ),
                (
                    "f_designacion",
                    models.DateField(
                        default="1900-01-01", verbose_name="Fecha_Designacion"
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Correo")),
                ("telefono", models.CharField(max_length=11, verbose_name="Teléfono")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("R.E. 1", "R.E. 1"),
                            ("R.E. 2", "R.E. 2"),
                            ("R.E. 3", "R.E. 3"),
                            ("R.E. 4-A", "R.E. 4-A"),
                            ("R.E. 4-B", "R.E. 4-B"),
                            ("R.E. 5", "R.E. 5"),
                            ("R.E. 6", "R.E. 6"),
                            ("R.E. 7", "R.E. 7"),
                            ("R.E. 8-A", "R.E. 8-A"),
                            ("R.E. 8-B", "R.E. 8-B"),
                            ("R.E. 9", "R.E. 9"),
                            ("R.E. 10-A", "R.E. 10-A"),
                            ("R.E. 10-B", "R.E. 10-B"),
                            ("R.E. 10-C", "R.E. 10-C"),
                            ("SUB. R.E. 1-A", "SUB. R.E. 1-A"),
                            ("SUB. R.E. 1-B", "SUB. R.E. 1-B"),
                            ("SUB. R.E. 2", "SUB. R.E. 2"),
                            ("SUB. R.E. 3", "SUB. R.E. 3"),
                            ("SUB. R.E. 5", "SUB. R.E. 5"),
                        ],
                        max_length=100,
                        verbose_name="Regional",
                    ),
                ),
            ],
            options={
                "verbose_name": "RepresentanteLegal_Escuela",
                "verbose_name_plural": "RepresentantesLegales_Escuelas",
                "db_table": "representantelegal_escuelas",
            },
        ),
        migrations.CreateModel(
            name="DetalleAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="represlegales.asignacion",
                        verbose_name="Asignacion",
                    ),
                ),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="represlegales.escuelasrepresentadas",
                        verbose_name="Escuela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle_Escuela_Representada",
                "verbose_name_plural": "Detalles_Escuelas_Representadas",
                "db_table": "Detalle_Asignacion_Representadas",
                "ordering": ["escuela"],
            },
        ),
        migrations.AddField(
            model_name="asignacion",
            name="replegales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="represlegales.representanteslegales",
                verbose_name="Replegales",
            ),
        ),
    ]
