# Generated by Django 5.1.1 on 2025-03-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeguimientoSIE2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("region", models.CharField(max_length=50, verbose_name="Regional")),
                ("agente", models.CharField(max_length=100, verbose_name="agente")),
                (
                    "localidad",
                    models.CharField(max_length=100, verbose_name="localidad"),
                ),
                ("cue", models.CharField(max_length=20, verbose_name="Cue")),
                ("anexo", models.CharField(max_length=10, verbose_name="Anexo")),
                ("grado", models.CharField(max_length=30, verbose_name="Grado")),
                ("seccion", models.CharField(max_length=30, verbose_name="Sección")),
                ("turno_nombre", models.CharField(max_length=50, verbose_name="Turno")),
                (
                    "ciclo_lectivo",
                    models.CharField(max_length=10, verbose_name="Ciclo"),
                ),
                (
                    "estado_inscripcion",
                    models.CharField(max_length=50, verbose_name="Estado"),
                ),
                ("nro_documento", models.CharField(max_length=20, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=50, verbose_name="Nombres")),
                (
                    "discapacidad",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Discapacidad",
                    ),
                ),
                (
                    "comunidad_aborigen",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Comunidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "seguimiento_sie",
                "verbose_name_plural": "seguimientos_sies",
                "db_table": "seguimiento_sie_2025",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SIESegimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agente", models.CharField(max_length=100, verbose_name="Agente")),
                ("escuela", models.CharField(max_length=100, verbose_name="Escuela")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("region", models.CharField(max_length=50, verbose_name="Regional")),
                ("nivel", models.CharField(max_length=50, verbose_name="Nivel")),
                ("sieant", models.IntegerField(verbose_name="Sie_anterior")),
                ("sieact", models.IntegerField(verbose_name="Sie_actual")),
                ("dni_agente", models.CharField(max_length=8, verbose_name="DNI")),
            ],
            options={
                "verbose_name": "sie_seguimiento",
                "verbose_name_plural": "sies_seguimientos",
                "db_table": "sie_seguimiento",
                "managed": False,
            },
        ),
    ]
