# Generated by Django 5.2.8 on 2026-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicadoresie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeSGE",
            fields=[
                ("id_excel", models.CharField(blank=True, max_length=100, null=True)),
                ("cueanexo", models.CharField(blank=True, max_length=20, null=True)),
                ("agente", models.CharField(blank=True, max_length=150, null=True)),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "tipo_oferta",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=50, null=True)),
                ("ambito", models.CharField(blank=True, max_length=50, null=True)),
                ("regional", models.CharField(blank=True, max_length=50, null=True)),
                ("cue", models.CharField(blank=True, max_length=20, null=True)),
                ("anexo", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "escuela_cod_tel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("escuela_tel", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "escuela_email",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "responsable_apellido",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "responsable_nombre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telefono_responsable",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sge_2025", models.CharField(blank=True, max_length=50, null=True)),
                ("sge_2026", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "inscriptos_2025",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "inscriptos_2026",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Informe SGE",
                "verbose_name_plural": "Informes SGE",
                "db_table": "sie_seguimiento_actualizado2026",
                "managed": False,
            },
        ),
    ]
