# Generated by Django 5.2.8 on 2026-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicadoresie", "0002_informesge"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechaActualizacionSGE",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(verbose_name="Fecha de Actualización")),
            ],
            options={
                "verbose_name": "Fecha de Actualización SGE",
                "verbose_name_plural": "Fechas de Actualización SGE",
                "db_table": '"indicadores"."fecha_actualizacion_sge2026"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PadronRegional",
            fields=[
                (
                    "cueanexo",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CUE Anexo",
                    ),
                ),
                (
                    "nom_est",
                    models.CharField(max_length=255, verbose_name="Establecimiento"),
                ),
                (
                    "oferta",
                    models.TextField(blank=True, null=True, verbose_name="Oferta(s)"),
                ),
                (
                    "region_loc",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Región"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Localidad"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sector"
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ámbito"
                    ),
                ),
                ("acronimo", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.CharField(blank=True, max_length=50, null=True)),
                ("ref_loc", models.CharField(blank=True, max_length=100, null=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                (
                    "resploc_cuitcuil",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Padrón Regional",
                "verbose_name_plural": "Padrones Regionales",
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolUsuarioGlobal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsuarioPerfil",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsuarioVisualizador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(db_column="username", max_length=150, unique=True),
                ),
                ("is_superuser", models.BooleanField()),
                ("is_staff", models.BooleanField()),
            ],
            options={
                "db_table": "Usuario_Visualizador",
                "managed": False,
            },
        ),
    ]
