# Generated by Django 5.2.8 on 2026-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicadoresie", "0003_fechaactualizacionsge_padronregional_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisSgeRa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sistema", models.CharField(blank=True, max_length=20, null=True)),
                ("nivel", models.CharField(blank=True, max_length=100, null=True)),
                ("cueanexo", models.CharField(blank=True, max_length=20, null=True)),
                ("escuela", models.TextField(blank=True, null=True)),
                ("grado", models.CharField(blank=True, max_length=100, null=True)),
                ("seccion", models.CharField(blank=True, max_length=50, null=True)),
                ("turno", models.CharField(blank=True, max_length=50, null=True)),
                ("tipo_secc", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                ("origen_estructura_id", models.TextField(blank=True, null=True)),
                ("origen_grados", models.JSONField(blank=True, null=True)),
                ("origen_es_agrupada", models.BooleanField(blank=True, null=True)),
                ("origen_total", models.IntegerField(blank=True, null=True)),
                ("origen_componentes", models.JSONField(blank=True, null=True)),
                (
                    "calidad_registros_repetidos",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "calidad_inscripciones_multiseccion",
                    models.JSONField(blank=True, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("estado_padron_actual", models.TextField(blank=True, null=True)),
                ("en_padron_actual", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": '"public"."analisis_sge_ra"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuditoriaSgeRa",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("cueanexo", models.TextField()),
                ("tipo_situacion", models.TextField()),
                ("orden", models.IntegerField()),
                ("contexto_nivel", models.TextField(blank=True, null=True)),
                ("contexto_grado", models.TextField(blank=True, null=True)),
                ("contexto_seccion", models.TextField(blank=True, null=True)),
                ("contexto_turno", models.TextField(blank=True, null=True)),
                ("contexto_tipo_secc", models.TextField(blank=True, null=True)),
                ("titulo", models.TextField()),
                ("valor_ra", models.TextField()),
                ("valor_sge", models.TextField()),
                ("mensaje", models.TextField()),
                ("detalle", models.JSONField()),
                ("bloquea_revision", models.BooleanField()),
                ("motivo_bloqueo", models.TextField(blank=True, null=True)),
                ("dimension_codigo", models.TextField()),
                ("categoria_operativa", models.TextField()),
                ("comparabilidad_codigo", models.TextField()),
                ("resumen_diferencia", models.TextField()),
                ("accion_revision_codigo", models.TextField()),
                ("periodo_ra", models.SmallIntegerField(blank=True, null=True)),
                ("periodo_sge", models.SmallIntegerField(blank=True, null=True)),
                ("valor_ra_tipo", models.TextField()),
                ("valor_sge_tipo", models.TextField()),
                ("valor_ra_numero", models.BigIntegerField(blank=True, null=True)),
                ("valor_sge_numero", models.BigIntegerField(blank=True, null=True)),
                ("diferencia_absoluta", models.BigIntegerField(blank=True, null=True)),
                (
                    "diferencia_sge_menos_ra",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("comparacion_confiable", models.BooleanField()),
                (
                    "motivo_no_comparable_codigo",
                    models.TextField(blank=True, null=True),
                ),
                ("causa_sin_datos_codigo", models.TextField(blank=True, null=True)),
                ("detalle_version", models.SmallIntegerField()),
                (
                    "estado_padron_actual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("en_padron_actual", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": '"public"."auditoria_sge_ra"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuditoriaSgeRaEstado",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("valida", models.BooleanField()),
                ("estado_base", models.CharField(max_length=20)),
                ("estado_auditoria", models.CharField(max_length=20)),
                ("ultimo_intento_en", models.DateTimeField(blank=True, null=True)),
                ("base_refrescada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "auditoria_refrescada_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "ultimo_refresco_exitoso_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ultimo_error_en", models.DateTimeField(blank=True, null=True)),
                ("filas_base", models.BigIntegerField(blank=True, null=True)),
                ("filas_ra", models.BigIntegerField(blank=True, null=True)),
                ("filas_sge", models.BigIntegerField(blank=True, null=True)),
                ("cues_padron_activos", models.BigIntegerField(blank=True, null=True)),
                ("cues_ra_sge", models.BigIntegerField(blank=True, null=True)),
                ("cues_solo_ra", models.BigIntegerField(blank=True, null=True)),
                ("cues_solo_sge", models.BigIntegerField(blank=True, null=True)),
                (
                    "cues_sin_datos_ra_sge",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("cues_universo_total", models.BigIntegerField(blank=True, null=True)),
                ("situaciones", models.BigIntegerField(blank=True, null=True)),
                ("alcance", models.TextField()),
                ("fuente_ra", models.TextField()),
                ("fuente_sge", models.TextField()),
                ("version_motor", models.TextField()),
                ("detalle_estado", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": '"public"."auditoria_sge_ra_estado"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FechaActualizacionComparativaSgeRa",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(verbose_name="Fecha de Actualización")),
            ],
            options={
                "verbose_name": "Fecha de Actualización Comparativa SGE RA",
                "verbose_name_plural": "Fechas de Actualización Comparativa SGE RA",
                "db_table": '"indicadores"."fecha_actualizacion_sge"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ResumenSgeRa",
            fields=[
                (
                    "cueanexo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("escuela", models.TextField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "estado_padron_actual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("en_padron_actual", models.BooleanField(blank=True, null=True)),
                ("estado_actual", models.TextField(blank=True, null=True)),
                ("cantidad_situaciones_total", models.IntegerField()),
                ("cantidad_bloqueos_total", models.IntegerField()),
                ("tiene_situaciones", models.BooleanField()),
                ("tiene_bloqueos", models.BooleanField()),
                ("situaciones_por_tipo", models.JSONField()),
                ("bloqueos_por_tipo", models.JSONField()),
                ("estado_codigo", models.CharField(max_length=30)),
                ("estado", models.TextField()),
            ],
            options={
                "db_table": '"public"."resumen_sge_ra"',
                "managed": False,
            },
        ),
    ]
