# Generated by Django 5.1.1 on 2024-11-09 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="Total")),
            ],
            options={
                "verbose_name": "Asignacion",
                "verbose_name_plural": "Asignaciones",
                "db_table": "Asignacion",
                "ordering": ["supervisor"],
            },
        ),
        migrations.CreateModel(
            name="EscuelasSupervisadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("region", models.CharField(max_length=100, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Escuela_Supervisada",
                "verbose_name_plural": "Escuelas_Supervisadas",
                "db_table": "escuelas_supervisadas",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                ("apellido", models.CharField(max_length=255, verbose_name="Apellido")),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("email", models.EmailField(max_length=255, verbose_name="Correo")),
                ("telefono", models.CharField(max_length=11, verbose_name="Teléfono")),
                ("region", models.CharField(max_length=100, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Supervisor_Escuela",
                "verbose_name_plural": "Supervisores_Escuelas",
                "db_table": "supervisores_escuelas",
            },
        ),
        migrations.CreateModel(
            name="DetalleAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superescuela.asignacion",
                        verbose_name="Asignacion",
                    ),
                ),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superescuela.escuelassupervisadas",
                        verbose_name="Escuela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle_Escuela_Supervisada",
                "verbose_name_plural": "Detalles_Escuelas_Supervisadas",
                "db_table": "Detalle_Asignacion",
                "ordering": ["escuela"],
            },
        ),
        migrations.AddField(
            model_name="asignacion",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="superescuela.supervisor",
                verbose_name="Supervisor",
            ),
        ),
    ]
