# Generated by Django 5.1.1 on 2025-01-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="Total")),
            ],
            options={
                "verbose_name": "Asignacion",
                "verbose_name_plural": "Asignaciones",
                "db_table": "Asignacion",
                "ordering": ["supervisor"],
            },
        ),
        migrations.CreateModel(
            name="EscuelasSupervisadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("region", models.CharField(max_length=100, verbose_name="Regional")),
            ],
            options={
                "verbose_name": "Escuela_Supervisada",
                "verbose_name_plural": "Escuelas_Supervisadas",
                "db_table": "escuelas_supervisadas",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                ("cuil", models.CharField(max_length=11, verbose_name="CUIL")),
                ("apellido", models.CharField(max_length=255, verbose_name="Apellido")),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                (
                    "f_nac",
                    models.DateField(default="1900-01-01", verbose_name="Fecha_Nac"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=9,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "sit_revista",
                    models.CharField(
                        choices=[
                            ("Titular", "Titular"),
                            ("Interino", "Interino"),
                            ("Suplente", "Suplente"),
                        ],
                        max_length=100,
                        verbose_name="Sit_Revista",
                    ),
                ),
                (
                    "f_designacion",
                    models.DateField(
                        default="1900-01-01", verbose_name="Fecha_Designacion"
                    ),
                ),
                ("cuof", models.IntegerField(verbose_name="CUOF")),
                ("cuof_anexo", models.IntegerField(verbose_name="Anexo CUOF")),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("Primario", "Primario"),
                            ("Secundario", "Secundario"),
                            ("Superior", "Superior"),
                            ("Multinivel", "Multinivel"),
                        ],
                        max_length=25,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("Jóvenes y Adultos", "Jóvenes y Adultos"),
                            ("Artística", "Artística"),
                            ("Rural", "Rural"),
                            ("Técnica - Form. Prof.", "Técnica - Form. Prof."),
                            (
                                "Hospitalaria - Domiciliaria",
                                "Hospitalaria - Domiciliaria",
                            ),
                            ("Mutimodalidad", "Multimodalidad"),
                        ],
                        max_length=50,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Gestión Estatal", "Gestión Estatal"),
                            ("Gestión Social", "Gestión Social"),
                            ("Gestión Comunitaria", "Gestión Comunitaria"),
                            ("Gestión Privada", "Gestión Privada"),
                            ("Multigestión", "Multigestión"),
                        ],
                        max_length=50,
                        verbose_name="Sector",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Correo")),
                ("telefono", models.CharField(max_length=11, verbose_name="Teléfono")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("R.E. 1", "R.E. 1"),
                            ("R.E. 2", "R.E. 2"),
                            ("R.E. 3", "R.E. 3"),
                            ("R.E. 4-A", "R.E. 4-A"),
                            ("R.E. 4-B", "R.E. 4-B"),
                            ("R.E. 5", "R.E. 5"),
                            ("R.E. 6", "R.E. 6"),
                            ("R.E. 7", "R.E. 7"),
                            ("R.E. 8-A", "R.E. 8-A"),
                            ("R.E. 8-B", "R.E. 8-B"),
                            ("R.E. 9", "R.E. 9"),
                            ("R.E. 10-A", "R.E. 10-A"),
                            ("R.E. 10-B", "R.E. 10-B"),
                            ("R.E. 10-C", "R.E. 10-C"),
                            ("SUB. R.E. 1-A", "SUB. R.E. 1-A"),
                            ("SUB. R.E. 1-B", "SUB. R.E. 1-B"),
                            ("SUB. R.E. 2", "SUB. R.E. 2"),
                            ("SUB. R.E. 3", "SUB. R.E. 3"),
                            ("SUB. R.E. 5", "SUB. R.E. 5"),
                        ],
                        max_length=100,
                        verbose_name="Regional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor_Escuela",
                "verbose_name_plural": "Supervisores_Escuelas",
                "db_table": "supervisores_escuelas",
            },
        ),
        migrations.CreateModel(
            name="DetalleAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superescuela.asignacion",
                        verbose_name="Asignacion",
                    ),
                ),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superescuela.escuelassupervisadas",
                        verbose_name="Escuela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle_Escuela_Supervisada",
                "verbose_name_plural": "Detalles_Escuelas_Supervisadas",
                "db_table": "Detalle_Asignacion",
                "ordering": ["escuela"],
            },
        ),
        migrations.AddField(
            model_name="asignacion",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="superescuela.supervisor",
                verbose_name="Supervisor",
            ),
        ),
    ]
