# Generated by Django 5.1.1 on 2025-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superescuela", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisor",
            name="modalidad",
            field=models.CharField(
                choices=[
                    ("Común", "Común"),
                    ("Jóvenes y Adultos", "Jóvenes y Adultos"),
                    ("Artística", "Artística"),
                    ("Bilingüe Intercultural", "Bilingüe Intercultural"),
                    ("Educación Especial", "Educación Especial"),
                    ("Educación Física", "Educación Física"),
                    ("Servicios Complementarios", "Servicios Complementarios"),
                    ("Rural", "Rural"),
                    ("Técnica - Form. Prof.", "Técnica - Form. Prof."),
                    ("Hospitalaria - Domiciliaria", "Hospitalaria - Domiciliaria"),
                    ("Mutimodalidad", "Multimodalidad"),
                ],
                max_length=50,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primario", "Primario"),
                    ("Secundario", "Secundario"),
                    ("Superior", "Superior"),
                    ("Multinivel", "Multinivel"),
                ],
                max_length=25,
                verbose_name="Nivel",
            ),
        ),
    ]
