# Generated by Django 5.1.1 on 2024-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superescuela", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisor",
            name="region",
            field=models.CharField(
                choices=[
                    ("R.E. 1", "R.E. 1"),
                    ("R.E. 2", "R.E. 2"),
                    ("R.E. 3", "R.E. 3"),
                    ("R.E. 4-A", "R.E. 4-A"),
                    ("R.E. 4-B", "R.E. 4-B"),
                    ("R.E. 5", "R.E. 5"),
                    ("R.E. 6", "R.E. 6"),
                    ("R.E. 7", "R.E. 7"),
                    ("R.E. 8-A", "R.E. 8-A"),
                    ("R.E. 8-B", "R.E. 8-B"),
                    ("R.E. 9", "R.E. 9"),
                    ("R.E. 10-A", "R.E. 10-A"),
                    ("R.E. 10-B", "R.E. 10-B"),
                    ("R.E. 10-C", "R.E. 10-C"),
                    ("SUB. R.E. 1-A", "SUB. R.E. 1-A"),
                    ("SUB. R.E. 1-B", "SUB. R.E. 1-B"),
                    ("SUB. R.E. 2", "SUB. R.E. 2"),
                    ("SUB. R.E. 3", "SUB. R.E. 3"),
                    ("SUB. R.E. 5", "SUB. R.E. 5"),
                ],
                max_length=100,
                verbose_name="Regional",
            ),
        ),
    ]
