# Generated by Django 5.1.1 on 2025-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superescuela", "0002_alter_supervisor_modalidad_alter_supervisor_nivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="escuelassupervisadas",
            name="oferta",
            field=models.CharField(default=1, max_length=255, verbose_name="Oferta"),
            preserve_default=False,
        ),
    ]
