# Generated by Django 5.1.1 on 2025-02-12 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("superescuela", "0003_escuelassupervisadas_oferta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escuelassupervisadas",
            options={
                "managed": False,
                "verbose_name": "Escuela_Supervisada",
                "verbose_name_plural": "Escuelas_Supervisadas",
            },
        ),
    ]
