# Generated by Django 5.1.1 on 2025-02-12 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("superescuela", "0004_alter_escuelassupervisadas_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escuelassupervisadas",
            options={
                "verbose_name": "Escuela_Supervisada",
                "verbose_name_plural": "Escuelas_Supervisadas",
            },
        ),
    ]
