# Generated by Django 5.2.8 on 2026-05-21 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nomencladorceic",
            options={
                "managed": False,
                "ordering": ["descripcion"],
                "verbose_name": "nomenclador ceic",
                "verbose_name_plural": "nomencladores ceic",
            },
        ),
    ]
