# Generated by Django 5.2.8 on 2026-05-29 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0006_merge_branches"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tipoos",
            table="tipo_obra_social",
        ),
    ]
