# Generated by Django 5.2.8 on 2026-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhpersonas",
            "0008_tipofunciones_registroactividades_f_desde_funciones_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDesigFunc",
            fields=[
                ("c_desigfunc", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "desigfunc_descripcion",
                    models.CharField(max_length=100, unique=True),
                ),
                ("ayuda", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "desigfunc_tipo_bnh",
                "managed": True,
            },
        ),
    ]
