# Generated by Django 5.2.8 on 2026-06-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0010_grado_anio_secciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroactividades",
            name="grado_anio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bnhpersonas.grado_anio"
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="secciones",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bnhpersonas.secciones"
            ),
        ),
    ]
