# Generated by Django 5.2.8 on 2026-09-02 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnhpersonas', '0018_ministerial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horarioactividad',
            constraint=models.CheckConstraint(condition=models.Q(('hora_hasta__gt', models.F('hora_desde'))), name='bnh_horario_orden'),
        ),
        migrations.AddConstraint(
            model_name='registroactividades',
            constraint=models.CheckConstraint(condition=models.Q(('f_hasta__isnull', True), ('f_hasta__gte', models.F('f_desde')), _connector='OR'), name='bnh_cargo_fechas'),
        ),
        migrations.AddConstraint(
            model_name='registroactividades',
            constraint=models.CheckConstraint(condition=models.Q(('f_hasta_funciones__isnull', True), ('f_hasta_funciones__gte', models.F('f_desde_funciones')), _connector='OR'), name='bnh_funcion_fechas'),
        ),
    ]
