# Generated by Django 5.2.8 on 2026-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0021_espaciocurricularnombre_modalidadtipo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitulacionSuperior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_titulacion", models.IntegerField()),
                ("c_nivel_servicio", models.SmallIntegerField()),
                ("c_modalidad1", models.SmallIntegerField()),
                ("descripcion", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Titulacion Superior",
                "verbose_name_plural": "Titulaciones Superior",
                "db_table": "titulacion",
            },
        ),
    ]
