# Generated by Django 4.2.5 on 2024-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VCapaUnicaOfertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.BigIntegerField(verbose_name="cueanexo")),
                ("long", models.FloatField(verbose_name="long")),
                ("lat", models.FloatField(verbose_name="lat")),
                ("nom_est", models.CharField(max_length=255, verbose_name="nom_est")),
                ("acronimo", models.CharField(verbose_name="acronimo")),
                ("ambito", models.CharField(verbose_name="ambito")),
                ("sector", models.CharField(verbose_name="sector")),
                ("region_loc", models.CharField(verbose_name="region_loc")),
                ("calle", models.CharField(verbose_name="calle")),
                ("numero", models.CharField(verbose_name="numero")),
                ("localidad", models.CharField(verbose_name="localidad")),
                ("departamento", models.CharField(verbose_name="departamento")),
            ],
            options={
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
    ]
