# Generated by Django 4.2.5 on 2024-04-13 21:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VCapaUnicaOfertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("long", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("nom_est", models.CharField(blank=True, null=True)),
                ("padron_cueanexo", models.IntegerField(blank=True, null=True)),
                ("acronimo", models.TextField(blank=True, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.CharField(blank=True, null=True)),
                ("ambito", models.CharField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, null=True)),
                ("region_loc", models.CharField(blank=True, null=True)),
                ("ref_loc", models.CharField(blank=True, null=True)),
                ("calle", models.CharField(blank=True, null=True)),
                ("numero", models.CharField(blank=True, null=True)),
                ("localidad", models.CharField(blank=True, null=True)),
                ("departamento", models.CharField(blank=True, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
    ]
