# Generated by Django 4.2.5 on 2024-08-26 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vcapaunicaofertas",
            options={
                "managed": False,
                "verbose_name": "VCapa_unica_oferta",
                "verbose_name_plural": "VCapas_unicas_ofertas",
            },
        ),
    ]
