# Generated by Django 4.2.5 on 2024-08-26 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0002_alter_vcapaunicaofertas_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vcapaunicaofertas",
            options={"managed": False},
        ),
    ]
