# Generated by Django 4.2.5 on 2024-08-28 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0003_alter_vcapaunicaofertas_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VCapaUnicaOfertas",
        ),
    ]
