# Generated by Django 4.2.5 on 2024-09-20 02:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mapas", "0004_delete_vcapaunicaofertas"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalesGeometria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("region_pad", models.CharField(max_length=255)),
                ("titulo", models.TextField()),
            ],
            options={
                "db_table": "public.c_regiones_educativas_2024_",
                "managed": False,
            },
        ),
    ]
