# Generated by Django 4.2.5 on 2024-09-20 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0005_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="regionalesgeometria",
            table="c_regiones_educativas_2024_",
        ),
    ]
