# Generated by Django 4.2.5 on 2024-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0006_alter_regionalesgeometria_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalidadesRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg", models.CharField(max_length=50)),
                ("nom_dir", models.CharField(max_length=255)),
                ("tel_dir", models.CharField(max_length=25)),
                ("email_dir", models.CharField(max_length=255)),
                ("loc_reg", models.CharField(max_length=255)),
                ("dep_reg", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "localidadesregion",
                "managed": False,
            },
        ),
    ]
