# Generated by Django 5.2.8 on 2026-03-20 03:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0008_interaccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapaEscuelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.BigIntegerField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("nom_est", models.CharField(max_length=200)),
                ("oferta", models.CharField(max_length=100)),
                ("ambito", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("region_loc", models.CharField(max_length=20)),
                ("calle", models.CharField(max_length=150)),
                ("numero", models.CharField(max_length=20)),
                ("localidad", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
    ]
