# Generated by Django 5.2.8 on 2026-03-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0009_capaescuelas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapaUnicaOfertas",
            fields=[
                (
                    "cueanexo",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nom_est", models.CharField(max_length=255)),
                ("oferta", models.CharField(max_length=255)),
                ("ambito", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("region_loc", models.CharField(max_length=100)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("localidad", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
            options={
                "verbose_name": "Escuela_colectivo",
                "verbose_name_plural": "Escuelas_colectivos",
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Colectivoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("direccion", models.TextField()),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("cod", models.CharField(max_length=10)),
                ("distan_paradas", models.IntegerField(blank=True, null=True)),
                ("lineas", models.TextField()),
            ],
            options={
                "db_table": "colectivoss",
                "managed": False,
            },
        ),
    ]
