# Generated by Django 5.2.8 on 2026-03-23 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapas", "0010_capaunicaofertas_colectivoss"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="capaescuelas",
            table="v_capa_unica_ofertas_ant",
        ),
    ]
