# Generated by Django 5.2.8 on 2026-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("level", models.CharField(max_length=50)),
                ("unit", models.CharField(default="%", max_length=20)),
                ("formula", models.JSONField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_code", models.CharField(max_length=50)),
                ("cueanexo", models.CharField(max_length=50)),
                ("ra", models.CharField(blank=True, max_length=50, null=True)),
                ("orientacion", models.CharField(blank=True, max_length=50, null=True)),
                ("grado", models.CharField(blank=True, max_length=20, null=True)),
                ("period", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                ("metadata", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
