# Generated by Django 5.2.8 on 2026-09-15 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0022_titulacionsuperior"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="titulacionsuperior",
            table="titulacion_superior",
        ),
    ]
