# Generated by Django 5.1.1 on 2025-03-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operachaco", "0002_pregunta"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOpcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("UNICA", "Opción Única"),
                            ("MULTIPLE", "Opción Múltiple"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo Opcion",
                "verbose_name_plural": "Tipos Opciones",
                "db_table": "Tipo_Opcion",
            },
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="operachaco.pregunta",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="operachaco.tipoopcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opcion",
                "verbose_name_plural": "Opciones",
                "db_table": "Opcion",
            },
        ),
    ]
