# Generated by Django 5.1.1 on 2025-03-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operachaco", "0003_tipoopcion_opcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcion",
            name="puntaje",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=4, verbose_name="Puntaje"
            ),
            preserve_default=False,
        ),
    ]
