# Generated by Django 5.1.1 on 2025-03-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operachaco", "0005_alter_opcion_options_opcion_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumnosSecundaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examenes",
                "db_table": "Examen",
            },
        ),
        migrations.CreateModel(
            name="ExamenSecundaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni_alumno", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellido",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Puntaje Total",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examenes",
                        to="operachaco.area",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen_secundaria",
                "verbose_name_plural": "Examenes_secundaria",
                "db_table": "Examen_secundaria",
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="operachaco.examensecundaria",
                    ),
                ),
                (
                    "opciones",
                    models.ManyToManyField(
                        related_name="respuestas", to="operachaco.opcion"
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="operachaco.pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "db_table": "Respuesta",
            },
        ),
    ]
