# Generated by Django 5.1.1 on 2025-03-27 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operachaco", "0006_alumnossecundaria_examensecundaria_respuesta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumnossecundaria",
            options={
                "verbose_name": "Alumno_Secundaria",
                "verbose_name_plural": "Alumnos_Secundaria",
            },
        ),
        migrations.AlterModelTable(
            name="alumnossecundaria",
            table="Alumno_Secundaria",
        ),
    ]
