# Generated by Django 4.2.5 on 2024-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PadronActualizar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_establecimiento", models.IntegerField(blank=True, null=True)),
                ("id_localizacion", models.IntegerField(blank=True, null=True)),
                ("cueanexo", models.TextField(blank=True, null=True)),
                ("nom_est", models.CharField(blank=True, max_length=255, null=True)),
                ("nro_est", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "anio_creac_establec",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fecha_creac_establec",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("udt", models.CharField(blank=True, max_length=255, null=True)),
                ("cui", models.CharField(blank=True, max_length=255, null=True)),
                ("cua", models.CharField(blank=True, max_length=255, null=True)),
                ("cuof", models.CharField(blank=True, max_length=255, null=True)),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
                ("ambito", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_loc", models.CharField(blank=True, max_length=255, null=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                ("localidad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cod_postal", models.CharField(blank=True, max_length=255, null=True)),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                ("estado_est", models.CharField(blank=True, max_length=255, null=True)),
                ("estado_loc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telefono_cod_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telefono_nro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "per_funcionamiento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_loc", models.CharField(blank=True, max_length=255, null=True)),
                ("sitio_web", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cooperadora",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sede", models.BooleanField(blank=True, null=True)),
                (
                    "permanencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sede_adm", models.BooleanField(blank=True, null=True)),
                (
                    "resploc_apellido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resploc_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resploc_telefono",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resploc_doc", models.IntegerField(blank=True, null=True)),
                (
                    "resploc_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resploc_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "resploc_cuitcuil",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("arancel", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "padron_actualizar",
                "managed": False,
            },
        ),
    ]
