# Generated by Django 5.2.8 on 2026-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0002_alter_nomencladorceic_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titulosespacios",
            options={"managed": False, "ordering": ["descrip_titulo"]},
        ),
    ]
