# Generated by Django 5.2.8 on 2026-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhpersonas",
            "0004_estadosciviles_nivelformacion_relacionparentesco_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documentotipo",
            table="documento_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="estadosciviles",
            table="estado_civil_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="localidades",
            table="localidad_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="nacionalidad",
            table="nacionalidad_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="pais",
            table="pais_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="provincias",
            table="provincia_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="sexo",
            table="sexo_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="tipocomunidadoriginaria",
            table="tipo_comunidad_originaria_bnh",
        ),
        migrations.AlterModelTable(
            name="tipodiscapacidad",
            table="tipo_discapacidad_bnh",
        ),
        migrations.AlterModelTable(
            name="tipoemail",
            table="tipo_email_bnh",
        ),
        migrations.AlterModelTable(
            name="tipolenguaoriginaria",
            table="tipo_lengua_originaria_bnh",
        ),
        migrations.AlterModelTable(
            name="tipoplanessociales",
            table="tipo_planes_sociales_bnh",
        ),
    ]
