# Generated by Django 5.2.8 on 2026-04-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supervisa2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscuelaCapaOfertas",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9)),
                ("nom_est", models.CharField(max_length=255)),
                ("region_loc", models.CharField(max_length=100)),
                ("oferta", models.CharField(max_length=150)),
                ("localidad", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=255)),
                ("sector", models.CharField(max_length=150)),
                ("ambito", models.CharField(max_length=150)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
            options={
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AsignacionSupervisorEscuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9)),
                ("nom_est", models.CharField(max_length=255)),
                ("region_loc", models.CharField(max_length=100)),
                ("oferta", models.CharField(blank=True, max_length=150, null=True)),
                ("localidad", models.CharField(max_length=255)),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="supervisa2.supervisor2",
                    ),
                ),
            ],
            options={
                "db_table": "asignacion_supervisores",
                "indexes": [
                    models.Index(
                        fields=["supervisor", "activo"],
                        name="asignacion__supervi_1d73d5_idx",
                    ),
                    models.Index(
                        fields=["cueanexo", "activo"],
                        name="asignacion__cueanex_bf3da0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supervisor", "cueanexo", "oferta"),
                        name="uq_supervisor_escuela_oferta",
                    )
                ],
            },
        ),
    ]
