# Generated by Django 5.2.8 on 2026-04-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asignaciones", "0001_initial"),
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionsupervisorescuela",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EN_REVISION", "En revisión"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(fields=["estado"], name="asignacion__estado_2469e6_idx"),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(
                fields=["supervisor", "estado"], name="asignacion__supervi_c910fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(
                fields=["estado", "activo"], name="asignacion__estado_67fc44_idx"
            ),
        ),
    ]
