# Generated by Django 5.2.8 on 2026-04-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asignaciones", "0002_asignacionsupervisorescuela_estado_and_more"),
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asignacionsupervisorescuela",
            name="asignacion__supervi_1d73d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignacionsupervisorescuela",
            name="asignacion__cueanex_bf3da0_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignacionsupervisorescuela",
            name="asignacion__estado_2469e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignacionsupervisorescuela",
            name="asignacion__supervi_c910fc_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignacionsupervisorescuela",
            name="asignacion__estado_67fc44_idx",
        ),
        migrations.AlterField(
            model_name="asignacionsupervisorescuela",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADO", "Enviado"),
                    ("REVISION_REGIONAL", "En revisión regional"),
                    ("OBSERVADO", "Observado"),
                    ("APROBADO", "Aprobado"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asignacionsupervisorescuela",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="supervisa2.supervisor2"
            ),
        ),
    ]
