# Generated by Django 5.2.8 on 2026-04-09 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "asignaciones",
            "0003_remove_asignacionsupervisorescuela_asignacion__supervi_1d73d5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionsupervisorescuela",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
