# Generated by Django 5.2.8 on 2026-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asignaciones", "0004_asignacionsupervisorescuela_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionsupervisorescuela",
            name="observacion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
