# Generated by Django 5.2.8 on 2026-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asignaciones", "0006_auditlog"),
        ("supervisa2", "0004_alter_supervisor2_estado_validacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignacionsupervisorescuela",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADO", "Enviado"),
                    ("OBSERVADO", "Observado"),
                    ("APROBADO", "Aprobado"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(fields=["estado"], name="asignacion__estado_2469e6_idx"),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(
                fields=["region_loc"], name="asignacion__region__0a9608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionsupervisorescuela",
            index=models.Index(
                fields=["created_at"], name="asignacion__created_7e32b9_idx"
            ),
        ),
    ]
