# Generated by Django 5.2.8 on 2026-05-14 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodAreasTelefonos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cod_prov", models.IntegerField()),
                ("provincia", models.CharField(max_length=100)),
                ("localidad", models.CharField(max_length=150)),
                ("codigo", models.IntegerField()),
            ],
            options={
                "verbose_name": "Codigo Area",
                "verbose_name_plural": "Codigos Areas",
                "db_table": "cod_areas",
                "ordering": ["codigo", "localidad"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentoTipo",
            fields=[
                ("c_tipo_doc", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_doc", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Documento",
                "verbose_name_plural": "Tipos Documentos",
                "db_table": "documento_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstadosCiviles",
            fields=[
                (
                    "c_estado_civil",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_estado_civil", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Estado Civil",
                "verbose_name_plural": "Estados Civiles",
                "db_table": "estado_civil_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Localidades",
            fields=[
                ("c_localidad", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_localidad", models.CharField(max_length=150)),
                ("c_departamento", models.IntegerField()),
                ("descrip_departamento", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "db_table": "localidad_tipo",
                "ordering": ["descrip_localidad"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Modalidades",
            fields=[
                ("c_modalidad", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_modalidad", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "modalidad",
                "verbose_name_plural": "modalidades",
                "db_table": "modalidades_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nacionalidad",
            fields=[
                (
                    "c_nacionalidad",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_nac", models.CharField(max_length=100)),
                ("c_pais", models.IntegerField()),
            ],
            options={
                "verbose_name": "Nacionalidad",
                "verbose_name_plural": "Nacionalidades",
                "db_table": "nacionalidad_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NivelServicio",
            fields=[
                ("c_nivel", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_nivel", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "oferta",
                "verbose_name_plural": "ofertas",
                "db_table": "nivel_servicio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NomencladorCeic",
            fields=[
                ("c_ceic", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=150)),
                ("estado", models.CharField(max_length=25)),
                ("c_niv", models.IntegerField()),
                ("t_nivel", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "nomenclador ceic",
                "verbose_name_plural": "nomencladores ceic",
                "db_table": "nomenclador_ceic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("c_pais", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_pais", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "pais",
                "verbose_name_plural": "paices",
                "db_table": "pais_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Provincias",
            fields=[
                ("c_provincia", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_provincia", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "provincia",
                "verbose_name_plural": "provincias",
                "db_table": "provincia_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RelacionParentesco",
            fields=[
                (
                    "c_relacion_parentesco",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_relacion_parentesco", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Relacion Parentesco",
                "verbose_name_plural": "Relaciones Parentesco",
                "db_table": "relacion_parentesco_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                ("c_sexo", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_sexo", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "sexo",
                "verbose_name_plural": "sexos",
                "db_table": "sexo_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoComunidadOriginaria",
            fields=[
                (
                    "c_tipo_comunidad_originaria",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_comunidad_originaria", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Comunidad Originaria",
                "verbose_name_plural": "Tipos Comunidad Originaria",
                "db_table": "tipo_comunidad_originaria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDiscapacidad",
            fields=[
                (
                    "c_tipo_discapacidad",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_discapacidad", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Discapacidad",
                "verbose_name_plural": "Tipos Discapacidad",
                "db_table": "tipo_discapacidad",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDocenteIntegrador",
            fields=[
                (
                    "c_tipo_docente_integrador",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_docente_integrador", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Docente Integrador",
                "verbose_name_plural": "Tipos Docente Integrador",
                "db_table": "tipo_docente_integrador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEmail",
            fields=[
                (
                    "c_tipo_email",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_email", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Email",
                "verbose_name_plural": "Tipos Email",
                "db_table": "tipo_email",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoLenguaOriginaria",
            fields=[
                (
                    "c_tipo_lengua_originaria",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_lengua_originaria", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Lengua Originaria",
                "verbose_name_plural": "Tipos Lengua Originaria",
                "db_table": "tipo_lengua_originaria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoPlanesSociales",
            fields=[
                (
                    "c_tipo_planes_sociales",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_planes_sociales", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Plan Social",
                "verbose_name_plural": "Tipos Planes Sociales",
                "db_table": "tipo_planes_sociales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTelefono",
            fields=[
                (
                    "c_tipo_telefono",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_telefono", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Telefono",
                "verbose_name_plural": "Tipos Telefonos",
                "db_table": "tipo_telefono",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CondicionActividad",
            fields=[
                (
                    "cod_condicion",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_condicion", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "condicion_actividad",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SituacionServicio",
            fields=[
                ("cod_sitrev", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_sitrev", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "situacion_revista",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Personas",
            fields=[
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cuil",
                    models.CharField(
                        blank=True, db_index=True, max_length=11, null=True
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True, db_index=True, max_length=8, null=True
                    ),
                ),
                ("apellido", models.CharField(db_index=True, max_length=150)),
                ("nombre", models.CharField(db_index=True, max_length=150)),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6,8}$",
                                message="Ingrese solo el número local (6 a 8 dígitos, sin código de área)",
                            )
                        ],
                    ),
                ),
                (
                    "telefono_normalizado",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                ("whatsapp", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("PASIVO", "Pasivo")],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                (
                    "codigo_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.codareastelefonos",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.localidades",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.provincias",
                    ),
                ),
                (
                    "sexo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.sexo",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personas",
            },
        ),
        migrations.CreateModel(
            name="RegistroActividades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("DOCENTE", "Docente"), ("NO DOCENTE", "No Docente")],
                        max_length=10,
                    ),
                ),
                (
                    "designacion",
                    models.CharField(
                        choices=[
                            ("CARGO", "CARGO"),
                            ("HORAS CATEDRAS", "HORAS CATEDRAS"),
                        ],
                        default="CARGO",
                        max_length=20,
                    ),
                ),
                ("f_desde", models.DateField()),
                ("f_hasta", models.DateField()),
                ("carga_horaria", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        max_length=10,
                    ),
                ),
                (
                    "ceic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.nomencladorceic",
                    ),
                ),
                (
                    "cond_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.condicionactividad",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.modalidades",
                    ),
                ),
                (
                    "niveles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.nivelservicio",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="bnhpersonas.personas",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sit_revista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bnhpersonas.situacionservicio",
                    ),
                ),
            ],
            options={
                "db_table": "registro_actividades",
            },
        ),
        migrations.AddIndex(
            model_name="personas",
            index=models.Index(fields=["dni"], name="personas_dni_9bfd07_idx"),
        ),
        migrations.AddIndex(
            model_name="personas",
            index=models.Index(fields=["cuil"], name="personas_cuil_ef5d98_idx"),
        ),
        migrations.AddIndex(
            model_name="personas",
            index=models.Index(
                fields=["telefono_normalizado"], name="personas_telefon_948765_idx"
            ),
        ),
    ]
