# Generated by Django 5.2.8 on 2026-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0003_alter_codareastelefonos_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroactividades",
            name="designacion",
            field=models.CharField(
                choices=[("CARGO", "CARGO"), ("HORAS CATEDRAS", "HORAS CATEDRAS")],
                default="CARGO",
                max_length=20,
            ),
        ),
    ]
