# Generated by Django 5.2.8 on 2026-05-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0003_alter_titulosespacios_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadosCiviles",
            fields=[
                (
                    "c_estado_civil",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_estado_civil", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Estado Civil",
                "verbose_name_plural": "Estados Civiles",
                "db_table": "estado_civil_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NivelFormacion",
            fields=[
                (
                    "c_nivel_formacion",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_nivel_formacion", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Nivel Formación",
                "verbose_name_plural": "Niveles Formación",
                "db_table": "nivel_formacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RelacionParentesco",
            fields=[
                (
                    "c_relacion_parentesco",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_relacion_parentesco", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Relacion Parentesco",
                "verbose_name_plural": "Relaciones Parentesco",
                "db_table": "relacion_parentesco_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoComunidadOriginaria",
            fields=[
                (
                    "c_tipo_comunidad_originaria",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_comunidad_originaria", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Comunidad Originaria",
                "verbose_name_plural": "Tipos Comunidad Originaria",
                "db_table": "tipo_comunidad_originaria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDiscapacidad",
            fields=[
                (
                    "c_tipo_discapacidad",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_discapacidad", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Discapacidad",
                "verbose_name_plural": "Tipos Discapacidad",
                "db_table": "tipo_discapacidad",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoDocenteIntegrador",
            fields=[
                (
                    "c_tipo_docente_integrador",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_docente_integrador", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Docente Integrador",
                "verbose_name_plural": "Tipos Docente Integrador",
                "db_table": "tipo_docente_integrador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEmail",
            fields=[
                (
                    "c_tipo_email",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_email", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Email",
                "verbose_name_plural": "Tipos Email",
                "db_table": "tipo_email",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoLenguaOriginaria",
            fields=[
                (
                    "c_tipo_lengua_originaria",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_lengua_originaria", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Lengua Originaria",
                "verbose_name_plural": "Tipos Lengua Originaria",
                "db_table": "tipo_lengua_originaria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoOS",
            fields=[
                ("c_tipo_os", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_os", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo OS",
                "verbose_name_plural": "Tipos OS",
                "db_table": "tipo_obra_social",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoPlanesSociales",
            fields=[
                (
                    "c_tipo_planes_sociales",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_planes_sociales", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Plan Social",
                "verbose_name_plural": "Tipos Planes Sociales",
                "db_table": "tipo_planes_sociales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTelefono",
            fields=[
                (
                    "c_tipo_telefono",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_tipo_telefono", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Telefono",
                "verbose_name_plural": "Tipos Telefonos",
                "db_table": "tipo_telefono",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="espacios",
            field=models.ForeignKey(
                db_column="espacios",
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.titulosespacios",
            ),
        ),
    ]
