# Generated by Django 5.2.8 on 2026-05-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0003_alter_titulosespacios_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroactividades",
            name="espacios",
            field=models.ForeignKey(
                db_column="espacios",
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.titulosespacios",
            ),
        ),
    ]
