# Generated by Django 5.2.8 on 2026-05-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0004_registroactividades_designacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="personas",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("PASIVO", "Pasivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="usuario_creacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="usuario_modificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="cueanexo",
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="usuario_creacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="usuario_modificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
