# Generated by Django 5.2.8 on 2026-05-26 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhpersonas",
            "0005_alter_documentotipo_table_alter_estadosciviles_table_and_more",
        ),
        ("bnhpersonas", "0005_tipoos_c_os_state"),
    ]

    operations = []
