# Generated by Django 5.2.8 on 2026-06-04 11:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0007_alter_tipoos_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoFunciones",
            fields=[
                ("c_funciones", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "funciones_descripcion",
                    models.CharField(max_length=100, unique=True),
                ),
            ],
            options={
                "db_table": "funciones_tipo_bnh",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="registroactividades",
            name="f_desde_funciones",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="registroactividades",
            name="f_hasta_funciones",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="espacios",
            field=models.ForeignKey(
                db_column="descrip_titulo",
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.titulosespacios",
                to_field="descrip_titulo",
            ),
        ),
        migrations.AddField(
            model_name="registroactividades",
            name="funciones",
            field=models.ForeignKey(
                db_column="c_funciones",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.tipofunciones",
            ),
            preserve_default=False,
        ),
    ]
