# Generated by Django 5.2.8 on 2026-06-25 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0012_horarioactividad"),
    ]

    operations = [
        migrations.AddField(
            model_name="horarioactividad",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="registroactividades",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
