# Generated by Django 5.2.8 on 2026-07-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0016_registroactividades_t_designacion_modalidadnivel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModalidadNivelCeic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rango_ceic",
                    models.CharField(help_text="Ej.: 1-21,220,221", max_length=500),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnhpersonas.modalidades",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnhpersonas.nivelservicio",
                    ),
                ),
            ],
            options={
                "db_table": "modalidad_nivel_ceic",
                "unique_together": {("modalidad", "nivel")},
            },
        ),
    ]
