# Generated by Django 5.2.8 on 2026-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0023_alter_titulacionsuperior_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulacionsuperior",
            name="descripcion",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
