# Generated by Django 5.2.8 on 2026-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0026_circuito_curricular_independiente"),
    ]

    operations = [
        migrations.CreateModel(
            name="CondicionActividadNombre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_nomen", models.CharField(max_length=10)),
                ("encuadre", models.CharField(max_length=10)),
                ("sit_rev", models.SmallIntegerField()),
                ("c_homo_sit_rev", models.SmallIntegerField()),
                ("c_homo_c_act", models.SmallIntegerField()),
                ("denominacion", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Condicion Actividad Nombre",
                "verbose_name_plural": "Condiciones Actividad Nombres",
                "db_table": "condicion_actividad_nombre",
            },
        ),
        migrations.AlterField(
            model_name="registroactividades",
            name="turno",
            field=models.CharField(
                choices=[
                    ("MAÑANA", "MAÑANA"),
                    ("MAÑANA EXTENDIDA", "MAÑANA EXTENDIDA"),
                    ("TARDE", "TARDE"),
                    ("TARDE EXTENDIDA", "TARDE EXTENDIDA"),
                    ("NOCHE", "NOCHE"),
                    ("VESPERTINO", "VESPERTINO"),
                    ("DOBLE", "DOBLE"),
                    ("DOBLE EXTENDIDA", "DOBLE EXTENDIDA"),
                ],
                default="MAÑANA",
                max_length=20,
            ),
        ),
    ]
