# Generated by Django 5.2.8 on 2026-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0027_condicionactividadnombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condicionactividadnombre",
            name="encuadre",
            field=models.CharField(max_length=50),
        ),
    ]
