# Generated by Django 5.2.8 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaAfectada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Área afectada",
                "verbose_name_plural": "Áreas afectadas",
                "db_table": "sirtee_cat_area_afectada",
            },
        ),
        migrations.CreateModel(
            name="Criticidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("color", models.CharField(default="secondary", max_length=20)),
                ("nivel", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Criticidad",
                "verbose_name_plural": "Criticidades",
                "db_table": "sirtee_cat_criticidad",
                "ordering": ["-nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoHallazgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("color", models.CharField(default="secondary", max_length=20)),
                ("cerrado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Estado del hallazgo",
                "verbose_name_plural": "Estados del hallazgo",
                "db_table": "sirtee_cat_estado_hallazgo",
            },
        ),
        migrations.CreateModel(
            name="EstadoIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("color", models.CharField(default="secondary", max_length=20)),
                ("finaliza", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Estado de intervención",
                "verbose_name_plural": "Estados de intervención",
                "db_table": "sirtee_cat_estado_intervencion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="FuenteFinanciamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fuente de financiamiento",
                "verbose_name_plural": "Fuentes de financiamiento",
                "db_table": "sirtee_cat_fuente_financiamiento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="OrganismoResponsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Organismo responsable",
                "verbose_name_plural": "Organismos responsables",
                "db_table": "sirtee_cat_organismo_responsable",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Prioridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("nivel", models.PositiveSmallIntegerField(default=1)),
                ("color", models.CharField(default="secondary", max_length=20)),
            ],
            options={
                "verbose_name": "Prioridad",
                "verbose_name_plural": "Prioridades",
                "db_table": "sirtee_cat_prioridad",
                "ordering": ["-nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Riesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Riesgo",
                "verbose_name_plural": "Riesgos",
                "db_table": "sirtee_cat_riesgo",
            },
        ),
        migrations.CreateModel(
            name="SistemaConstructivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sistema constructivo",
                "verbose_name_plural": "Sistemas constructivos",
                "db_table": "sirtee_cat_sistema_constructivo",
            },
        ),
        migrations.CreateModel(
            name="TipoHallazgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de hallazgo",
                "verbose_name_plural": "Tipos de hallazgo",
                "db_table": "sirtee_cat_tipo_hallazgo",
            },
        ),
        migrations.CreateModel(
            name="TipoIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de intervención",
                "verbose_name_plural": "Tipos de intervención",
                "db_table": "sirtee_cat_tipo_intervencion",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
