# Generated by Django 5.2.8 on 2026-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PadronRolUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Rol de usuario",
                "verbose_name_plural": "Roles de usuario",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PadronUsuarioPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario para Padrón Interno",
                "verbose_name_plural": "Perfiles de usuario para Padrón Interno",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
    ]
