# Generated by Django 5.2.8 on 2026-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("padroninterno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechaActualizacionPadronInterno",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(verbose_name="Fecha de Actualización")),
            ],
            options={
                "verbose_name": "Fecha de Actualización Padrón Interno",
                "verbose_name_plural": "Fechas de Actualización Padrón Interno",
                "db_table": '"indicadores"."padroninterno_fecha_actualizacion"',
                "managed": False,
            },
        ),
    ]
