# Generated by Django 5.2.8 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0002_nivelformacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOS",
            fields=[
                ("c_tipo_os", models.IntegerField(primary_key=True, serialize=False)),
                ("descrip_os", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo OS",
                "verbose_name_plural": "Tipos OS",
                "db_table": "tipo_obra_social",
                "managed": False,
            },
        ),
    ]
