# Generated by Django 5.2.8 on 2026-06-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhpersonas",
            "0014_remove_horarioactividad_actividad_actividadsede_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='f_nacimiento',
            field=models.DateField(
                default='2000-01-01'
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="horarioactividad",
            unique_together={("actividad_sede", "dia", "hora_desde", "hora_hasta")},
        ),
    ]
