# Generated by Django 5.2.8 on 2026-07-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0015_personas_f_nacimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroactividades",
            name="t_designacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.tipodesigfunc",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ModalidadNivel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnhpersonas.modalidades",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnhpersonas.nivelservicio",
                    ),
                ),
            ],
            options={
                "db_table": "modalidad_nivel",
                "unique_together": {("modalidad", "nivel")},
            },
        ),
    ]
