# Generated by Django 5.2.8 on 2026-09-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_existing_data(apps, schema_editor):
    # Copia local e inmutable: la migración no depende del código de dominio futuro.
    import re
    from collections import defaultdict
    from django.db.models import F
    alias = schema_editor.connection.alias
    Person = apps.get_model("bnhpersonas", "Personas")
    Activity = apps.get_model("bnhpersonas", "RegistroActividades")
    Schedule = apps.get_model("bnhpersonas", "HorarioActividad")
    seen = defaultdict(list)
    malformed = []
    for pk, cuil in Person.objects.using(alias).values_list("pk", "cuil").iterator():
        if cuil:
            canonical = re.sub(r"[^0-9]", "", cuil)
            seen[canonical].append(pk)
            if canonical != cuil or len(canonical) != 11:
                malformed.append(pk)
    duplicate = any(len(ids) > 1 for ids in seen.values())
    invalid = (Activity.objects.using(alias).filter(carga_horaria__lte=0).exists()
        or Activity.objects.using(alias).filter(f_hasta__lt=F("f_desde")).exists()
        or Activity.objects.using(alias).filter(f_hasta_funciones__lt=F("f_desde_funciones")).exists()
        or Schedule.objects.using(alias).filter(hora_hasta__lte=F("hora_desde")).exists())
    if duplicate or malformed or invalid:
        raise RuntimeError("Datos incompatibles con las nuevas restricciones. Ejecute bnh_preflight y regularice los registros antes de migrar.")


class Migration(migrations.Migration):

    dependencies = [
        ('bnhpersonas', '0017_modalidadnivelceic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_existing_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AccesoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(help_text='Valor exacto de region_loc en el padrón.', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entidad', models.CharField(max_length=40)),
                ('objeto_id', models.PositiveBigIntegerField()),
                ('cueanexo', models.CharField(blank=True, db_index=True, max_length=9)),
                ('accion', models.CharField(max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('antes', models.JSONField(default=dict)),
                ('despues', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='archivada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='personas',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registroactividades',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='registroactividades',
            name='validacion',
            field=models.CharField(choices=[('BORRADOR', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado')], default='BORRADOR', max_length=12),
        ),
        migrations.AddField(
            model_name='registroactividades',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='espacios',
            field=models.ForeignKey(blank=True, db_column='descrip_titulo', null=True, on_delete=django.db.models.deletion.PROTECT, to='bnhpersonas.titulosespacios', to_field='descrip_titulo'),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='f_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='f_hasta_funciones',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='grado_anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnhpersonas.grado_anio'),
        ),
        migrations.AlterField(
            model_name='registroactividades',
            name='secciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnhpersonas.secciones'),
        ),
        migrations.AddIndex(
            model_name='registroactividades',
            index=models.Index(fields=['cueanexo', 'eliminado', 'estado'], name='bnh_cue_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='personas',
            constraint=models.UniqueConstraint(condition=models.Q(('cuil__isnull', False), models.Q(('cuil', ''), _negated=True)), fields=('cuil',), name='bnh_persona_cuil_unico'),
        ),
        migrations.AddConstraint(
            model_name='registroactividades',
            constraint=models.CheckConstraint(condition=models.Q(('carga_horaria__gt', 0)), name='bnh_carga_positiva'),
        ),
        migrations.AddField(
            model_name='accesoregional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoregional',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoregional',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesoregional',
            constraint=models.UniqueConstraint(fields=('usuario', 'region'), name='bnh_usuario_region_unico'),
        ),
    ]
