# Generated by Django 5.2.8 on 2026-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CefPadronOferta",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(blank=True, max_length=9, null=True)),
                ("nom_est", models.TextField(blank=True, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("acronimo", models.CharField(blank=True, max_length=50, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.TextField(blank=True, null=True)),
                ("ambito", models.TextField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("region_loc", models.TextField(blank=True, null=True)),
                ("ref_loc", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("numero", models.TextField(blank=True, null=True)),
                ("localidad", models.TextField(blank=True, null=True)),
                ("departamento", models.TextField(blank=True, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("resploc_cuitcuil", models.TextField(blank=True, null=True)),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Oferta CEF desde Padrón",
                "verbose_name_plural": "Ofertas CEF desde Padrón",
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefRolUsuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Rol de usuario CEF",
                "verbose_name_plural": "Roles de usuario CEF",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefUsuarioPerfil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Perfil de usuario CEF",
                "verbose_name_plural": "Perfiles de usuario CEF",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
    ]
