# Generated by Django 5.2.14 on 2026-06-17 04:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefPadronOferta",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(blank=True, max_length=9, null=True)),
                ("nom_est", models.TextField(blank=True, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("acronimo", models.CharField(blank=True, max_length=50, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.TextField(blank=True, null=True)),
                ("ambito", models.TextField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("region_loc", models.TextField(blank=True, null=True)),
                ("ref_loc", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("numero", models.TextField(blank=True, null=True)),
                ("localidad", models.TextField(blank=True, null=True)),
                ("departamento", models.TextField(blank=True, null=True)),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("resploc_cuitcuil", models.TextField(blank=True, null=True)),
                ("resploc_doc", models.TextField(blank=True, null=True)),
                ("apellido_resp", models.TextField(blank=True, null=True)),
                ("nombre_resp", models.TextField(blank=True, null=True)),
                ("resploc_email", models.TextField(blank=True, null=True)),
                ("resploc_telefono", models.TextField(blank=True, null=True)),
                ("sup_tecnico", models.TextField(blank=True, null=True)),
                ("email_suptecnico", models.TextField(blank=True, null=True)),
                ("tel_suptecnico", models.TextField(blank=True, null=True)),
                ("categoria", models.TextField(blank=True, null=True)),
                ("cui_loc", models.TextField(blank=True, null=True)),
                ("cua_loc", models.TextField(blank=True, null=True)),
                ("cuof_loc", models.TextField(blank=True, null=True)),
                ("jornada", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Oferta CEF desde Padron",
                "verbose_name_plural": "Ofertas CEF desde Padron",
                "db_table": "v_capa_unica_ofertas_ant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefRolUsuario",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Rol de usuario CEF",
                "verbose_name_plural": "Roles de usuario CEF",
                "db_table": "usuarios_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefUsuarioPerfil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Perfil de usuario CEF",
                "verbose_name_plural": "Perfiles de usuario CEF",
                "db_table": "usuarios_perfilusuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefBeneficioSinoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de beneficio alimentario CEF",
                "verbose_name_plural": "Tipos de beneficio alimentario CEF",
                "db_table": '"cef"."beneficio_sino_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefCiclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=120)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("actual", models.BooleanField(default=False)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo CEF",
                "verbose_name_plural": "Ciclos CEF",
                "db_table": '"cef"."ciclos"',
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="CefCodigoRa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Codigo RA CEF",
                "verbose_name_plural": "Codigos RA CEF",
                "db_table": '"cef"."codigos_ra"',
                "ordering": ["orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="CefDiaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=30, unique=True)),
                ("numero", models.PositiveSmallIntegerField(unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia de semana CEF",
                "verbose_name_plural": "Dias de semana CEF",
                "db_table": '"cef"."dias_semana"',
                "ordering": ["orden", "numero"],
            },
        ),
        migrations.CreateModel(
            name="CefEje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Eje CEF",
                "verbose_name_plural": "Ejes CEF",
                "db_table": '"cef"."ejes"',
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "codigo_ra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="cef.cefcodigora",
                    ),
                ),
                (
                    "eje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="cef.cefeje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad CEF",
                "verbose_name_plural": "Actividades CEF",
                "db_table": '"cef"."actividades"',
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CefEspacioComedorTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de espacio comedor CEF",
                "verbose_name_plural": "Tipos de espacio comedor CEF",
                "db_table": '"cef"."espacio_comedor_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefFuenteFinanciamientoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de fuente de financiamiento CEF",
                "verbose_name_plural": "Tipos de fuente de financiamiento CEF",
                "db_table": '"cef"."fuente_financiamiento_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("numero", models.PositiveSmallIntegerField(default=1)),
                ("nombre", models.CharField(blank=True, max_length=150)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "cupo_maximo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("cerrado", "Cerrado"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("motivo_codigo_ra_override", models.TextField(blank=True)),
                (
                    "actividad_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "eje_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "codigo_ra_snapshot",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "codigo_ra_descripcion_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "turno_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=80),
                ),
                (
                    "turno_hora_desde_snapshot",
                    models.TimeField(blank=True, editable=False, null=True),
                ),
                (
                    "turno_hora_hasta_snapshot",
                    models.TimeField(blank=True, editable=False, null=True),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos",
                        to="cef.cefactividad",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "codigo_ra_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos_con_codigo_ra_override",
                        to="cef.cefcodigora",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo CEF",
                "verbose_name_plural": "Grupos CEF",
                "db_table": '"cef"."grupos"',
                "ordering": ["cueanexo", "-ciclo__anio", "actividad__nombre", "numero"],
            },
        ),
        migrations.CreateModel(
            name="CefGrupoDiaFuncionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dia_semana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos_funcionamiento",
                        to="cef.cefdiasemana",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias_funcionamiento",
                        to="cef.cefgrupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia de funcionamiento de grupo CEF",
                "verbose_name_plural": "Dias de funcionamiento de grupos CEF",
                "db_table": '"cef"."grupo_dias_func"',
                "ordering": ["grupo", "dia_semana__orden", "dia_semana__numero"],
            },
        ),
        migrations.CreateModel(
            name="CefInscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                            ("finalizado", "Finalizado"),
                            ("en_espera", "En espera"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones_cef",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="cef.cefgrupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripcion CEF",
                "verbose_name_plural": "Inscripciones CEF",
                "db_table": '"cef"."inscripciones"',
                "ordering": ["grupo", "alumno"],
            },
        ),
        migrations.CreateModel(
            name="CefInventarioCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de inventario CEF",
                "verbose_name_plural": "Categorias de inventario CEF",
                "db_table": '"cef"."inventario_categorias"',
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiales",
                        to="cef.cefinventariocategoria",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Material CEF",
                "verbose_name_plural": "Materiales CEF",
                "db_table": '"cef"."materiales"',
                "ordering": ["categoria__nombre", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CefInventarioMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("cantidad", models.PositiveIntegerField(default=0)),
                ("estado_descripcion", models.TextField(blank=True)),
                (
                    "material_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "categoria_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventario_materiales",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios",
                        to="cef.cefmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de material CEF",
                "verbose_name_plural": "Inventario de materiales CEF",
                "db_table": '"cef"."inventario_materiales"',
                "ordering": [
                    "cueanexo",
                    "-ciclo__anio",
                    "material__categoria__nombre",
                    "material__nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="CefNivelActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel de actividad CEF",
                "verbose_name_plural": "Niveles de actividad CEF",
                "db_table": '"cef"."niveles_actividad"',
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="nivel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="cef.cefnivelactividad",
            ),
        ),
        migrations.CreateModel(
            name="CefOrientacionTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de orientacion CEF",
                "verbose_name_plural": "Tipos de orientacion CEF",
                "db_table": '"cef"."orientacion_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefPrestacionTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de prestacion CEF",
                "verbose_name_plural": "Tipos de prestacion CEF",
                "db_table": '"cef"."prestacion_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CefDatosRelevamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                (
                    "nombre_seccion",
                    models.CharField(default="No corresponde", max_length=120),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "beneficio_codigo_snapshot",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "beneficio_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "fuente_codigo_snapshot",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "fuente_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "prestacion_codigo_snapshot",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "prestacion_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "espacio_comedor_codigo_snapshot",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "espacio_comedor_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "orientacion_codigo_snapshot",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "orientacion_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficio_alimentario_gratuito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_beneficio",
                        to="cef.cefbeneficiosinotipo",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_relevamiento",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "espacio_comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_espacio_comedor",
                        to="cef.cefespaciocomedortipo",
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_fuente_financiamiento",
                        to="cef.ceffuentefinanciamientotipo",
                    ),
                ),
                (
                    "c_orientacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_orientacion",
                        to="cef.ceforientaciontipo",
                    ),
                ),
                (
                    "prestacion_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datos_prestacion",
                        to="cef.cefprestaciontipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datos de relevamiento CEF",
                "verbose_name_plural": "Datos de relevamiento CEF",
                "db_table": '"cef"."datos_relevamiento"',
                "ordering": ["cueanexo", "-ciclo__anio"],
            },
        ),
        migrations.CreateModel(
            name="CefRangoEtario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("edad_desde_dias", models.PositiveIntegerField(default=0)),
                ("edad_hasta_dias", models.PositiveIntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango etario CEF",
                "verbose_name_plural": "Rangos etarios CEF",
                "db_table": '"cef"."rangos_etarios"',
                "ordering": ["orden", "edad_desde_dias", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="rango_etario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="cef.cefrangoetario",
            ),
        ),
        migrations.CreateModel(
            name="CefTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80)),
                ("hora_desde_referencia", models.TimeField()),
                ("hora_hasta_referencia", models.TimeField()),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno CEF",
                "verbose_name_plural": "Turnos CEF",
                "db_table": '"cef"."turnos"',
                "ordering": ["-ciclo__anio", "orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos",
                to="cef.cefturno",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefciclo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actual", True)),
                fields=("actual",),
                name="uq_cef_ciclo_actual",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdiasemana",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero__gte", 1), ("numero__lte", 7)),
                name="ck_cef_dia_num",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefgrupodiafuncionamiento",
            constraint=models.UniqueConstraint(
                fields=("grupo", "dia_semana"), name="uq_cef_grp_dia"
            ),
        ),
        migrations.AddIndex(
            model_name="cefinscripcion",
            index=models.Index(fields=["estado"], name="idx_cef_insc_est"),
        ),
        migrations.AddIndex(
            model_name="cefinscripcion",
            index=models.Index(fields=["fecha_inscripcion"], name="idx_cef_insc_fecha"),
        ),
        migrations.AddIndex(
            model_name="cefinscripcion",
            index=models.Index(
                fields=["alumno", "estado"], name="idx_cef_insc_alum_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinscripcion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado__in", ["activo", "en_espera"])),
                fields=("grupo", "alumno"),
                name="uq_cef_insc_abierta",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefmaterial",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"), name="uq_cef_mat_cat_nom"
            ),
        ),
        migrations.AddIndex(
            model_name="cefinventariomaterial",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_cef_inv_cue_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="cefinventariomaterial",
            index=models.Index(fields=["material"], name="idx_cef_inv_mat"),
        ),
        migrations.AddConstraint(
            model_name="cefinventariomaterial",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo", "material"), name="uq_cef_inv_cic_mat"
            ),
        ),
        migrations.AddIndex(
            model_name="cefdatosrelevamiento",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_cef_dat_cue_cic"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdatosrelevamiento",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo"), name="uq_cef_dat_cue_cic"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefturno",
            constraint=models.UniqueConstraint(
                fields=("ciclo", "nombre"), name="uq_cef_turno_cic_nom"
            ),
        ),
        migrations.AddIndex(
            model_name="cefgrupo",
            index=models.Index(
                fields=["cueanexo", "estado"], name="idx_cef_grp_cue_est"
            ),
        ),
        migrations.AddIndex(
            model_name="cefgrupo",
            index=models.Index(
                fields=["cueanexo", "ciclo"], name="idx_cef_grp_cue_cic"
            ),
        ),
        migrations.AddIndex(
            model_name="cefgrupo",
            index=models.Index(
                fields=["actividad", "estado"], name="idx_cef_grp_act_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefgrupo",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "ciclo", "actividad", "numero"),
                name="uq_cef_grp_cic_act_num",
            ),
        ),
    ]
