# Generated by Django 5.2.14 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cefinventariocategoria",
            name="actualizado_por",
        ),
        migrations.RemoveField(
            model_name="cefinventariocategoria",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="cefmaterial",
            name="categoria",
        ),
        migrations.AlterModelOptions(
            name="cefinventariomaterial",
            options={
                "ordering": [
                    "cueanexo",
                    "-ciclo__anio",
                    "material__orden",
                    "material__nombre",
                ],
                "verbose_name": "Inventario de material CEF",
                "verbose_name_plural": "Inventario de materiales CEF",
            },
        ),
        migrations.AlterModelOptions(
            name="cefmaterial",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Material CEF",
                "verbose_name_plural": "Materiales CEF",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "cef"."materiales" DROP CONSTRAINT IF EXISTS "uq_cef_mat_cat_nom";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="cefmaterial",
                    name="uq_cef_mat_cat_nom",
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cefinventariomaterial",
            name="categoria_nombre_snapshot",
        ),
        migrations.AlterField(
            model_name="cefmaterial",
            name="nombre",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name="CefInventarioCategoria",
        ),
    ]
