# Generated by Django 5.2.15 on 2026-06-30 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0002_remove_cefinventariocategoria_actualizado_por_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefDocenteBnh",
            fields=[
                (
                    "cuil",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("apellido", models.CharField(blank=True, max_length=150, null=True)),
                ("nombre", models.CharField(blank=True, max_length=150, null=True)),
                ("estado", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "verbose_name": "Docente BNH",
                "verbose_name_plural": "Docentes BNH",
                "db_table": '"bnh"."personas"',
                "ordering": ["apellido", "nombre", "cuil"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CefDocenteGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("docente_cuil", models.CharField(db_index=True, max_length=11)),
                (
                    "rol",
                    models.CharField(
                        choices=[("titular", "Titular"), ("suplente", "Suplente")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                (
                    "docente_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "docente_dni_snapshot",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "docente_estado_bnh_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docentes",
                        to="cef.cefgrupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente de grupo CEF",
                "verbose_name_plural": "Docentes de grupos CEF",
                "db_table": '"cef"."docentes_grupo"',
                "ordering": ["grupo", "rol", "docente_nombre_snapshot", "docente_cuil"],
                "indexes": [
                    models.Index(
                        fields=["docente_cuil", "estado"], name="idx_cef_doc_cuil_est"
                    ),
                    models.Index(
                        fields=["grupo", "estado"], name="idx_cef_doc_grp_est"
                    ),
                    models.Index(fields=["rol", "estado"], name="idx_cef_doc_rol_est"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "activo")),
                        fields=("grupo", "docente_cuil"),
                        name="uq_cef_doc_grp_cuil_act",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "activo")),
                        fields=("grupo", "rol"),
                        name="uq_cef_doc_grp_rol_act",
                    ),
                ],
            },
        ),
    ]
