# Generated by Django 5.2.15 on 2026-06-30 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        ("cef", "0003_cefdocentebnh_cefdocentegrupo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefAlumnoCef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                (
                    "alumno_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "alumno_documento_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                (
                    "alumno_cuil_snapshot",
                    models.CharField(blank=True, editable=False, max_length=11),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bancos_cef",
                        to="bnhalumnos.alumno",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos_cef",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno CEF",
                "verbose_name_plural": "Alumnos CEF",
                "db_table": '"cef"."alumnos_cef"',
                "ordering": ["cueanexo", "-ciclo__anio", "alumno_nombre_snapshot"],
                "indexes": [
                    models.Index(
                        fields=["cueanexo", "ciclo"], name="idx_cef_alumnocef_cic"
                    ),
                    models.Index(
                        fields=["alumno", "estado"], name="idx_cef_alumnocef_est"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "activo")),
                        fields=("cueanexo", "ciclo", "alumno"),
                        name="uq_cef_alumnocef_act",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CefDocenteCef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                ("docente_cuil", models.CharField(db_index=True, max_length=11)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=255)),
                (
                    "docente_nombre_snapshot",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "docente_dni_snapshot",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "docente_estado_bnh_snapshot",
                    models.CharField(blank=True, editable=False, max_length=30),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docentes_cef",
                        to="cef.cefciclo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente CEF",
                "verbose_name_plural": "Docentes CEF",
                "db_table": '"cef"."docentes_cef"',
                "ordering": [
                    "cueanexo",
                    "-ciclo__anio",
                    "docente_nombre_snapshot",
                    "docente_cuil",
                ],
                "indexes": [
                    models.Index(
                        fields=["cueanexo", "ciclo"], name="idx_cef_docentecef_cic"
                    ),
                    models.Index(
                        fields=["docente_cuil", "estado"], name="idx_cef_docentecef_est"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "activo")),
                        fields=("cueanexo", "ciclo", "docente_cuil"),
                        name="uq_cef_docentecef_act",
                    )
                ],
            },
        ),
    ]
