# Generated by Django 5.2.8 on 2026-08-14 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        ("cef", "0004_cefalumnocef_cefdocentecef"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cefinscripcion",
            name="uq_cef_insc_abierta",
        ),
        migrations.AlterField(
            model_name="cefinscripcion",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinscripcion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("grupo", "alumno"),
                name="uq_cef_insc_abierta",
            ),
        ),
    ]
