# Generated by Django 5.2.16 on 2026-07-27 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        ("cef", "0004_cefalumnocef_cefdocentecef"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefInventarioMaterialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("estado_descripcion", models.CharField(max_length=150)),
                (
                    "estado_normalizado",
                    models.CharField(editable=False, max_length=150),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Estado de material de inventario CEF",
                "verbose_name_plural": "Estados de materiales de inventario CEF",
                "db_table": '"cef"."inventario_materiales_estados"',
                "ordering": ["inventario_material", "estado_normalizado"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="cefinscripcion",
            name="uq_cef_insc_abierta",
        ),
        migrations.AlterField(
            model_name="cefinscripcion",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinscripcion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo")),
                fields=("grupo", "alumno"),
                name="uq_cef_insc_abierta",
            ),
        ),
        migrations.AddField(
            model_name="cefinventariomaterialestado",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cefinventariomaterialestado",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cefinventariomaterialestado",
            name="inventario_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribuciones_estado",
                to="cef.cefinventariomaterial",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinventariomaterialestado",
            constraint=models.UniqueConstraint(
                fields=("inventario_material", "estado_normalizado"),
                name="uq_cef_inv_est_norm",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinventariomaterialestado",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="ck_cef_inv_est_cant_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinventariomaterialestado",
            constraint=models.CheckConstraint(
                condition=models.Q(("estado_normalizado", ""), _negated=True),
                name="ck_cef_inv_est_no_vacio",
            ),
        ),
    ]
