# Generated by Django 5.2.16 on 2026-07-29 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0005_cefinventariomaterialestado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefEstadoMaterialTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de estado de material CEF",
                "verbose_name_plural": "Tipos de estado de materiales CEF",
                "db_table": '"cef"."estado_material_tipo"',
                "ordering": ["orden", "codigo", "nombre"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cefinventariomaterialestado",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distribuciones_inventario",
                to="cef.cefestadomaterialtipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinventariomaterialestado",
            constraint=models.UniqueConstraint(
                fields=("inventario_material", "estado"), name="uq_cef_inv_est_cat"
            ),
        ),
    ]
