# Generated by Django 5.2.16 on 2026-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0006_cefestadomaterialtipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cefinventariomaterialestado",
            name="observaciones",
        ),
    ]
