# Generated by Django 5.2.16 on 2026-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0007_remove_cefinventariomaterialestado_observaciones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cefdatosrelevamiento",
            name="nombre_seccion",
        ),
    ]
