# Generated by Django 5.2.16 on 2026-08-06 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bnhalumnos",
            "0012_remove_alumno_nivel_formacion_tutor_nivel_formacion_and_more",
        ),
        ("cef", "0008_remove_cefdatosrelevamiento_nombre_seccion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cefdocentegrupo",
            name="motivo_baja",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="fecha_baja",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="grupo_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos_derivados",
                to="cef.cefgrupo",
            ),
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="motivo_baja",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="nivel_nombre_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="cefgrupo",
            name="rango_etario_nombre_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="cefalumnocef",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cefdocentecef",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cefdocentegrupo",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cefdocentegrupo",
            name="fecha_desde",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cefgrupo",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("baja", "Baja")],
                db_index=True,
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cefgrupo",
            name="numero",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="cefalumnocef",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "activo"), ("fecha_baja__isnull", True)),
                    models.Q(("estado", "baja"), ("fecha_baja__isnull", False)),
                    _connector="OR",
                ),
                name="ck_cef_alumnocef_estado_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdocentecef",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "activo"), ("fecha_baja__isnull", True)),
                    models.Q(("estado", "baja"), ("fecha_baja__isnull", False)),
                    _connector="OR",
                ),
                name="ck_cef_docentecef_estado_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdocentegrupo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "activo"), ("fecha_hasta__isnull", True)),
                    models.Q(("estado", "baja"), ("fecha_hasta__isnull", False)),
                    _connector="OR",
                ),
                name="ck_cef_docgrp_estado_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefgrupo",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero__gte", 1)), name="ck_cef_grp_num_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefgrupo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "activo"), ("fecha_baja__isnull", True)),
                    models.Q(("estado", "baja"), ("fecha_baja__isnull", False)),
                    _connector="OR",
                ),
                name="ck_cef_grp_estado_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefinscripcion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "activo"), ("fecha_baja__isnull", True)),
                    models.Q(("estado", "baja"), ("fecha_baja__isnull", False)),
                    _connector="OR",
                ),
                name="ck_cef_insc_estado_fecha",
            ),
        ),
    ]
