# Generated by Django 5.2.16 on 2026-08-06 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0009_cefdocentegrupo_motivo_baja_cefgrupo_fecha_baja_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefGrupoEstadoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "estado_resultante",
                    models.CharField(
                        choices=[("activo", "Activo"), ("baja", "Baja")], max_length=20
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_estado",
                        to="cef.cefgrupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de estado de grupo CEF",
                "verbose_name_plural": "Movimientos de estado de grupos CEF",
                "db_table": '"cef"."grupo_estado_movimientos"',
                "ordering": ["grupo", "fecha", "creado_en", "pk"],
            },
        ),
    ]
