# Generated by Django 5.2.16 on 2026-08-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0010_cefgrupoestadomovimiento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cefciclo",
            name="cerrado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="cefciclo",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual", True), ("cerrado", True), _negated=True),
                name="ck_cef_ciclo_cerrado_actual",
            ),
        ),
    ]
