# Generated by Django 5.2.16 on 2026-08-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0011_cefciclo_cerrado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CefJornadaAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField(db_index=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jornadas_asistencia",
                        to="cef.cefgrupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada de asistencia CEF",
                "verbose_name_plural": "Jornadas de asistencia CEF",
                "db_table": '"cef"."jornadas_asistencia"',
                "ordering": ["-fecha", "grupo", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CefAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificada", "Justificada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="cef.cefinscripcion",
                    ),
                ),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="cef.cefjornadaasistencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia CEF",
                "verbose_name_plural": "Asistencias CEF",
                "db_table": '"cef"."asistencias"',
                "ordering": ["jornada", "inscripcion", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CefAsistenciaMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificada", "Justificada"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificada", "Justificada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asistencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="cef.cefasistencia",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de asistencia CEF",
                "verbose_name_plural": "Movimientos de asistencia CEF",
                "db_table": '"cef"."asistencia_movimientos"',
                "ordering": ["creado_en", "pk"],
                "indexes": [
                    models.Index(
                        fields=["asistencia", "creado_en"],
                        name="idx_cef_asist_mov_fecha",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cefjornadaasistencia",
            index=models.Index(
                fields=["grupo", "fecha"], name="idx_cef_jornada_grp_fecha"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefjornadaasistencia",
            constraint=models.UniqueConstraint(
                fields=("grupo", "fecha"), name="uq_cef_jornada_grupo_fecha"
            ),
        ),
        migrations.AddIndex(
            model_name="cefasistencia",
            index=models.Index(
                fields=["jornada", "estado"], name="idx_cef_asist_jornada_est"
            ),
        ),
        migrations.AddConstraint(
            model_name="cefasistencia",
            constraint=models.UniqueConstraint(
                fields=("jornada", "inscripcion"), name="uq_cef_asistencia_jornada_insc"
            ),
        ),
    ]
