# Generated by Django 5.2.16 on 2026-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0012_cefjornadaasistencia_cefasistencia_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cefturno",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Turno CEF",
                "verbose_name_plural": "Turnos CEF",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cefturno",
            name="uq_cef_turno_cic_nom",
        ),
        migrations.RemoveField(
            model_name="cefturno",
            name="ciclo",
        ),
        migrations.AlterField(
            model_name="cefturno",
            name="nombre",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
