# Generated by Django 5.2.17 on 2026-08-18 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0005_remove_cefinscripcion_uq_cef_insc_abierta_and_more"),
        ("cef", "0013_alter_cefturno_options_and_more"),
    ]

    operations = []
