# Generated by Django 5.2.16 on 2026-09-09 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cef", "0013_alter_cefturno_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cefdocentegrupo",
            name="uq_cef_doc_grp_rol_act",
        ),
        migrations.AlterField(
            model_name="cefdocentegrupo",
            name="rol",
            field=models.CharField(
                choices=[
                    ("titular", "Titular"),
                    ("suplente", "Suplente"),
                    ("interino", "Interino"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdocentegrupo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo"), ("rol", "titular")),
                fields=("grupo",),
                name="uq_cef_doc_grp_tit_act",
            ),
        ),
        migrations.AddConstraint(
            model_name="cefdocentegrupo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "activo"), ("rol", "interino")),
                fields=("grupo",),
                name="uq_cef_doc_grp_int_act",
            ),
        ),
    ]
