# Generated by Django 5.1.1 on 2025-02-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uegp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldocuegp",
            name="cueanexo",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Cueanexo"
            ),
        ),
        migrations.AlterField(
            model_name="personalnodocuegp",
            name="cueanexo",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Cueanexo"
            ),
        ),
    ]
