# Generated by Django 5.2.14 on 2026-05-22 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0003_tipoos"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documentotipo",
            table="documento_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="localidades",
            table="localidad_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="nacionalidad",
            table="nacionalidad_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="pais",
            table="pais_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="provincias",
            table="provincia_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="sexo",
            table="sexo_tipo_bnh",
        ),
        migrations.AlterModelTable(
            name="tipocomunidadoriginaria",
            table="tipo_comunidad_originaria_bnh",
        ),
        migrations.AlterModelTable(
            name="tipodiscapacidad",
            table="tipo_discapacidad_bnh",
        ),
        migrations.AlterModelTable(
            name="tipolenguaoriginaria",
            table="tipo_lengua_originaria_bnh",
        ),
        migrations.AlterModelTable(
            name="tipoos",
            table="tipo_obra_social_bnh",
        ),
        migrations.AlterModelTable(
            name="tipoplanessociales",
            table="tipo_planes_sociales_bnh",
        ),
    ]
