# Generated by Django 5.2.8 on 2026-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0009_tipodesigfunc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grado_anio",
            fields=[
                (
                    "c_grado_anio",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombre_grado_anio",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("c_niv_grado", models.IntegerField()),
                (
                    "t_niv_grado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Grado_Anio",
                "verbose_name_plural": "Grados_Anios",
                "db_table": "grado_anio",
            },
        ),
        migrations.CreateModel(
            name="Secciones",
            fields=[
                ("c_seccion", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nombre_seccion",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("c_niv_seccion", models.IntegerField()),
                (
                    "t_niv_seccion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Seccion",
                "verbose_name_plural": "Secciones",
                "db_table": "Secciones",
            },
        ),
    ]
