# Generated by Django 5.2.8 on 2026-06-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0011_alter_registroactividades_grado_anio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("LUNES", "Lunes"),
                            ("MARTES", "Martes"),
                            ("MIERCOLES", "Miércoles"),
                            ("JUEVES", "Jueves"),
                            ("VIERNES", "Viernes"),
                        ],
                        max_length=15,
                    ),
                ),
                ("hora_desde", models.TimeField()),
                ("hora_hasta", models.TimeField()),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="bnhpersonas.registroactividades",
                    ),
                ),
            ],
            options={
                "db_table": "horarios_actividad",
            },
        ),
    ]
