# Generated by Django 5.2.8 on 2026-06-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0013_horarioactividad_uuid_registroactividades_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horarioactividad",
            name="actividad",
        ),
        migrations.CreateModel(
            name="ActividadSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(db_index=True, max_length=9)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnhpersonas.registroactividades",
                    ),
                ),
            ],
            options={
                "unique_together": {("actividad", "cueanexo")},
            },
        ),
        migrations.AddField(
            model_name="horarioactividad",
            name="actividad_sede",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="bnhpersonas.actividadsede",
            ),
            preserve_default=False,
        ),
    ]
