# Generated by Django 5.2.8 on 2026-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_sesionusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivousuario",
            name="email_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dispositivousuario",
            name="fecha_envio_email",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispositivousuario",
            name="fecha_ultimo_intento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispositivousuario",
            name="intentos_envio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispositivousuario",
            name="ultimo_error_envio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
