# Generated by Django 5.2.8 on 2026-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_dispositivousuario_bloqueado"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivousuario",
            name="modelo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dispositivousuario",
            name="ubicacion",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
