# Generated by Django 5.2.8 on 2026-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_dispositivousuario_modelo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesionusuario",
            name="ubicacion",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
