# Generated by Django 4.2.5 on 2024-05-20 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegOpLectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asistencia", models.BooleanField(default=True)),
                ("cueanexo", models.CharField(max_length=9)),
                ("grado", models.CharField(max_length=25)),
                ("seccion", models.CharField(max_length=15)),
                ("dni", models.CharField(max_length=8)),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                (
                    "velocidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "prosodia",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "comprension",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "promedio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("desempeño", models.CharField(max_length=18)),
                ("año", models.IntegerField(max_length=4)),
                ("mes", models.CharField(max_length=10)),
                ("dni_docente", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name": "Registro_Op_Lectura",
                "verbose_name_plural": "Registros_Op_Lecturas",
                "ordering": ["cueanexo", "dni"],
            },
        ),
    ]
