# Generated by Django 4.2.5 on 2024-07-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_curso", models.CharField(max_length=15, verbose_name="Curso")),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "db_table": "Curso",
                "ordering": ["nom_curso"],
            },
        ),
        migrations.CreateModel(
            name="division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_division",
                    models.CharField(max_length=15, verbose_name="División"),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisiones",
                "db_table": "Divisiones",
                "ordering": ["nom_division"],
            },
        ),
        migrations.CreateModel(
            name="turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_turno", models.CharField(max_length=15, verbose_name="Turnos")),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "db_table": "Turnos",
                "ordering": ["nom_turno"],
            },
        ),
        migrations.CreateModel(
            name="RegDocporSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni_docen", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellido_docen",
                    models.CharField(max_length=255, verbose_name="Apellido"),
                ),
                (
                    "nombres_docen",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "validacion",
                    models.BooleanField(default=False, verbose_name="Validación"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.division",
                        verbose_name="División",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.turno",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Docente_Aplicador",
                "verbose_name_plural": "Docentes_Aplicadores",
                "db_table": "Docente_Aplicador",
                "ordering": ["apellido_docen", "nombres_docen"],
            },
        ),
    ]
