# Generated by Django 4.2.5 on 2024-05-25 17:41

import apps.oplectura.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="grado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomgrado", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RegComprension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_comp", models.CharField(max_length=150)),
                (
                    "puntaje_comp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegNivelDesmp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tnivel", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="sit_rev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situarev", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RegVelocidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_vel", models.CharField(max_length=150)),
                (
                    "puntaje_vel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "nivel_vel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regniveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegProsodia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_pros", models.CharField(max_length=150)),
                (
                    "puntaje_pros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "nivel_pros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regniveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegPrecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_prec", models.CharField(max_length=150)),
                (
                    "puntaje_prec",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "nivel_prec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regniveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegOpLectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asistencia", models.BooleanField(default=False)),
                ("cueanexo", models.CharField(max_length=9)),
                ("grado", models.CharField(max_length=25)),
                ("seccion", models.CharField(max_length=15)),
                ("dni", models.CharField(max_length=8)),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("puntaje_velocidad", models.IntegerField(blank=True, null=True)),
                ("nivel_velocidad", models.IntegerField(blank=True, null=True)),
                ("puntaje_precision", models.IntegerField(blank=True, null=True)),
                ("nivel_precision", models.IntegerField(blank=True, null=True)),
                ("puntaje_prosodia", models.IntegerField(blank=True, null=True)),
                ("nivel_prosodia", models.IntegerField(blank=True, null=True)),
                ("puntaje_comprension", models.IntegerField(blank=True, null=True)),
                ("nivel_comprension", models.IntegerField(blank=True, null=True)),
                ("año", models.IntegerField(max_length=4)),
                ("mes", models.CharField(default="mayo", max_length=10)),
                ("dni_docente", models.CharField(max_length=8)),
                (
                    "comprension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regcomprension",
                    ),
                ),
                (
                    "precision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regprecision",
                    ),
                ),
                (
                    "prosodia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regprosodia",
                    ),
                ),
                (
                    "velocidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.regvelocidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro_Op_Lectura",
                "verbose_name_plural": "Registros_Op_Lecturas",
                "ordering": ["cueanexo", "dni"],
            },
        ),
        migrations.AddField(
            model_name="regcomprension",
            name="nivel_comp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oplectura.regniveldesmp",
            ),
        ),
        migrations.CreateModel(
            name="DocenteGradoSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cueanexo",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.MaxLengthValidator(9),
                            django.core.validators.RegexValidator(
                                "^\\d+$",
                                message="Este campo solo puede contener dígitos.",
                            ),
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "dni",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MaxLengthValidator(8),
                            django.core.validators.RegexValidator(
                                "^\\d+$",
                                message="Este campo solo puede contener dígitos.",
                            ),
                        ],
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        max_length=50,
                        validators=[apps.oplectura.models.validate_seccion],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "ngrado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.grado",
                    ),
                ),
                (
                    "sitrev",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.sit_rev",
                    ),
                ),
            ],
        ),
    ]
