# Generated by Django 4.2.5 on 2024-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regoplectura",
            name="nivel_comprension",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regoplectura",
            name="nivel_precision",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regoplectura",
            name="nivel_prosodia",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regoplectura",
            name="nivel_velocidad",
            field=models.CharField(blank=True, null=True),
        ),
    ]
