# Generated by Django 4.2.5 on 2024-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regdocporseccion",
            name="dni_docen",
            field=models.CharField(max_length=9, verbose_name="DNI"),
        ),
    ]
