# Generated by Django 4.2.5 on 2024-05-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="niveldesmp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tnivel", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="velocidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_vel", models.CharField(max_length=15)),
                (
                    "nivel_vel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.niveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="prosodia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_pros", models.CharField(max_length=15)),
                (
                    "nivel_pros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.niveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="precision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_prec", models.CharField(max_length=15)),
                (
                    "nivel_prec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.niveldesmp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comprension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escala_comp", models.CharField(max_length=15)),
                (
                    "nivel_comp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.niveldesmp",
                    ),
                ),
            ],
        ),
    ]
