# Generated by Django 4.2.5 on 2024-07-31 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0002_alter_regdocporseccion_dni_docen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
    ]
