# Generated by Django 4.2.5 on 2024-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0002_niveldesmp_velocidad_prosodia_precision_comprension"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="prosodia",
            new_name="RegComprension",
        ),
        migrations.RenameModel(
            old_name="niveldesmp",
            new_name="RegNivelDesmp",
        ),
        migrations.RenameModel(
            old_name="comprension",
            new_name="RegPrecision",
        ),
        migrations.RenameModel(
            old_name="velocidad",
            new_name="RegProsodia",
        ),
        migrations.RenameModel(
            old_name="precision",
            new_name="RegVelocidad",
        ),
        migrations.RenameField(
            model_name="regcomprension",
            old_name="escala_pros",
            new_name="escala_comp",
        ),
        migrations.RenameField(
            model_name="regcomprension",
            old_name="nivel_pros",
            new_name="nivel_comp",
        ),
        migrations.RenameField(
            model_name="regprecision",
            old_name="escala_comp",
            new_name="escala_prec",
        ),
        migrations.RenameField(
            model_name="regprecision",
            old_name="nivel_comp",
            new_name="nivel_prec",
        ),
        migrations.RenameField(
            model_name="regprosodia",
            old_name="escala_vel",
            new_name="escala_pros",
        ),
        migrations.RenameField(
            model_name="regprosodia",
            old_name="nivel_vel",
            new_name="nivel_pros",
        ),
        migrations.RenameField(
            model_name="regvelocidad",
            old_name="escala_prec",
            new_name="escala_vel",
        ),
        migrations.RenameField(
            model_name="regvelocidad",
            old_name="nivel_prec",
            new_name="nivel_vel",
        ),
    ]
