# Generated by Django 4.2.5 on 2024-05-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0003_rename_prosodia_regcomprension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="grado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_grado", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="sit_rev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situacion_revista", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DocenteGradoSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9)),
                ("apellido_nombre", models.CharField(max_length=255)),
                ("dni", models.CharField(max_length=8)),
                ("seccion", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.grado",
                    ),
                ),
                (
                    "situa_revista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.sit_rev",
                    ),
                ),
            ],
        ),
    ]
