# Generated by Django 4.2.5 on 2024-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0003_alter_curso_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOperativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toperativo",
                    models.CharField(max_length=255, verbose_name="Tipo Operativo"),
                ),
            ],
            options={
                "verbose_name": "Operativo",
                "verbose_name_plural": "Operativos",
                "db_table": "Tipo_Operativo",
            },
        ),
    ]
