# Generated by Django 4.2.5 on 2024-05-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0003_alter_regoplectura_dni_docente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regoplectura",
            name="año",
            field=models.IntegerField(default=2024, max_length=4),
        ),
        migrations.AlterField(
            model_name="regoplectura",
            name="dni_docente",
            field=models.CharField(max_length=8),
        ),
    ]
