# Generated by Django 4.2.5 on 2024-08-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0004_tipooperativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="regdocporseccion",
            name="operativos",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="oplectura.tipooperativo",
                verbose_name="Operativo",
            ),
            preserve_default=False,
        ),
    ]
