# Generated by Django 4.2.5 on 2024-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0004_alter_regoplectura_año_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="oplecturaabril",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg", models.CharField(max_length=25)),
                ("cueanexo", models.CharField(max_length=9)),
                ("escuela", models.CharField(max_length=255)),
                ("ambito", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=255)),
                ("nombres", models.CharField(max_length=255)),
                ("dni", models.CharField(max_length=8)),
                ("puntaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("desempeño", models.CharField(max_length=100)),
            ],
        ),
    ]
