# Generated by Django 4.2.5 on 2024-05-21 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0004_grado_sit_rev_docentegradoseccion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docentegradoseccion",
            old_name="grado",
            new_name="ngrado",
        ),
        migrations.RenameField(
            model_name="docentegradoseccion",
            old_name="situa_revista",
            new_name="sitrev",
        ),
    ]
