# Generated by Django 4.2.5 on 2024-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0005_oplecturaabril"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regoplectura",
            name="año",
            field=models.IntegerField(default=2024),
        ),
    ]
