# Generated by Django 4.2.5 on 2024-08-01 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0005_regdocporseccion_operativos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=255, verbose_name="Periodos")),
            ],
            options={
                "verbose_name": "Periodo",
                "verbose_name_plural": "Periodos",
                "db_table": "Periodos",
            },
        ),
        migrations.CreateModel(
            name="RegEvaluacionFluidezLectora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asistencia",
                    models.BooleanField(default=False, verbose_name="Asistencia"),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("region", models.CharField(max_length=255, verbose_name="Regional")),
                ("grado", models.CharField(max_length=25, verbose_name="Curso")),
                ("seccion", models.CharField(max_length=25, verbose_name="División")),
                ("dni_alumno", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "apellido_alumno",
                    models.CharField(max_length=255, verbose_name="Apellido"),
                ),
                (
                    "nombres_alumno",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                (
                    "velocidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Velocidad",
                    ),
                ),
                (
                    "cal_vel",
                    models.CharField(
                        max_length=255, verbose_name="Calificación Velocidad"
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Precisión",
                    ),
                ),
                (
                    "cal_pres",
                    models.CharField(
                        max_length=255, verbose_name="Calificación Precisión"
                    ),
                ),
                (
                    "prosodia",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Prosodia",
                    ),
                ),
                (
                    "cal_pros",
                    models.CharField(
                        max_length=255, verbose_name="Calificación Prosodia"
                    ),
                ),
                (
                    "comprension",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Comprensión",
                    ),
                ),
                (
                    "cal_comp",
                    models.CharField(
                        max_length=255, verbose_name="Calificación Comprensión"
                    ),
                ),
                (
                    "tramo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.periodos",
                        verbose_name="Tramo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluacion_Lectora",
                "verbose_name_plural": "Evaluaciones_Lectoras",
                "db_table": "Evaluacion_Lectora",
                "ordering": ["cueanexo"],
            },
        ),
    ]
