# Generated by Django 4.2.5 on 2024-05-21 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0005_rename_grado_docentegradoseccion_ngrado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docentegradoseccion",
            old_name="apellido_nombre",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="grado",
            old_name="nombre_grado",
            new_name="nomgrado",
        ),
        migrations.RenameField(
            model_name="sit_rev",
            old_name="situacion_revista",
            new_name="situarev",
        ),
    ]
