# Generated by Django 4.2.5 on 2024-05-21 21:53

import apps.oplectura.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "oplectura",
            "0006_rename_apellido_nombre_docentegradoseccion_nombre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docentegradoseccion",
            name="cueanexo",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.MaxLengthValidator(9),
                    django.core.validators.RegexValidator(
                        "^\\d+$", message="Este campo solo puede contener dígitos."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="docentegradoseccion",
            name="dni",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.MaxLengthValidator(8),
                    django.core.validators.RegexValidator(
                        "^\\d+$", message="Este campo solo puede contener dígitos."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="docentegradoseccion",
            name="seccion",
            field=models.CharField(
                max_length=50, validators=[apps.oplectura.models.validate_seccion]
            ),
        ),
    ]
