# Generated by Django 4.2.5 on 2024-08-08 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0006_periodos_regevaluacionfluidezlectora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="comprension",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Comprensión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="precision",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="Precisión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="prosodia",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Prosodia",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="velocidad",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="Velocidad",
            ),
        ),
    ]
