# Generated by Django 4.2.5 on 2024-09-11 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0007_alter_regevaluacionfluidezlectora_comprension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="comprension",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Comprensión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="precision",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(70),
                ],
                verbose_name="Precisión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="velocidad",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(70),
                ],
                verbose_name="Velocidad",
            ),
        ),
    ]
