# Generated by Django 5.1.1 on 2024-10-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0008_alter_regevaluacionfluidezlectora_comprension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegAplicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("region", models.CharField(max_length=50, verbose_name="Regional")),
                ("apellido", models.CharField(max_length=255, verbose_name="Apellido")),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "validacion",
                    models.BooleanField(default=False, verbose_name="Validación"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.division",
                        verbose_name="División",
                    ),
                ),
                (
                    "operativos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.tipooperativo",
                        verbose_name="Operativo",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.turno",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reg_Aplicador",
                "verbose_name_plural": "Reg_Aplicadores",
                "db_table": "Aplicadores",
            },
        ),
    ]
