# Generated by Django 5.1.1 on 2024-10-22 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0009_regaplicador"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="regaplicador",
            table="AplicadoresEsc",
        ),
    ]
