# Generated by Django 5.1.1 on 2024-10-22 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0010_alter_regaplicador_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regaplicador",
            name="turno",
        ),
    ]
