# Generated by Django 5.1.1 on 2024-11-08 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplectura", "0011_remove_regaplicador_turno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="comprension",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Comprensión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="precision",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="Precisión",
            ),
        ),
        migrations.AlterField(
            model_name="regevaluacionfluidezlectora",
            name="velocidad",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="Velocidad",
            ),
        ),
    ]
