# Generated by Django 4.2.5 on 2024-06-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="NivelAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tacceso",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tipoacceso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel_Acceso",
                "verbose_name_plural": "Niveles_Accesos",
                "db_table": "Nivel_Acceso",
                "ordering": ["tacceso"],
            },
        ),
        migrations.CreateModel(
            name="UsuariosVisualizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=9, unique=True, verbose_name="usuario"),
                ),
                ("apellido", models.CharField(max_length=150, verbose_name="apellido")),
                ("nombres", models.CharField(max_length=150, verbose_name="nombres")),
                ("correo", models.EmailField(max_length=254, verbose_name="correo")),
                ("telefono", models.CharField(max_length=20, verbose_name="telefono")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="is_staff"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="is_superuser"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "nivelacceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.nivelacceso",
                        to_field="tacceso",
                        verbose_name="nivelacceso",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario_Visualizador",
                "verbose_name_plural": "Usuarios_Visualizadores",
                "db_table": "Usuario_Visualizador",
                "ordering": ["apellido", "nombres"],
            },
        ),
    ]
