# Generated by Django 4.2.5 on 2024-03-28 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NivelAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tacceso",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tipoacceso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel_Acceso",
                "verbose_name_plural": "Niveles_Accesos",
                "db_table": "Nivel_Acceso",
                "ordering": ["tacceso"],
            },
        ),
        migrations.CreateModel(
            name="UsuariosVisualizador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "nomusua",
                    models.CharField(max_length=9, unique=True, verbose_name="usuario"),
                ),
                (
                    "contraseña",
                    models.CharField(max_length=150, verbose_name="contraseña"),
                ),
                ("apellido", models.CharField(max_length=150, verbose_name="apellido")),
                ("nombres", models.CharField(max_length=150, verbose_name="nombres")),
                ("correo", models.EmailField(max_length=254, verbose_name="correo")),
                ("telefono", models.CharField(max_length=20, verbose_name="telefono")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                ("staff", models.BooleanField(default=True, verbose_name="is_staff")),
                (
                    "superusua",
                    models.BooleanField(default=False, verbose_name="is_superuser"),
                ),
                (
                    "nivelacceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.nivelacceso",
                        verbose_name="nivelacceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario_Visualizador",
                "verbose_name_plural": "Usuarios_Visulizadores",
                "db_table": "Usuario_Visualizador",
                "ordering": ["apellido", "nombres"],
            },
        ),
    ]
