# Generated by Django 5.2.8 on 2026-03-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="NivelAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tacceso",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tipoacceso"
                    ),
                ),
            ],
            options={
                "db_table": "usuarios_nivelacceso",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "categoria_acceso",
                    models.CharField(
                        choices=[
                            ("all", "Todo"),
                            ("regional", "Regional"),
                            ("propio", "Propio"),
                            ("nivel", "Nivel"),
                        ],
                        default="propio",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuariosVisualizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("username", models.CharField(max_length=11, unique=True)),
                ("apellido", models.CharField(max_length=150)),
                ("nombres", models.CharField(max_length=150)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "nivelacceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.nivelacceso",
                        to_field="tacceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario Visualizador",
                "verbose_name_plural": "Usuarios Visualizadores",
                "db_table": "Usuario_Visualizador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RegionalUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(db_index=True, max_length=11)),
                ("region_loc", models.CharField(db_index=True, max_length=100)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Usuario Regional",
                "verbose_name_plural": "Usuarios Regionales",
                "indexes": [
                    models.Index(
                        fields=["region_loc", "activo"],
                        name="usuarios_re_region__234e74_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionalUsuariosAgentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(db_index=True, max_length=11)),
                ("region_loc", models.CharField(db_index=True, max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana (07:00 - 13:00)"),
                            ("tarde", "Tarde (13:00 - 18:00)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gestor Regional",
                "verbose_name_plural": "Gestores Regionales",
                "indexes": [
                    models.Index(
                        fields=["region_loc", "activo"],
                        name="usuarios_re_region__fa49f5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usuarios.rol"
                    ),
                ),
            ],
        ),
    ]
