# Generated by Django 4.2.5 on 2024-04-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosvisualizador",
            name="nivelacceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.nivelacceso",
                to_field="tacceso",
                verbose_name="nivelacceso",
            ),
        ),
    ]
