# Generated by Django 4.2.5 on 2024-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosvisualizador",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="is_staff"),
        ),
    ]
