# Generated by Django 5.2.8 on 2026-03-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosvisualizador",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="is_staff"),
        ),
        migrations.CreateModel(
            name="RegionalUsuariosAgentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_loc", models.CharField(db_index=True, max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana (07:00 - 13:00)"),
                            ("tarde", "Tarde (13:00 - 18:00)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles_regionales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestor Regional",
                "verbose_name_plural": "Gestores Regionales",
                "indexes": [
                    models.Index(
                        fields=["region_loc", "activo"],
                        name="usuarios_re_region__fa49f5_idx",
                    )
                ],
            },
        ),
    ]
