# Generated by Django 5.2.8 on 2026-03-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_usuariosvisualizador_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalUsuariosAgentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_loc",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Regional"
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana (07:00 - 13:00)"),
                            ("tarde", "Tarde (13:00 - 18:00)"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Turno laboral",
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_regional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestor Regional",
                "verbose_name_plural": "Gestores Regionales",
                "indexes": [
                    models.Index(
                        fields=["region_loc", "turno"],
                        name="usuarios_re_region__cd5dd6_idx",
                    )
                ],
            },
        ),
    ]
