# Generated by Django 4.2.5 on 2024-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_usuariosvisualizador_last_login_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuariosvisualizador",
            old_name="nomusua",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="usuariosvisualizador",
            name="contraseña",
        ),
        migrations.AlterField(
            model_name="usuariosvisualizador",
            name="password",
            field=models.CharField(max_length=150, verbose_name="contraseña"),
        ),
    ]
