# Generated by Django 5.2.8 on 2026-03-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_usuariocueanexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.rol",
            ),
        ),
    ]
