# Generated by Django 5.2.8 on 2026-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_usuariosvisualizador_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalusuariosagentes",
            name="usuario",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
