# Generated by Django 4.2.5 on 2024-03-28 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_rename_nomusua_usuariosvisualizador_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuariosvisualizador",
            old_name="staff",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="usuariosvisualizador",
            old_name="superusua",
            new_name="is_superuser",
        ),
    ]
