# Generated by Django 5.2.8 on 2026-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalusuarios",
            name="rol_regional",
            field=models.CharField(default="Regional", max_length=255),
        ),
        migrations.AddField(
            model_name="regionalusuarios",
            name="t_acceso_regional",
            field=models.CharField(default="Regional", max_length=255),
        ),
        migrations.AddField(
            model_name="regionalusuariosagentes",
            name="rol_gestor",
            field=models.CharField(default="Gestor", max_length=255),
        ),
        migrations.AddField(
            model_name="regionalusuariosagentes",
            name="t_acceso_gestor",
            field=models.CharField(default="Gestor", max_length=255),
        ),
    ]
