# Generated by Django 5.2.8 on 2026-03-04 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_regionalusuariosagentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalusuariosagentes",
            name="usuario",
            field=models.OneToOneField(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_regional",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
