# Generated by Django 5.2.8 on 2026-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_regionalusuarios_rol_regional_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioSyncEstado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cuil", models.CharField(blank=True, max_length=20, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "usuarios_syncestado",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SyncControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=50, unique=True)),
                ("valor", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceso", models.CharField(max_length=50, unique=True)),
                ("en_ejecucion", models.BooleanField(default=False)),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("creados", models.IntegerField(default=0)),
                ("actualizados", models.IntegerField(default=0)),
                ("rechazados", models.IntegerField(default=0)),
                ("desactivados", models.IntegerField(default=0)),
                ("modo", models.CharField(default="incremental", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioRechazado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuitcuil", models.CharField(blank=True, max_length=20, null=True)),
                ("apellido", models.CharField(blank=True, max_length=150, null=True)),
                ("nombre", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("motivo", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Usuario rechazado",
                "verbose_name_plural": "Usuarios rechazados",
                "db_table": "usuarios_rechazados",
                "managed": True,
            },
        ),
    ]
