# Generated by Django 5.2.8 on 2026-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_usuariosyncestado_synccontrol_syncestado_synclog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioAuditoriaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("accion", models.CharField(max_length=20)),
                ("cambios", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioRechazadoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("motivo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
