# Generated by Django 5.2.8 on 2026-03-27 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_usuarioauditorialog_usuariorechazadolog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="synclog",
            old_name="fecha_fin",
            new_name="fin",
        ),
        migrations.RenameField(
            model_name="synclog",
            old_name="creados",
            new_name="insertados",
        ),
        migrations.RenameField(
            model_name="synclog",
            old_name="desactivados",
            new_name="total_procesados",
        ),
        migrations.RemoveField(
            model_name="synccontrol",
            name="clave",
        ),
        migrations.RemoveField(
            model_name="synccontrol",
            name="valor",
        ),
        migrations.RemoveField(
            model_name="synclog",
            name="fecha_inicio",
        ),
        migrations.RemoveField(
            model_name="synclog",
            name="modo",
        ),
        migrations.AddField(
            model_name="synccontrol",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synccontrol",
            name="nombre",
            field=models.CharField(default="directores", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="synclog",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synclog",
            name="estado",
            field=models.CharField(default="running", max_length=20),
        ),
        migrations.AddField(
            model_name="synclog",
            name="inicio",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 3, 27, 10, 6, 54, 364805, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
