# Generated by Django 5.2.8 on 2026-04-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0007_rename_fecha_fin_synclog_fin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioAccesoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("accion", models.CharField(max_length=50)),
                ("path", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
