# Generated by Django 5.2.8 on 2026-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0008_usuarioaccesolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncestado",
            name="cancelar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="usuarioaccesolog",
            index=models.Index(
                fields=["username"], name="usuarios_us_usernam_7bd0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuarioaccesolog",
            index=models.Index(fields=["fecha"], name="usuarios_us_fecha_2e2aca_idx"),
        ),
        migrations.AddIndex(
            model_name="usuarioaccesolog",
            index=models.Index(fields=["accion"], name="usuarios_us_accion_eb87a6_idx"),
        ),
    ]
