# Generated by Django 5.2.8 on 2026-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0009_syncestado_cancelar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="categoria_acceso",
            field=models.CharField(
                choices=[
                    ("all", "Todo"),
                    ("regional", "Regional"),
                    ("propio", "Propio"),
                    ("nivel", "Nivel"),
                    ("supervisor", "Supervisor"),
                ],
                default="propio",
                max_length=20,
            ),
        ),
    ]
