# Generated by Django 5.2.8 on 2026-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0011_estadousuario_passwordchangelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioIntermedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=150)),
                ("nombres", models.CharField(max_length=150)),
                ("cuil", models.CharField(max_length=20)),
                ("dni", models.CharField(max_length=20)),
                ("correo", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "intermediausuarios",
                "managed": False,
            },
        ),
    ]
