# Generated by Django 4.2.5 on 2024-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PadronOfertas",
            fields=[
                ("cueanexo", models.IntegerField(blank=True, null=True)),
                (
                    "id_establecimiento",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "id_localizacion",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "id_oferta_local",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nom_est", models.CharField(blank=True, null=True)),
                ("acronimo", models.CharField(blank=True, null=True)),
                ("oferta", models.CharField(blank=True, null=True)),
                ("nro_est", models.CharField(blank=True, null=True)),
                ("ambito", models.CharField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, null=True)),
                ("region_loc", models.CharField(blank=True, null=True)),
                ("ref_loc", models.CharField(blank=True, null=True)),
                ("calle", models.CharField(blank=True, null=True)),
                ("numero", models.CharField(blank=True, null=True)),
                ("localidad", models.CharField(blank=True, null=True)),
                ("departamento", models.CharField(blank=True, null=True)),
                ("estado_loc", models.CharField(blank=True, null=True)),
                ("est_oferta", models.CharField(blank=True, null=True)),
                ("estado_est", models.CharField(blank=True, null=True)),
                ("jornada", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "padron_ofertas",
                "managed": False,
            },
        ),
    ]
