# Generated by Django 4.2.5 on 2024-05-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id_estado", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="NivMod",
            fields=[
                ("id_nivel", models.AutoField(primary_key=True, serialize=False)),
                ("nivel_modalidad", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NomenCargosDoc",
            fields=[
                ("ceic", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docentes.estado",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docentes.nivmod",
                    ),
                ),
            ],
        ),
    ]
