#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting archivos estáticos..."
python3 /app/manage.py collectstatic --noinput

echo "Starting servidor Gunicorn..."
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
