# Generated by Django 4.2.5 on 2024-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escuelasupervisor",
            name="region_esc",
            field=models.CharField(default=1, max_length=15, verbose_name="Regional"),
            preserve_default=False,
        ),
    ]
