# Generated by Django 5.2.8 on 2026-04-08 14:21

import apps.supervisa2.models.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NivelModalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("codigo", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "nivel_modalidad",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="RegionalUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=11)),
                ("region_loc", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "usuarios_regionalusuarios",
            },
        ),
        migrations.CreateModel(
            name="SituacionRevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "situacion_revistas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Supervisor2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[apps.supervisa2.models.validators.validate_phone],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[
                            apps.supervisa2.models.validators.validate_email_strict
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "estado_validacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_REVISION", "En Revision"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "niveles_modalidad",
                    models.ManyToManyField(blank=True, to="supervisa2.nivelmodalidad"),
                ),
                (
                    "regiones",
                    models.ManyToManyField(blank=True, to="supervisa2.region"),
                ),
                (
                    "situacion_revista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supervisa2.situacionrevista",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="cuil",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisores",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "abm_supervisores",
                "ordering": ["usuario"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_loc", models.CharField(max_length=100)),
                (
                    "supervisor",
                    models.ForeignKey(
                        db_column="supervisor2_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_regiones",
                        to="supervisa2.supervisor2",
                    ),
                ),
            ],
            options={
                "db_table": "amb_supervisores_regiones",
            },
        ),
        migrations.AddConstraint(
            model_name="supervisor2",
            constraint=models.UniqueConstraint(
                fields=("usuario",), name="unique_supervisor_por_usuario"
            ),
        ),
    ]
