# Generated by Django 5.2.8 on 2026-04-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisa2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalusuario",
            name="categoria",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regionalusuario",
            name="rol",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
