# Generated by Django 5.2.8 on 2026-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisa2", "0002_regionalusuario_categoria_regionalusuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalusuario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
