# Generated by Django 5.2.8 on 2026-04-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervisa2", "0003_regionalusuario_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisor2",
            name="estado_validacion",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_REVISION", "En revisión"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
