# Generated by Django 4.2.5 on 2024-05-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="documentoTipo",
            fields=[
                ("c_doc", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_doc", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="grado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_grado", models.CharField(max_length=255)),
                ("c_grado", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="oferta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_oferta", models.CharField(max_length=255)),
                ("edad_desde", models.IntegerField()),
                ("edad_hasta", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="pais",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_pais", models.CharField(max_length=255)),
                ("c_pais", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="provincia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_prov", models.CharField(max_length=255)),
                ("c_prov", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="sexo",
            fields=[
                ("c_sexo", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_sexo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="nacionalidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_nacionalidad", models.CharField(max_length=255)),
                ("c_nacionalidad", models.IntegerField()),
                (
                    "c_pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.pais"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="localidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_loc", models.CharField(max_length=255)),
                ("c_loc", models.IntegerField()),
                ("c_dep", models.IntegerField()),
                ("descripcion_dep", models.CharField(max_length=255)),
                (
                    "c_prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alumnos.provincia",
                    ),
                ),
            ],
        ),
    ]
