# Generated by Django 4.2.5 on 2024-06-01 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="grado",
            new_name="grados",
        ),
        migrations.RenameField(
            model_name="documentotipo",
            old_name="c_doc",
            new_name="c_tdoc",
        ),
        migrations.RenameField(
            model_name="documentotipo",
            old_name="descripcion_doc",
            new_name="descrip_doc",
        ),
        migrations.RenameField(
            model_name="grados",
            old_name="descripcion_grado",
            new_name="descrip_grado",
        ),
        migrations.RenameField(
            model_name="localidad",
            old_name="descripcion_dep",
            new_name="descrip_dep",
        ),
        migrations.RenameField(
            model_name="localidad",
            old_name="descripcion_loc",
            new_name="descrip_loc",
        ),
        migrations.RenameField(
            model_name="nacionalidad",
            old_name="descripcion_nacionalidad",
            new_name="descrip_nacionalidad",
        ),
        migrations.RenameField(
            model_name="oferta",
            old_name="descripcion_oferta",
            new_name="descrip_oferta",
        ),
        migrations.RenameField(
            model_name="pais",
            old_name="descripcion_pais",
            new_name="descrip_pais",
        ),
        migrations.RenameField(
            model_name="provincia",
            old_name="descripcion_prov",
            new_name="descrip_prov",
        ),
        migrations.RenameField(
            model_name="sexo",
            old_name="descripcion_sexo",
            new_name="descrip_sex",
        ),
    ]
