# Generated by Django 5.1.1 on 2025-02-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscuelasBilingues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.BigIntegerField(verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Escuela")),
                ("acronimo", models.CharField(max_length=50, verbose_name="Acronimo")),
                ("oferta", models.CharField(max_length=255, verbose_name="Oferta")),
                ("ambito", models.CharField(max_length=255, verbose_name="Ambito")),
                ("sector", models.CharField(max_length=255, verbose_name="Sector")),
                ("region_loc", models.CharField(max_length=50, verbose_name="Region")),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
            ],
            options={
                "verbose_name": "Escuela_Bilingue",
                "verbose_name_plural": "Escuelas_Builingues",
                "db_table": "v_escuelas_bilingues",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nivel_curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(max_length=255, verbose_name="Nivel")),
                ("curso", models.CharField(max_length=255, verbose_name="Curso")),
            ],
            options={
                "verbose_name": "Nivel_Curso",
                "verbose_name_plural": "Niveles_Cursos",
                "db_table": "nivel_curso",
            },
        ),
        migrations.CreateModel(
            name="Alumnos_Bilingue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Escuela")),
                (
                    "seccion",
                    models.CharField(
                        choices=[
                            ("Única", "Única"),
                            ("Múltiple", "Múltiple"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=10,
                        verbose_name="Sección",
                    ),
                ),
                (
                    "lengua",
                    models.CharField(
                        choices=[
                            ("QOM", "QOM"),
                            ("MOCOIT", "MOCOIT"),
                            ("WICHI", "WICHI"),
                        ],
                        max_length=10,
                        verbose_name="Lengua",
                    ),
                ),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("mujeres", models.IntegerField(verbose_name="Mujeres")),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumnos_curso",
                        to="intercultural.nivel_curso",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumnos_nivel",
                        to="intercultural.nivel_curso",
                        verbose_name="Nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno_Bilingue",
                "verbose_name_plural": "Alumnos_Bilingues",
                "db_table": "alumno_bilingue",
            },
        ),
    ]
