# Generated by Django 5.1.1 on 2025-02-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alumnos_curso",
                to="intercultural.nivel_curso",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIAL", "INICIAL"),
                    ("PRIMARIO", "PRIMARIO"),
                    ("SECUNDARIO", "SECUNDARIO"),
                    ("SUPERIOR", "SUPERIOR"),
                ],
                max_length=50,
                verbose_name="Nivel",
            ),
        ),
    ]
