# Generated by Django 5.1.1 on 2025-02-15 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0002_alter_alumnos_bilingue_curso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumnos_bilingue",
            name="nom_est",
        ),
    ]
