# Generated by Django 5.1.1 on 2025-02-17 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0003_remove_alumnos_bilingue_nom_est"),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaAlumnosBilingue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Escuela")),
                ("lengua", models.CharField(max_length=50, verbose_name="Lengua")),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("mujeres", models.IntegerField(verbose_name="Mujeres")),
                (
                    "region_loc",
                    models.CharField(max_length=50, verbose_name="Regional"),
                ),
                (
                    "localidad",
                    models.CharField(max_length=155, verbose_name="Localidad"),
                ),
            ],
            options={
                "verbose_name": "Vista_Alumno_Bilingue",
                "verbose_name_plural": "Vistas_Alumnos_Bilingues",
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="mujeres",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Mujeres",
            ),
        ),
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIAL", "INICIAL"),
                    ("INICIAL - ESPECIAL", "INICIAL - ESPECIAL"),
                    ("PRIMARIO", "PRIMARIO"),
                    ("PRIMARIO - ADULTO", "PRIMARIO - ADULTO"),
                    ("PRIMARIO - ESPECIAL", "PRIMARIO - ESPECIAL"),
                    ("SECUNDARIO", "SECUNDARIO"),
                    ("SECUNDARIO - ADULTO", "SECUNDARIO - ADULTO"),
                    ("SUPERIOR", "SUPERIOR"),
                    ("EDUCACION TEMPRANA - ESPECIAL", "EDUCACION TEMPRANA - ESPECIAL"),
                ],
                max_length=50,
                verbose_name="Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="varones",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Varones",
            ),
        ),
    ]
