# Generated by Django 5.1.1 on 2025-02-17 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "intercultural",
            "0004_vistaalumnosbilingue_alter_alumnos_bilingue_mujeres_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vistaalumnosbilingue",
            table="cenpe.v_capa_unica_ofertas",
        ),
    ]
