# Generated by Django 5.1.1 on 2025-02-17 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0008_alter_vistaalumnosbilingue_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vistaalumnosbilingue",
            table="cenpe.v_capa_unica_ofertas",
        ),
    ]
