# Generated by Django 5.1.1 on 2025-02-17 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0009_alter_vistaalumnosbilingue_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vistaalumnosbilingue",
            table="v_alumnos_bilingue",
        ),
    ]
