# Generated by Django 5.1.1 on 2025-02-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0010_alter_vistaalumnosbilingue_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumnos_bilingue",
            name="lengua",
            field=models.CharField(
                choices=[("QOM", "QOM"), ("MOQOIT", "MOQOIT"), ("WICHI", "WICHI")],
                max_length=10,
                verbose_name="Pueblo Originario",
            ),
        ),
    ]
