# Generated by Django 5.1.1 on 2025-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0011_alter_alumnos_bilingue_lengua"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportarAlumnoBilingueConId",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=15)),
                ("nom_est", models.CharField(max_length=255)),
                ("sector", models.CharField(max_length=100)),
                ("ambito", models.CharField(max_length=100)),
                ("region_loc", models.CharField(max_length=100)),
                ("localidad", models.CharField(max_length=100)),
                ("departamento", models.CharField(max_length=100)),
                ("nivel", models.CharField(max_length=50)),
                ("curso", models.CharField(max_length=50)),
                ("seccion", models.CharField(max_length=10)),
                ("lengua", models.CharField(max_length=100)),
                ("varones", models.IntegerField()),
                ("mujeres", models.IntegerField()),
            ],
            options={
                "db_table": "cenpe.v_alumnos_bilingues_con_id",
                "managed": False,
            },
        ),
    ]
