# Generated by Django 5.1.1 on 2025-05-23 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intercultural", "0012_exportaralumnobilingueconid"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="exportaralumnobilingueconid",
            table="v_alumnos_bilingues_con_id",
        ),
    ]
