# Generated by Django 4.2.5 on 2024-07-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeicPuntos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(max_length=255, verbose_name="Nivel")),
                ("ceic_id", models.IntegerField(verbose_name="ciec_id")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("estado", models.BooleanField(verbose_name="Estado")),
                ("puntos", models.IntegerField(verbose_name="Puntos")),
            ],
            options={
                "db_table": "cenpe.ceic_puntos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="documento_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_tipo", models.IntegerField(verbose_name="c_tipo")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.documento_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="grado_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_grado", models.IntegerField(verbose_name="c_grado")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.grado_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="localidad_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_localidad", models.IntegerField(verbose_name="c_localidad")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("c_departamento", models.IntegerField(verbose_name="c_departamento")),
                (
                    "descripcion_dpto",
                    models.CharField(max_length=255, verbose_name="Descripción Dpto"),
                ),
            ],
            options={
                "db_table": "cenpe.localidad_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="nacionalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_nacionalidad", models.IntegerField(verbose_name="c_nacionalidad")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.nacionalidad",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="oferta_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_oferta", models.IntegerField(verbose_name="c_oferta")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.oferta_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="orientacion_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_orientacion", models.IntegerField(verbose_name="c_orientación")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.orientacion_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_pais", models.IntegerField(verbose_name="c_pais")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.pais",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="provincia_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_provincia", models.IntegerField(verbose_name="c_provincia")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.provincia_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="sexo_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_sexo", models.IntegerField(verbose_name="c_sexo")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "cenpe.sexo_tipo",
                "managed": False,
            },
        ),
    ]
