# Generated by Django 4.2.5 on 2024-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado_Civil_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion_estciv",
                    models.CharField(max_length=50, verbose_name="Estado Civil"),
                ),
            ],
            options={
                "verbose_name": "Estado Civil",
                "verbose_name_plural": "Estados Civiles",
                "db_table": "est_civil_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Estado_Titulo_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_titulo",
                    models.CharField(max_length=50, verbose_name="Estado Título"),
                ),
            ],
            options={
                "verbose_name": "Estado Titulo",
                "verbose_name_plural": "Estados Titulos",
                "db_table": "est_tit_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gestion_Institucion_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_gestion",
                    models.CharField(max_length=50, verbose_name="Tipo Gestión"),
                ),
            ],
            options={
                "verbose_name": "Tipo Gestion",
                "verbose_name_plural": "Tipos Gestiones",
                "db_table": "t_gestion_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Nivel_Formacion_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_form",
                    models.CharField(max_length=50, verbose_name="Nivel Formación"),
                ),
            ],
            options={
                "verbose_name": "Nivel Formacion",
                "verbose_name_plural": "Niveles Formacion",
                "db_table": "n_form_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipo_Formacion_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_form",
                    models.CharField(max_length=20, verbose_name="Tipo Formación"),
                ),
            ],
            options={
                "verbose_name": "Tipo Formacion",
                "verbose_name_plural": "Tipos Formacion",
                "db_table": "t_form_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipo_Institucion_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_inst",
                    models.CharField(max_length=50, verbose_name="Tipo Institución"),
                ),
            ],
            options={
                "verbose_name": "Tipo Institucion",
                "verbose_name_plural": "Tipos Instituciones",
                "db_table": "t_inst_cenpe",
                "managed": True,
            },
        ),
        migrations.AlterModelTable(
            name="ceicpuntos",
            table="ceic_puntos",
        ),
        migrations.AlterModelTable(
            name="documento_tipo",
            table="documento_tipo",
        ),
        migrations.AlterModelTable(
            name="grado_tipo",
            table="grado_tipo",
        ),
        migrations.AlterModelTable(
            name="localidad_tipo",
            table="localidad_tipo",
        ),
        migrations.AlterModelTable(
            name="nacionalidad",
            table="nacionalidad",
        ),
        migrations.AlterModelTable(
            name="oferta_tipo",
            table="oferta_tipo",
        ),
        migrations.AlterModelTable(
            name="orientacion_tipo",
            table="orientacion_tipo",
        ),
        migrations.AlterModelTable(
            name="pais",
            table="pais",
        ),
        migrations.AlterModelTable(
            name="provincia_tipo",
            table="provincia_tipo",
        ),
        migrations.AlterModelTable(
            name="sexo_tipo",
            table="sexo_tipo",
        ),
    ]
