# Generated by Django 4.2.5 on 2024-07-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cenpe", "0002_estado_civil_cenpe_estado_titulo_cenpe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nivel_Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niv_sis", models.CharField(max_length=255, verbose_name="Niveles")),
            ],
            options={
                "verbose_name": "Nivel",
                "verbose_name_plural": "Niveles",
                "db_table": "niv_sis_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipo_Trayectoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "t_trayecto",
                    models.CharField(max_length=255, verbose_name="Tipo trayecto"),
                ),
            ],
            options={
                "verbose_name": "Tipo Trayectoria",
                "verbose_name_plural": "Tipos Trayectorias",
                "db_table": "tipo_trayectoria_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Trayectoria_Ocupacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_ingreso", models.DateField(verbose_name="Fecha Ingreso")),
                (
                    "frente_alumno",
                    models.BooleanField(default=False, verbose_name="Frente Alumnos"),
                ),
                (
                    "anios_frentealumn",
                    models.IntegerField(verbose_name="Años Frente Alumno"),
                ),
                (
                    "apoyo",
                    models.BooleanField(default=False, verbose_name="Tareas de Apoyo"),
                ),
                ("anios_apoyo", models.IntegerField(verbose_name="Años Apoyo")),
                (
                    "func_dir",
                    models.BooleanField(
                        default=False, verbose_name="Funciones Directivas"
                    ),
                ),
                ("anios_dir", models.IntegerField(verbose_name="Años Dirección")),
                (
                    "act_extraesc",
                    models.BooleanField(verbose_name="Actividad fuera Sistema"),
                ),
                (
                    "cant_hs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Cantidad horas semanales",
                    ),
                ),
                (
                    "actual_tray",
                    models.ForeignKey(
                        db_column="actual_trayecto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_trayectorias",
                        to="cenpe.tipo_trayectoria",
                        verbose_name="Actualmente",
                    ),
                ),
                (
                    "ingreso_tray",
                    models.ForeignKey(
                        db_column="ingreso_trayecto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingreso_trayectorias",
                        to="cenpe.tipo_trayectoria",
                        verbose_name="Ingresó como",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trayectoria Ocupacional",
                "verbose_name_plural": "Trayectorias Ocupacionales",
                "db_table": "trayectoria_ocupacional_cenpe",
                "managed": True,
            },
        ),
    ]
