# Generated by Django 4.2.5 on 2024-07-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cenpe", "0003_nivel_sistema_tipo_trayectoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datos_Personal_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombres")),
                ("cuil", models.CharField(max_length=11, verbose_name="Cuil")),
                ("dni", models.CharField(max_length=9, verbose_name="Documento N°")),
                (
                    "telfijo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono Fijo",
                    ),
                ),
                (
                    "celular",
                    models.CharField(max_length=20, verbose_name="Teléfono Móvil"),
                ),
                ("f_nac", models.DateField(verbose_name="Fecha de Nacimiento")),
                (
                    "calle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Calle"
                    ),
                ),
                (
                    "nro",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "mz",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Manzana"
                    ),
                ),
                (
                    "pc",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Pc"
                    ),
                ),
                (
                    "casa",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Casa"
                    ),
                ),
                (
                    "piso",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Piso"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "estado_civil",
                    models.ForeignKey(
                        db_column="descripcion_estciv",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.estado_civil_cenpe",
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "loc_nac",
                    models.ForeignKey(
                        db_column="descripcion_loc",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.localidad_tipo",
                        verbose_name="Localidad Nacimiento",
                    ),
                ),
                (
                    "loc_resid",
                    models.ForeignKey(
                        db_column="descripcion_localidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localidad_residencia",
                        to="cenpe.localidad_tipo",
                        verbose_name="Localidad Residencia",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        db_column="descripcion_nacional",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.nacionalidad",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "nivel_form",
                    models.ForeignKey(
                        db_column="nivel_form",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.nivel_formacion_cenpe",
                        verbose_name="Nivel Formación",
                    ),
                ),
                (
                    "pais_nac",
                    models.ForeignKey(
                        db_column="descripcion_pais",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.pais",
                        verbose_name="País Nacimiento",
                    ),
                ),
                (
                    "prov_nac",
                    models.ForeignKey(
                        db_column="descripcion_prov",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.provincia_tipo",
                        verbose_name="Prov Nacimiento",
                    ),
                ),
                (
                    "prov_resid",
                    models.ForeignKey(
                        db_column="descripcion_provincia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincia_residencia",
                        to="cenpe.provincia_tipo",
                        verbose_name="Prov Residencia",
                    ),
                ),
                (
                    "sexo",
                    models.ForeignKey(
                        db_column="descripcion_sex",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.sexo_tipo",
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "t_doc",
                    models.ForeignKey(
                        db_column="descripcion_doc",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.documento_tipo",
                        verbose_name="Tipo Documento",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Cenpe",
                "verbose_name_plural": "Personales Cenpe",
                "db_table": "datos_personal_cenpe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Academica_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Nombre Título"),
                ),
                (
                    "reg_nro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Registro N°",
                    ),
                ),
                ("f_egreso", models.DateField(verbose_name="Fecha egreso")),
                (
                    "estado_tit",
                    models.ForeignKey(
                        db_column="estado_titulo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.estado_titulo_cenpe",
                        verbose_name="Estado Titulación",
                    ),
                ),
                (
                    "gestion_inst",
                    models.ForeignKey(
                        db_column="t_gestion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.gestion_institucion_cenpe",
                        verbose_name="Tipo Gestión",
                    ),
                ),
                (
                    "nivel_form",
                    models.ForeignKey(
                        db_column="nivel_form",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.nivel_formacion_cenpe",
                        verbose_name="Nivel Formación",
                    ),
                ),
                (
                    "tipo_form",
                    models.ForeignKey(
                        db_column="t_form",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.tipo_formacion_cenpe",
                        verbose_name="Tipo Formación",
                    ),
                ),
                (
                    "tipo_inst",
                    models.ForeignKey(
                        db_column="t_inst",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.tipo_institucion_cenpe",
                        verbose_name="Tipo Gestión",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academica",
                "verbose_name_plural": "Academicas",
                "db_table": "academica_cenpe",
                "managed": True,
            },
        ),
    ]
