# Generated by Django 4.2.5 on 2024-07-05 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cenpe", "0004_datos_personal_cenpe_academica_cenpe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academica_cenpe",
            name="estado_tit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.estado_titulo_cenpe",
                verbose_name="Estado Titulación",
            ),
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="gestion_inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.gestion_institucion_cenpe",
                verbose_name="Tipo Gestión",
            ),
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="nivel_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.nivel_formacion_cenpe",
                verbose_name="Nivel Formación",
            ),
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="tipo_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.tipo_formacion_cenpe",
                verbose_name="Tipo Formación",
            ),
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="tipo_inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.tipo_institucion_cenpe",
                verbose_name="Tipo Gestión",
            ),
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="estado_civil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.estado_civil_cenpe",
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="loc_nac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localidad_nacimiento",
                to="cenpe.localidad_tipo",
                verbose_name="Localidad Nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="loc_resid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.localidad_tipo",
                verbose_name="Localidad Residencia",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="nacionalidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.nacionalidad",
                verbose_name="Nacionalidad",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="nivel_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.nivel_formacion_cenpe",
                verbose_name="Nivel Formación",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="pais_nac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.pais",
                verbose_name="País Nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="prov_nac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provincia_nacimiento",
                to="cenpe.provincia_tipo",
                verbose_name="Prov Nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="prov_resid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.provincia_tipo",
                verbose_name="Prov Residencia",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="sexo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.sexo_tipo",
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="t_doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.documento_tipo",
                verbose_name="Tipo Documento",
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="usuario",
            field=models.CharField(max_length=11, verbose_name="usuario"),
        ),
        migrations.AlterField(
            model_name="trayectoria_ocupacional",
            name="actual_tray",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.tipo_trayectoria",
                verbose_name="Actualmente",
            ),
        ),
        migrations.AlterField(
            model_name="trayectoria_ocupacional",
            name="ingreso_tray",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingreso_trayectoria",
                to="cenpe.tipo_trayectoria",
                verbose_name="Ingresó como",
            ),
        ),
        migrations.AlterField(
            model_name="trayectoria_ocupacional",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
