# Generated by Django 4.2.5 on 2024-08-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0005_alter_academica_cenpe_estado_tit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos_personal_cenpe",
            name="barrio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Barrio"
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="loc_nac",
            field=models.CharField(max_length=150, verbose_name="Ciudad Nacimiento"),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="loc_resid",
            field=models.CharField(max_length=150, verbose_name="Localidad Residencia"),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="pc",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Parcela"
            ),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="prov_nac",
            field=models.CharField(max_length=150, verbose_name="País Nacimiento"),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="prov_resid",
            field=models.CharField(max_length=150, verbose_name="Provincia Residencia"),
        ),
    ]
