# Generated by Django 4.2.5 on 2024-08-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cenpe", "0006_datos_personal_cenpe_barrio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
