# Generated by Django 4.2.5 on 2024-08-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0007_alter_datos_personal_cenpe_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="prov_nac",
            field=models.CharField(max_length=150, verbose_name="Provincia Nacimiento"),
        ),
    ]
