# Generated by Django 4.2.5 on 2024-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0008_alter_datos_personal_cenpe_prov_nac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="celular",
            field=models.CharField(max_length=10, verbose_name="Teléfono Móvil"),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="dni",
            field=models.CharField(max_length=8, verbose_name="Documento N°"),
        ),
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="telfijo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Teléfono Fijo"
            ),
        ),
    ]
