# Generated by Django 4.2.5 on 2024-08-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0010_condicionactividad_funciones_situacionrevista"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academica_cenpe",
            name="estado_tit",
        ),
        migrations.AlterField(
            model_name="academica_cenpe",
            name="tipo_inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.tipo_institucion_cenpe",
                verbose_name="Tipo Institución",
            ),
        ),
    ]
