# Generated by Django 4.2.5 on 2024-08-30 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cenpe", "0011_remove_academica_cenpe_estado_tit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargosHoras_Cenpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "cant_horas",
                    models.SmallIntegerField(default=0, verbose_name="Cantidad_Horas"),
                ),
                ("fecha_desde", models.DateField(verbose_name="Fecha_desde")),
                (
                    "fecha_hasta",
                    models.DateField(
                        default=datetime.date(31, 12, 31), verbose_name="Fecha_hasta"
                    ),
                ),
                (
                    "cargos_horas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.ceicpuntos",
                        verbose_name="Cargos_Horas",
                    ),
                ),
                (
                    "condicion_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.condicionactividad",
                        verbose_name="Condición",
                    ),
                ),
                (
                    "funciones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.funciones",
                        verbose_name="Función",
                    ),
                ),
                (
                    "nivel_cargohora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.nivel_sistema",
                        verbose_name="Nivel_Cargo_Hora",
                    ),
                ),
                (
                    "situacion_revista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.situacionrevista",
                        verbose_name="Situacion_Revista",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
        ),
    ]
