# Generated by Django 4.2.5 on 2024-08-30 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0012_cargoshoras_cenpe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoshoras_cenpe",
            name="fecha_hasta",
            field=models.DateField(
                default=datetime.date(2060, 12, 31), verbose_name="Fecha_hasta"
            ),
        ),
    ]
