# Generated by Django 4.2.5 on 2024-09-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0013_alter_cargoshoras_cenpe_fecha_hasta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="usuario",
            field=models.CharField(max_length=9, verbose_name="Usuario"),
        ),
    ]
