# Generated by Django 4.2.5 on 2024-09-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0014_alter_datos_personal_cenpe_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academica_cenpe",
            name="usuario",
            field=models.CharField(max_length=9, verbose_name="Usuario"),
        ),
    ]
