# Generated by Django 4.2.5 on 2024-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0015_alter_academica_cenpe_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="cuof",
            field=models.SmallIntegerField(default=1, verbose_name="CUOF"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="cuof_anexo",
            field=models.SmallIntegerField(default=1, verbose_name="CUOF_Anexo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="jueves",
            field=models.BooleanField(default=False, verbose_name="Jueves"),
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="lunes",
            field=models.BooleanField(default=False, verbose_name="Lunes"),
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="martes",
            field=models.BooleanField(default=False, verbose_name="Martes"),
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="miercoles",
            field=models.BooleanField(default=False, verbose_name="Miercoles"),
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="viernes",
            field=models.BooleanField(default=False, verbose_name="Viernes"),
        ),
        migrations.AlterField(
            model_name="cargoshoras_cenpe",
            name="usuario",
            field=models.CharField(max_length=9, verbose_name="Usuario"),
        ),
    ]
