# Generated by Django 4.2.5 on 2024-09-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0016_cargoshoras_cenpe_cuof_cargoshoras_cenpe_cuof_anexo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria_Cueanexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_categoria",
                    models.CharField(max_length=50, verbose_name="Categoría"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoJornada_Cueanexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_jornada",
                    models.CharField(max_length=100, verbose_name="Jornada"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zona_Cueanexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_zona", models.CharField(max_length=255, verbose_name="Zona")),
            ],
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.categoria_cueanexo",
                verbose_name="Categoría",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="jornada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.tipojornada_cueanexo",
                verbose_name="Jornada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargoshoras_cenpe",
            name="zona",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cenpe.zona_cueanexo",
                verbose_name="Zona",
            ),
            preserve_default=False,
        ),
    ]
