# Generated by Django 4.2.5 on 2024-09-02 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0018_padroncenpe_alter_cargoshoras_cenpe_cargos_horas_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="padroncenpe",
            table="public.padron_actualizar",
        ),
    ]
