# Generated by Django 4.2.5 on 2024-09-02 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0019_alter_padroncenpe_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="padroncenpe",
            table="padron_actualizar",
        ),
    ]
