# Generated by Django 4.2.5 on 2024-09-03 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0022_alter_padroncenpe_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condicionactividad",
            options={
                "managed": True,
                "ordering": ["cond_act"],
                "verbose_name": "Condicion Actividad",
                "verbose_name_plural": "Condiciones Actividades",
            },
        ),
    ]
