# Generated by Django 4.2.5 on 2024-09-03 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0023_alter_condicionactividad_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zona_cueanexo",
            options={"ordering": ["tipo_zona"]},
        ),
    ]
