# Generated by Django 4.2.5 on 2024-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0024_alter_zona_cueanexo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos_personal_cenpe",
            name="id_jurisdiccional",
            field=models.BigIntegerField(default=1, verbose_name="Id_jurisdiccional"),
            preserve_default=False,
        ),
    ]
