# Generated by Django 4.2.5 on 2024-09-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0025_datos_personal_cenpe_id_jurisdiccional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_personal_cenpe",
            name="id_jurisdiccional",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Id_jurisdiccional"
            ),
        ),
    ]
