# Generated by Django 4.2.5 on 2024-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0026_alter_datos_personal_cenpe_id_jurisdiccional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoshoras_cenpe",
            name="cant_horas",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Cantidad_Horas"
            ),
        ),
    ]
