# Generated by Django 4.2.5 on 2024-09-04 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0027_alter_cargoshoras_cenpe_cant_horas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funciones",
            options={
                "managed": True,
                "ordering": ["funcion"],
                "verbose_name": "Funcion",
                "verbose_name_plural": "Funciones",
            },
        ),
    ]
