# Generated by Django 4.2.5 on 2024-09-04 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0028_alter_funciones_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nivel_sistema",
            options={
                "managed": True,
                "ordering": ["niv_sis"],
                "verbose_name": "Nivel",
                "verbose_name_plural": "Niveles",
            },
        ),
    ]
