# Generated by Django 5.2.8 on 2026-04-08 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0029_alter_nivel_sistema_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="situacionrevista",
            table="situacion_revista_cenpe",
        ),
    ]
