from django.contrib import admin
from .models import * 

admin.site.register(CeicPuntos)
admin.site.register(documento_tipo)
admin.site.register(grado_tipo)
admin.site.register(provincia_tipo)
admin.site.register(localidad_tipo)
admin.site.register(pais)
admin.site.register(nacionalidad)
admin.site.register(oferta_tipo)
admin.site.register(orientacion_tipo)
admin.site.register(sexo_tipo)
admin.site.register(Nivel_Formacion_Cenpe)
admin.site.register(Estado_Civil_Cenpe)
admin.site.register(Estado_Titulo_Cenpe)
admin.site.register(Datos_Personal_Cenpe)
admin.site.register(Academica_Cenpe)
admin.site.register(Tipo_Formacion_Cenpe)
admin.site.register(Tipo_Institucion_Cenpe)
admin.site.register(Gestion_Institucion_Cenpe)
admin.site.register(Nivel_Sistema)
admin.site.register(Tipo_Trayectoria)
admin.site.register(Trayectoria_Ocupacional)
