# Generated by Django 5.2.8 on 2026-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NivelFormacion",
            fields=[
                (
                    "c_nivel_formacion",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descrip_nivel_formacion", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Nivel Formación",
                "verbose_name_plural": "Niveles Formación",
                "db_table": "nivel_formacion",
                "managed": False,
            },
        ),
    ]
