# Generated by Django 5.2.8 on 2026-09-03 10:38

from django.db import migrations, models


def ensure_columns(apps, schema_editor):
    # Algunos CSV provienen de tablas a las que c_modalidad se agregó manualmente.
    # Incorporar esa columna al estado ORM no debe recrearla ni perder sus valores.
    for name in ("Grado_anio", "Secciones"):
        model = apps.get_model("bnhpersonas", name)
        table = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {c.name: c for c in schema_editor.connection.introspection.get_table_description(cursor, table)}
        existing = columns.get("c_modalidad")
        if existing:
            kind = schema_editor.connection.introspection.get_field_type(existing.type_code, existing)
            if kind not in ("IntegerField", "BigIntegerField", "SmallIntegerField", "PositiveIntegerField", "PositiveSmallIntegerField"):
                raise RuntimeError(f"{table}.c_modalidad existe pero no es entero. Revise el esquema antes de continuar.")
            # Un esquema con NOT NULL también admite los CSV (todos tienen modalidad).
            # No se reescriben valores ni se relaja una restricción ya instalada.
            continue
        field = models.IntegerField(blank=True, null=True)
        field.set_attributes_from_name("c_modalidad")
        field.model = model
        schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('bnhpersonas', '0019_integridad'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(ensure_columns, migrations.RunPython.noop)],
            state_operations=[
        migrations.AddField(
            model_name='grado_anio',
            name='c_modalidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secciones',
            name='c_modalidad',
            field=models.IntegerField(blank=True, null=True),
        ),
            ],
        ),
        migrations.AddIndex(
            model_name='grado_anio',
            index=models.Index(fields=['c_modalidad', 'c_niv_grado', 'estado'], name='bnh_grado_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='secciones',
            index=models.Index(fields=['c_modalidad', 'c_niv_seccion', 'estado'], name='bnh_seccion_parent_idx'),
        ),
    ]
