# Generated by Django 5.2.8 on 2026-09-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0020_dependencia_catalogos"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspacioCurricularNombre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_espacio_curricular", models.BigIntegerField()),
                ("id_titulacion", models.IntegerField()),
                ("id_nombre_espacio_curricular", models.IntegerField()),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Espacio Curricular Nombre",
                "verbose_name_plural": "Espacios Curriculares Nombres",
                "db_table": "espacio_curricular_nombre",
            },
        ),
        migrations.CreateModel(
            name="ModalidadTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_modalidad1", models.SmallIntegerField()),
                ("descripcion", models.CharField(max_length=255)),
                ("orden", models.SmallIntegerField()),
            ],
            options={
                "verbose_name": "Modalidad Tipo",
                "verbose_name_plural": "Modalidades Tipo",
                "db_table": "modalidad1_tipo",
            },
        ),
        migrations.CreateModel(
            name="NivelServicioTipo",
            fields=[
                (
                    "c_nivel",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("c_modalidad1", models.SmallIntegerField()),
            ],
            options={
                "verbose_name": "Nivel Servicio Tipo",
                "verbose_name_plural": "Niveles Servicio Tipo",
                "db_table": "nivel_servicio_tipo",
            },
        ),
        migrations.CreateModel(
            name="PofTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_pof", models.SmallIntegerField()),
                ("descrip_pof", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo Pof",
                "verbose_name_plural": "Tipos Pof",
                "db_table": "tipo_pof",
            },
        ),
        migrations.CreateModel(
            name="TitulacionNombre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_nombre_titulacion", models.IntegerField()),
                ("id_titulacion", models.IntegerField()),
                ("descripcion_adicional", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("c_nivel_servicio", models.SmallIntegerField()),
                ("c_modalidad1", models.SmallIntegerField()),
            ],
            options={
                "verbose_name": "Titulacion Nombre",
                "verbose_name_plural": "Titulaciones Nombre",
                "db_table": "titulacion_nombre",
            },
        ),
    ]
