# Generated by Django 5.2.8 on 2026-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0024_alter_titulacionsuperior_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitulacionFP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_titulacion", models.IntegerField()),
                ("c_nivel_servicio", models.SmallIntegerField()),
                ("c_modalidad1", models.SmallIntegerField()),
                ("descripcion", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Titulacion FP",
                "verbose_name_plural": "Titulaciones FP",
                "db_table": "titulacion_fp",
            },
        ),
    ]
