# Generated by Django 5.2.8 on 2026-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0028_alter_condicionactividadnombre_encuadre"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_tpersonal", models.SmallIntegerField()),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo Personal",
                "verbose_name_plural": "Tipos Personales",
                "db_table": "tipo_personal",
            },
        ),
        migrations.AddField(
            model_name="condicionactividadnombre",
            name="t_personal",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
