# Generated by Django 5.1.1 on 2025-09-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termino", models.CharField(max_length=255, verbose_name="Término")),
                ("definicion", models.TextField(verbose_name="Definición")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField(verbose_name="Pregunta")),
                ("respuesta", models.TextField(verbose_name="Respuesta")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
