# Generated by Django 5.1.1 on 2025-03-10 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accesibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("sanitarios", models.IntegerField(verbose_name="Sanitarios")),
                ("asensores", models.IntegerField(verbose_name="Asensores")),
                ("montacargas", models.IntegerField(verbose_name="Montacargas")),
                ("escaleras", models.IntegerField(verbose_name="Escaleras")),
                ("rampas", models.IntegerField(verbose_name="Rampas")),
            ],
            options={
                "verbose_name": "Accesibilidad",
                "verbose_name_plural": "Accesibilidades",
                "db_table": "accesibilidad",
            },
        ),
        migrations.CreateModel(
            name="DatosEscuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nom_Est")),
                ("calle", models.CharField(max_length=255, verbose_name="Calle")),
                ("nro", models.IntegerField(verbose_name="Nro")),
                ("circ", models.CharField(max_length=5, verbose_name="Circ")),
                ("mz", models.CharField(max_length=5, verbose_name="Mz")),
                ("pc", models.CharField(max_length=5, verbose_name="Mz")),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                ("anio_edif", models.IntegerField(verbose_name="Inauguracion")),
                (
                    "patrimonio",
                    models.BooleanField(default=False, verbose_name="Patrimonio"),
                ),
                ("antiguedad", models.IntegerField(verbose_name="Antigüedad")),
                (
                    "dist_munic",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Distancia_Municipio",
                    ),
                ),
                (
                    "dist_tierra",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Distancia_Tierra"
                    ),
                ),
                (
                    "dist_pavim",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Distancia_Pavimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato_Escuela",
                "verbose_name_plural": "Datos_Escuelas",
                "db_table": "dato_escuela",
            },
        ),
        migrations.CreateModel(
            name="DominioEscuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        choices=[
                            ("PROPIO", "PROPIO"),
                            ("LOCACION", "LOCACION"),
                            ("COMODATO", "COMODATO"),
                            ("CESION", "CESION"),
                            ("OTRO", "OTRO"),
                        ],
                        max_length=50,
                        verbose_name="Dominio",
                    ),
                ),
                ("plan_const", models.CharField(max_length=255, verbose_name="Plan")),
                ("ampliacion", models.IntegerField(verbose_name="Ampliación")),
                (
                    "plan_ampl",
                    models.CharField(max_length=255, verbose_name="Plan_Ampliación"),
                ),
                (
                    "sup_terrreno",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Sup_Terreno"
                    ),
                ),
                (
                    "sup_cub",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Sup_Cubierta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio_Escuela",
                "verbose_name_plural": "Dominios_Escuelas",
                "db_table": "dominio_escuela",
            },
        ),
        migrations.CreateModel(
            name="EspaciosPedagogicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("aulas_comunes", models.IntegerField(verbose_name="Aulas_Comunes")),
                ("aulas_aire", models.IntegerField(verbose_name="Aulas_Aire")),
                ("sum", models.IntegerField(verbose_name="SUM")),
                ("laboratorio", models.IntegerField(verbose_name="Laboratorio")),
                ("playon_depo", models.IntegerField(verbose_name="Playon_Deportivo")),
            ],
            options={
                "verbose_name": "Espacio_Pedagogico",
                "verbose_name_plural": "Espacios_Pedagogicos",
                "db_table": "espacio_pedagogico",
            },
        ),
        migrations.CreateModel(
            name="Sanitarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("bebederos", models.IntegerField(verbose_name="Bebederos")),
                ("inodoros", models.IntegerField(verbose_name="Inodoros")),
                ("lavatorios", models.IntegerField(verbose_name="Lavatorios")),
                ("mingitorios", models.IntegerField(verbose_name="Mingitorios")),
                ("bidet", models.IntegerField(verbose_name="Bidet")),
                ("letrinas", models.IntegerField(verbose_name="Letrinas")),
            ],
            options={
                "verbose_name": "Sanitario",
                "verbose_name_plural": "Sanitarios",
                "db_table": "sanitarios",
            },
        ),
        migrations.CreateModel(
            name="Seguridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("alarma", models.BooleanField(default=False, verbose_name="Alarma")),
                (
                    "contraincendio",
                    models.BooleanField(default=False, verbose_name="Contraincendio"),
                ),
                ("rejas", models.BooleanField(default=False, verbose_name="Rejas")),
                ("cerco", models.BooleanField(default=False, verbose_name="Escaleras")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BUENO", "BUENO"),
                            ("REGULAR", "REGULAR"),
                            ("MALO", "MALO"),
                        ],
                        max_length=25,
                        verbose_name="Rampas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguridad",
                "verbose_name_plural": "Seguridades",
                "db_table": "seguridad",
            },
        ),
    ]
