# Generated by Django 5.1.1 on 2025-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                ("c_departamento", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_dpto", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "departamentos_chaco",
            },
        ),
    ]
