# Generated by Django 5.1.1 on 2025-03-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cenpe", "0029_alter_nivel_sistema_options"),
        ("infraestructura", "0002_departamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localidad",
            fields=[
                ("c_localidad", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion_loc", models.CharField(max_length=255)),
                (
                    "c_departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infraestructura.departamento",
                    ),
                ),
                (
                    "c_provincia",
                    models.ForeignKey(
                        db_column="c_provincia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cenpe.provincia_tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "db_table": "localidades",
            },
        ),
    ]
