# Generated by Django 5.1.1 on 2025-03-10 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0003_localidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="VCapaUnicaOfertasCuiCuof",
            fields=[
                (
                    "cueanexo",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("nom_est", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "padron_cueanexo",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("acronimo", models.TextField(blank=True, null=True)),
                ("oferta", models.TextField(blank=True, null=True)),
                ("etiqueta", models.TextField(blank=True, null=True)),
                ("nro_est", models.IntegerField(blank=True, null=True)),
                ("ambito", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("region_loc", models.CharField(blank=True, max_length=100, null=True)),
                ("ref_loc", models.CharField(blank=True, max_length=100, null=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                ("localidad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estado_loc", models.TextField(blank=True, null=True)),
                ("est_oferta", models.TextField(blank=True, null=True)),
                ("estado_est", models.TextField(blank=True, null=True)),
                ("cui_loc", models.CharField(blank=True, max_length=50, null=True)),
                ("cuof_loc", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "v_capa_unica_ofertas_cui_cuof",
                "managed": False,
            },
        ),
    ]
