# Generated by Django 5.1.1 on 2025-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0004_vcapaunicaofertascuicuof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosescuela",
            name="departamento",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="datosescuela",
            name="localidad",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Localidad"
            ),
        ),
    ]
