# Generated by Django 5.1.1 on 2025-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0005_alter_datosescuela_departamento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosescuela",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="datosescuela",
            name="localidad",
        ),
        migrations.AddField(
            model_name="datosescuela",
            name="departamentos",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Departamento"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datosescuela",
            name="localidades",
            field=models.CharField(default=1, max_length=255, verbose_name="Localidad"),
            preserve_default=False,
        ),
    ]
