# Generated by Django 5.2.8 on 2026-03-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0005_alter_datosescuela_departamento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dominioescuela",
            old_name="sup_terrreno",
            new_name="sup_terreno",
        ),
        migrations.RemoveField(
            model_name="datosescuela",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="datosescuela",
            name="localidad",
        ),
        migrations.AlterField(
            model_name="datosescuela",
            name="departamentos",
            field=models.CharField(max_length=255, verbose_name="Departamento"),
        ),
        migrations.AlterField(
            model_name="datosescuela",
            name="localidades",
            field=models.CharField(default=3, max_length=255, verbose_name="Localidad"),
            preserve_default=False,
        ),
    ]
