# Generated by Django 5.2.8 on 2026-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "infraestructura",
            "0006_rename_sup_terrreno_dominioescuela_sup_terreno_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dominioescuela",
            old_name="sup_terreno",
            new_name="sup_terrreno",
        ),
    ]
