# Generated by Django 5.1.1 on 2025-03-11 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0006_remove_datosescuela_departamento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dominioescuela",
            old_name="sup_terrreno",
            new_name="sup_terreno",
        ),
    ]
