# Generated by Django 5.2.8 on 2026-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0007_rename_sup_terreno_dominioescuela_sup_terrreno"),
    ]

    operations = [
        migrations.AddField(
            model_name="datosescuela",
            name="sup_terrreno",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Sup_Terreno"
            ),
            preserve_default=False,
        ),
    ]
