# Generated by Django 5.2.8 on 2026-03-18 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infraestructura", "0008_datosescuela_sup_terrreno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datosescuela",
            old_name="sup_terrreno",
            new_name="sup_terreno",
        ),
        migrations.RenameField(
            model_name="dominioescuela",
            old_name="sup_terrreno",
            new_name="sup_terreno",
        ),
    ]
