# Generated by Django 5.1.1 on 2025-02-21 14:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aguapey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("total_mes", models.IntegerField(verbose_name="Total Mes")),
                ("total_base", models.IntegerField(verbose_name="Total Base")),
            ],
            options={
                "verbose_name": "Aguapey",
                "verbose_name_plural": "Aguapeys",
                "db_table": "Aguapey",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INICIAL", "INICIAL"),
                            ("PRIMARIO", "PRIMARIO"),
                            ("SECUNDARIO", "SECUNDARIO"),
                            ("PRIMARIO ADULTO", "PRIMARIO ADULTO"),
                            ("SECUNDARIO ADULTO", "SECUNDARIO ADULTO"),
                            ("SUPERIOR NO UNIVERSITARIO", "SUPERIOR NO UNIVERSITARIO"),
                            ("UNIVERSITARIO", "UNIVERSITARIO"),
                            ("OTROS", "OTROS"),
                        ],
                        max_length=50,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        choices=[
                            ("ALUMNOS", "ALUMNOS"),
                            ("DOCENTES", "DOCENTES"),
                            ("OTROS", "OTROS"),
                        ],
                        max_length=50,
                        verbose_name="Usuarios",
                    ),
                ),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("total", models.IntegerField(verbose_name="Total")),
            ],
            options={
                "verbose_name": "Asistencia_Usuario",
                "verbose_name_plural": "Asistencias_Usuarios",
                "db_table": "asistencia_usuario",
            },
        ),
        migrations.CreateModel(
            name="InstitucionesPrestaServicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("escuela", models.CharField(max_length=255, verbose_name="Escuela")),
                ("matricula", models.IntegerField(verbose_name="Matricula")),
                ("docentes", models.IntegerField(verbose_name="Docentes")),
                ("matricdisc", models.IntegerField(verbose_name="Discapacidad")),
                ("etnia", models.IntegerField(verbose_name="Etnia")),
            ],
            options={
                "verbose_name": "Institucion_Servicio",
                "verbose_name_plural": "Instituciones_Servicios",
                "db_table": "institucion_servicio",
            },
        ),
        migrations.CreateModel(
            name="ServiciosMatBiblio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_servicio", models.IntegerField(verbose_name="Codigo")),
                (
                    "nom_servicio",
                    models.CharField(max_length=255, verbose_name="Detalle"),
                ),
            ],
            options={
                "verbose_name": "Servicio_Material_Biblio",
                "verbose_name_plural": "Servicios_Materiales_Biblios",
                "db_table": "servicio_material_biblio",
            },
        ),
        migrations.CreateModel(
            name="TipoMaterialBiblio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_material",
                    models.CharField(max_length=255, verbose_name="Tipo_Material"),
                ),
            ],
            options={
                "verbose_name": "Tipo_Material_Biblio",
                "verbose_name_plural": "Tipos_Materiales_Biblios",
                "db_table": "tipo_material_biblio",
            },
        ),
        migrations.CreateModel(
            name="Turnos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_turno", models.CharField(max_length=50, verbose_name="Turno")),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "db_table": "turno",
            },
        ),
        migrations.CreateModel(
            name="InformePedagogico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("total", models.IntegerField(verbose_name="Total")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe_Pedagogico",
                "verbose_name_plural": "Informes_Pedagogicos",
                "db_table": "informe_pedagogico",
            },
        ),
        migrations.CreateModel(
            name="ProcesosTecnicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "procesos",
                    models.CharField(
                        choices=[
                            ("SELLADOS", "SELLADOS"),
                            ("INVENTARIADOS", "INVENTARIADOS"),
                            ("CLASIFICADOS", "CLASIFICADOS"),
                            ("CATALOGADOS", "CATALOGADOS"),
                            ("RESTAURADOS", "RESTAURADOS"),
                            ("BAJAS", "BAJAS"),
                        ],
                        max_length=255,
                        verbose_name="Procesos",
                    ),
                ),
                ("total", models.IntegerField(verbose_name="Total")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.tipomaterialbiblio",
                        verbose_name="Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso_Tecnico",
                "verbose_name_plural": "Procesos_Tecnicos",
                "db_table": "proceso_tecnico",
            },
        ),
        migrations.CreateModel(
            name="ServicioReferenciaVirtual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("total", models.IntegerField(verbose_name="Total")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "turnos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.turnos",
                        verbose_name="Turnos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio_Referencia_Virtual",
                "verbose_name_plural": "Servicios_Referencias_Virtuales",
                "db_table": "servicio_referencia_virtual",
            },
        ),
        migrations.CreateModel(
            name="ServicioReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("varones", models.IntegerField(verbose_name="Varones")),
                ("total", models.IntegerField(verbose_name="Total")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "turnos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.turnos",
                        verbose_name="Turnos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio_Referencia",
                "verbose_name_plural": "Servicios_Referencias",
                "db_table": "servicio_referencia",
            },
        ),
        migrations.CreateModel(
            name="ServicioPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "instalacion",
                    models.CharField(
                        choices=[
                            ("SALA", "SALA"),
                            ("AULA", "AULA"),
                            ("DOMICILIO", "DOMICILIO"),
                            ("OTRAS", "OTRAS"),
                        ],
                        max_length=255,
                        verbose_name="Instalacion",
                    ),
                ),
                ("total", models.IntegerField(verbose_name="Total")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "turnos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.turnos",
                        verbose_name="Turnos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio_Prestamo",
                "verbose_name_plural": "Servicios_Prestamos",
                "db_table": "servicio_prestamo",
            },
        ),
        migrations.CreateModel(
            name="MaterialBibliografico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "t_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.tipomaterialbiblio",
                        verbose_name="Material",
                    ),
                ),
                (
                    "turnos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.turnos",
                        verbose_name="Turnos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material_Bibliografico",
                "verbose_name_plural": "Materiales_Bibliograficos",
                "db_table": "material_bibliografico",
            },
        ),
    ]
