# Generated by Django 5.1.1 on 2025-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviciosmatbiblio",
            name="cod_nomservicio",
            field=models.IntegerField(default=0, verbose_name="CodNom"),
        ),
    ]
