# Generated by Django 5.1.1 on 2025-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0002_serviciosmatbiblio_cod_nomservicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escuelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("nom_est", models.CharField(max_length=255, verbose_name="Nombre")),
                ("oferta", models.CharField(max_length=255, verbose_name="Ofertas")),
                (
                    "region_loc",
                    models.CharField(max_length=255, verbose_name="Regional"),
                ),
                (
                    "localidad",
                    models.CharField(max_length=255, verbose_name="Localidad"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=255, verbose_name="Departamento"),
                ),
            ],
            options={
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
                "db_table": "public.cueanexo_nomest_ofertas",
                "managed": False,
            },
        ),
    ]
