# Generated by Django 5.1.1 on 2025-02-25 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0003_escuelas"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="escuelas",
            table="cueanexo_nomest_ofertas",
        ),
    ]
