# Generated by Django 5.1.1 on 2025-03-01 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0004_alter_escuelas_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerarInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                (
                    "meses",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "annos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "f_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                ("estado", models.CharField(default="GENERADO", verbose_name="Estado")),
                ("f_envio", models.DateTimeField(verbose_name="Fecha Envío")),
            ],
            options={
                "verbose_name": "GenerarInforme",
                "verbose_name_plural": "GenerarInformes",
                "db_table": "generar_informe",
            },
        ),
    ]
