# Generated by Django 5.1.1 on 2025-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0005_generarinforme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generarinforme",
            name="f_envio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Envío"
            ),
        ),
    ]
