# Generated by Django 5.1.1 on 2025-03-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0006_alter_generarinforme_f_envio"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanillasAnexas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("mes", models.CharField(max_length=25, verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.serviciosmatbiblio",
                        verbose_name="Servicios",
                    ),
                ),
            ],
            options={
                "verbose_name": "PlanillaAnexa",
                "verbose_name_plural": "PlanillasAnexas",
                "db_table": "planilla_anexa",
            },
        ),
    ]
