# Generated by Django 5.1.1 on 2025-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0007_planillasanexas"),
    ]

    operations = [
        migrations.AddField(
            model_name="aguapey",
            name="observaciones",
            field=models.TextField(
                default=1, max_length=255, verbose_name="Observaciones"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aguapey",
            name="total_usuarios",
            field=models.IntegerField(default=1, verbose_name="Total Usuarios"),
            preserve_default=False,
        ),
    ]
