# Generated by Django 5.1.1 on 2025-03-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0008_aguapey_observaciones_aguapey_total_usuarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinoFondos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_fondo", models.IntegerField(verbose_name="Codigo")),
                ("nom_fondo", models.CharField(max_length=255, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "DestinoFondo",
                "verbose_name_plural": "DestinosFondos",
                "db_table": "destino_fondos",
            },
        ),
        migrations.CreateModel(
            name="RegistroDestinoFondos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
                ("mes", models.CharField(max_length=25, verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripcion"),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.destinofondos",
                        verbose_name="Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "RegistroDestinoFondo",
                "verbose_name_plural": "RegistroDestinosFondos",
                "db_table": "registro_destino_fondos",
            },
        ),
    ]
