# Generated by Django 5.1.1 on 2025-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0009_destinofondos_registrodestinofondos"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocentePonMensual",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=50)),
                ("cuof", models.CharField(max_length=50)),
                ("cuof_anexo", models.CharField(max_length=50)),
                ("ptaid", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=100)),
                ("nombres", models.CharField(max_length=100)),
                ("n_doc", models.CharField(max_length=20)),
                ("cuil", models.CharField(max_length=20)),
                ("f_nac", models.DateField()),
                ("sit_rev", models.CharField(max_length=50)),
                ("nivel", models.CharField(max_length=50)),
                ("ceic", models.CharField(max_length=50)),
                ("denom_cargo", models.CharField(max_length=100)),
                ("f_desde", models.DateField()),
                ("f_hasta", models.DateField()),
                ("regional", models.CharField(max_length=100)),
                ("localidad", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Docente_Mensual",
                "verbose_name_plural": "Docentes_Mensuales",
                "db_table": "cenpe.docentespon_mensual_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NoDocentesMensual",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cueanexo", models.CharField(max_length=9)),
                ("cuof", models.CharField(max_length=10)),
                ("cuof_anexo", models.CharField(blank=True, max_length=10, null=True)),
                ("ptaid", models.CharField(max_length=20)),
                ("apellidos", models.CharField(max_length=100)),
                ("nombres", models.CharField(max_length=100)),
                ("ndoc", models.CharField(max_length=15)),
                ("cuil", models.CharField(max_length=15)),
                ("f_nac", models.DateField(blank=True, null=True)),
                ("denom_cargo", models.CharField(max_length=100)),
                ("categ", models.CharField(max_length=50)),
                ("gpo", models.CharField(max_length=50)),
                ("apart", models.CharField(max_length=50)),
                ("f_desde", models.DateField(blank=True, null=True)),
                ("f_hasta", models.DateField(blank=True, null=True)),
                ("regional", models.CharField(max_length=100)),
                ("localidad", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "No_Docente_Mensual",
                "verbose_name_plural": "No_Docentes_Mensuales",
                "db_table": "cenpe.nodocentes_mensual_view",
                "managed": False,
            },
        ),
    ]
