# Generated by Django 5.1.1 on 2025-03-05 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0010_docenteponmensual_nodocentesmensual"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="docenteponmensual",
            table="docentespon_mensual_view",
        ),
        migrations.AlterModelTable(
            name="nodocentesmensual",
            table="nodocentes_mensual_view",
        ),
    ]
