# Generated by Django 5.1.1 on 2025-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0011_alter_docenteponmensual_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocalLicDocentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ptaid", models.CharField(blank=True, max_length=9, null=True)),
                ("cuil", models.CharField(blank=True, max_length=11, null=True)),
                ("ptatipo", models.CharField(blank=True, max_length=255, null=True)),
                ("lic_desde", models.DateField(blank=True, null=True)),
                ("lic_hasta", models.DateField(blank=True, null=True)),
                ("desc_lic", models.CharField(blank=True, max_length=255, null=True)),
                ("cuof", models.CharField(blank=True, max_length=7, null=True)),
                ("cuof_anexo", models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                "verbose_name": "Focal_Lic_Docente",
                "verbose_name_plural": "Focales_Lic_Docentes",
                "db_table": "focal_lic_docentes",
                "managed": False,
            },
        ),
    ]
