# Generated by Django 5.1.1 on 2025-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0012_focallicdocentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aguapey",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="asistenciausuarios",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="generarinforme",
            name="meses",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="informepedagogico",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="institucionesprestaservicios",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="materialbibliografico",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="procesostecnicos",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="procesostecnicos",
            name="procesos",
            field=models.CharField(
                choices=[
                    ("SELLADOS", "SELLADOS"),
                    ("INVENTARIADOS", "INVENTARIADOS"),
                    ("CLASIFICADOS", "CLASIFICADOS"),
                    ("CATALOGADOS", "CATALOGADOS"),
                    ("RESTAURADOS", "RESTAURADOS"),
                    ("RESTAURADOS", "RESTAURADOS"),
                    ("BAJAS", "BAJAS"),
                ],
                max_length=255,
                verbose_name="Procesos",
            ),
        ),
        migrations.AlterField(
            model_name="servicioprestamo",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="servicioreferencia",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="servicioreferenciavirtual",
            name="mes",
            field=models.CharField(
                choices=[
                    ("ABRIL", "ABRIL"),
                    ("JULIO", "JULIO"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=25,
                verbose_name="Mes",
            ),
        ),
    ]
