# Generated by Django 5.1.1 on 2025-06-11 19:19

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0013_alter_aguapey_mes_alter_asistenciausuarios_mes_and_more"),
        ("oplectura", "0012_alter_regevaluacionfluidezlectora_comprension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibliotecariosCue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="cueanexo")),
                ("cuil", models.CharField(max_length=11, verbose_name="cuil")),
                (
                    "t_doc",
                    models.CharField(
                        choices=[("DNI", "DNI"), ("LC", "LC"), ("LE", "LE")],
                        max_length=3,
                        verbose_name="t_doc",
                    ),
                ),
                ("n_doc", models.CharField(max_length=8, verbose_name="n_doc")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="apellidos"),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="nombres")),
                ("f_nac", models.DateField(verbose_name="f_nac")),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("BIBLIOTECARIO", "BIBLIOTECARIO"),
                            ("DIRECTOR BIBLIOTECA 1RA", "DIRECTOR BIBLIOTECA 1RA"),
                            ("DIRECTOR BIBLIOTECA 2DA", "DIRECTOR BIBLIOTECA 2DA"),
                            ("DIRECTOR BIBLIOTECA 3RA", "DIRECTOR BIBLIOTECA 3RA"),
                            (
                                "DIRECTOR BIBLIOTECA CENTRAL",
                                "DIRECTOR BIBLIOTECA CENTRAL",
                            ),
                            ("VICEDIRECTOR BIBLIOTECA", "BICEDIRECTOR BIBLIOTECA"),
                        ],
                        max_length=255,
                        verbose_name="cargo",
                    ),
                ),
                (
                    "situacion_revista",
                    models.CharField(
                        choices=[
                            ("TITULAR", "TITULAR"),
                            ("INTERINO", "INTERINO"),
                            ("SUPLENTE", "SUPLENTE"),
                            ("CONTRATADO", "CONTRATADO"),
                        ],
                        max_length=255,
                        verbose_name="situacion_revista",
                    ),
                ),
                ("f_ingreso", models.DateField(verbose_name="f_ingreso")),
                (
                    "f_hasta",
                    models.DateField(
                        default=datetime.date(2039, 12, 31), verbose_name="f_hasta"
                    ),
                ),
                (
                    "cuof",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="cuof"
                    ),
                ),
                (
                    "cuof_anexo",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="cuof_anexo"
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ABRIL", "ABRIL"),
                            ("JULIO", "JULIO"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        max_length=25,
                        verbose_name="mes",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2025)],
                        verbose_name="anio",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplectura.turno",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bibliotecario_Cue",
                "verbose_name_plural": "Bibliotecarios_Cues",
                "db_table": "bibliotecarios_cue",
            },
        ),
    ]
