# Generated by Django 5.1.1 on 2025-06-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0014_bibliotecarioscue"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiposLicenciasPermisos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_licencia",
                    models.CharField(max_length=255, verbose_name="Tipo de Licencia"),
                ),
            ],
            options={
                "verbose_name": "Tipo_Licencia_Permiso",
                "verbose_name_plural": "Tipos_Licencias_Permisos",
                "db_table": "tipos_licencias_permisos",
            },
        ),
        migrations.CreateModel(
            name="TiposSituacionLaboral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_situacion",
                    models.CharField(
                        max_length=255, verbose_name="Tipo de Situación Laboral"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo_Situacion_Laboral",
                "verbose_name_plural": "Tipos_Situaciones_Laborales",
                "db_table": "tipos_situacion_laboral",
            },
        ),
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="f_desde_lic",
            field=models.DateField(blank=True, null=True, verbose_name="f_desde_lic"),
        ),
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="f_hasta_lic",
            field=models.DateField(blank=True, null=True, verbose_name="f_hasta_lic"),
        ),
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="observaciones",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="observaciones"
            ),
        ),
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="licencia_permiso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.tiposlicenciaspermisos",
                verbose_name="Licencia_Permiso",
            ),
        ),
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="situacion_laboral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.tipossituacionlaboral",
                verbose_name="Situacion_Laboral",
            ),
        ),
    ]
