# Generated by Django 5.2.8 on 2026-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0015_tiposlicenciaspermisos_tipossituacionlaboral_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaUsuariosResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("nivel", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=50)),
                ("total", models.IntegerField()),
                ("varones", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_asistencia_usuarios_resumen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InformePedagogicoResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("nom_servicio", models.CharField(max_length=255)),
                ("varones_total", models.IntegerField()),
                ("total_total", models.IntegerField()),
            ],
            options={
                "db_table": "v_informe_pedagogico_resumen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InstitucionesServiciosResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("escuela", models.CharField(max_length=255)),
                ("matricula", models.IntegerField()),
                ("docentes", models.IntegerField()),
                ("matricdisc", models.IntegerField()),
                ("etnia", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_instituciones_servicios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProcesosTecnicosResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("nom_material", models.CharField(max_length=150)),
                ("procesos", models.CharField(max_length=150)),
                ("total", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_procesos_tecnicos_resumen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VMaterialBiblioDynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("cod_servicio", models.IntegerField()),
                ("nom_servicio", models.CharField(max_length=255)),
                ("nom_turno", models.CharField(max_length=255)),
                ("materiales", models.JSONField()),
                ("total_general", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_material_biblio_dynamic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VServicioReferenciaResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("cod_servicio", models.IntegerField()),
                ("nom_servicio", models.CharField(max_length=255)),
                ("nom_turno", models.CharField(max_length=255)),
                ("total_v", models.IntegerField()),
                ("total_t", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_servicio_referencia_resumen",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VServicioReferenciaVirtualResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=20)),
                ("mes", models.CharField(max_length=20)),
                ("anio", models.IntegerField()),
                ("cod_servicio", models.IntegerField()),
                ("nom_servicio", models.CharField(max_length=255)),
                ("nom_turno", models.CharField(max_length=255)),
                ("total_v", models.IntegerField()),
                ("total_t", models.IntegerField()),
            ],
            options={
                "db_table": "pem.v_servicio_referencia_virtual_resumen",
                "managed": False,
            },
        ),
    ]
