# Generated by Django 5.2.8 on 2026-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biblioteca",
            "0016_asistenciausuariosresumen_informepedagogicoresumen_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodestinofondos",
            name="cantidad",
            field=models.IntegerField(default=1, verbose_name="Cantidad"),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="vmaterialbibliodynamic",
            table="pem.v_material_bibliografico_resumen",
        ),
        migrations.AlterModelTable(
            name="vservicioreferenciaresumen",
            table="v_material_biblio_dynamic",
        ),
        migrations.AlterModelTable(
            name="vservicioreferenciavirtualresumen",
            table="v_servicio_referencia_virtual_resumen",
        ),
    ]
