# Generated by Django 5.2.8 on 2026-04-21 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0017_registrodestinofondos_cantidad_and_more"),
        ("oplectura", "0012_alter_regevaluacionfluidezlectora_comprension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="f_desde_lic",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="f_hasta_lic",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="observaciones",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="situacion_laboral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.tipossituacionlaboral",
            ),
        ),
        migrations.AddConstraint(
            model_name="aguapey",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio"), name="unique_aguapey"
            ),
        ),
        migrations.AddConstraint(
            model_name="asistenciausuarios",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "nivel", "usuario"),
                name="unique_asistencia_usuarios",
            ),
        ),
        migrations.AddConstraint(
            model_name="bibliotecarioscue",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "n_doc", "mes", "anio"),
                name="unique_bibliotecario_cue",
            ),
        ),
        migrations.AddConstraint(
            model_name="informepedagogico",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "servicio"),
                name="unique_informe_pedagogico",
            ),
        ),
        migrations.AddConstraint(
            model_name="institucionesprestaservicios",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "escuela"),
                name="unique_institucion_servicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialbibliografico",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "servicio", "turnos", "t_material"),
                name="unique_material_bibliografico",
            ),
        ),
        migrations.AddConstraint(
            model_name="procesostecnicos",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "material", "procesos"),
                name="unique_procesos_tecnicos",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrodestinofondos",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "destino"),
                name="unique_registro_destino_fondos",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicioprestamo",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "servicio", "turnos", "instalacion"),
                name="unique_servicio_prestamo",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicioreferencia",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "servicio", "turnos"),
                name="unique_servicio_referencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicioreferenciavirtual",
            constraint=models.UniqueConstraint(
                fields=("cueanexo", "mes", "anio", "servicio", "turnos"),
                name="unique_servicio_referencia_virtual",
            ),
        ),
        migrations.AlterModelTable(
            name="aguapey",
            table="aguapey",
        ),
    ]
