# Generated by Django 5.2.8 on 2026-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0018_alter_bibliotecarioscue_f_desde_lic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aguapey",
            name="total_base",
            field=models.PositiveIntegerField(verbose_name="Total Base"),
        ),
        migrations.AlterField(
            model_name="aguapey",
            name="total_mes",
            field=models.PositiveIntegerField(verbose_name="Total Mes"),
        ),
        migrations.AlterField(
            model_name="aguapey",
            name="total_usuarios",
            field=models.PositiveIntegerField(verbose_name="Total Usuarios"),
        ),
        migrations.AlterField(
            model_name="informepedagogico",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="informepedagogico",
            name="varones",
            field=models.PositiveIntegerField(verbose_name="Varones"),
        ),
        migrations.AlterField(
            model_name="institucionesprestaservicios",
            name="docentes",
            field=models.PositiveIntegerField(verbose_name="Docentes"),
        ),
        migrations.AlterField(
            model_name="institucionesprestaservicios",
            name="etnia",
            field=models.PositiveIntegerField(verbose_name="Etnia"),
        ),
        migrations.AlterField(
            model_name="institucionesprestaservicios",
            name="matricdisc",
            field=models.PositiveIntegerField(verbose_name="Discapacidad"),
        ),
        migrations.AlterField(
            model_name="institucionesprestaservicios",
            name="matricula",
            field=models.PositiveIntegerField(verbose_name="Matricula"),
        ),
        migrations.AlterField(
            model_name="materialbibliografico",
            name="cantidad",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="procesostecnicos",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="registrodestinofondos",
            name="cantidad",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="servicioprestamo",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="servicioreferencia",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="servicioreferencia",
            name="varones",
            field=models.PositiveIntegerField(verbose_name="Varones"),
        ),
        migrations.AlterField(
            model_name="servicioreferenciavirtual",
            name="total",
            field=models.PositiveIntegerField(verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="servicioreferenciavirtual",
            name="varones",
            field=models.PositiveIntegerField(verbose_name="Varones"),
        ),
    ]
