# Generated by Django 5.2.8 on 2026-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biblioteca",
            "0019_alter_aguapey_total_base_alter_aguapey_total_mes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generarinforme",
            name="f_rehab",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Reapertura"
            ),
        ),
        migrations.AddField(
            model_name="generarinforme",
            name="rehab",
            field=models.BooleanField(default=False, verbose_name="Reapertura"),
        ),
    ]
