# Generated by Django 5.2.8 on 2026-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0020_generarinforme_f_rehab_generarinforme_rehab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("BIBLIOTECARIO", "BIBLIOTECARIO"),
                    ("DIRECTOR BIBLIOTECA 1RA", "DIRECTOR BIBLIOTECA 1RA"),
                    ("DIRECTOR BIBLIOTECA 2DA", "DIRECTOR BIBLIOTECA 2DA"),
                    ("DIRECTOR BIBLIOTECA 3RA", "DIRECTOR BIBLIOTECA 3RA"),
                    ("DIRECTOR BIBLIOTECA CENTRAL", "DIRECTOR BIBLIOTECA CENTRAL"),
                    ("VICEDIRECTOR BIBLIOTECA", "VICEDIRECTOR BIBLIOTECA"),
                ],
                max_length=255,
                verbose_name="cargo",
            ),
        ),
    ]
