# Generated by Django 5.2.17 on 2026-09-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0021_alter_bibliotecarioscue_cargo"),
        ("oplectura", "0012_alter_regevaluacionfluidezlectora_comprension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="cargo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIBLIOTECARIO", "BIBLIOTECARIO"),
                    ("DIRECTOR BIBLIOTECA 1RA", "DIRECTOR BIBLIOTECA 1RA"),
                    ("DIRECTOR BIBLIOTECA 2DA", "DIRECTOR BIBLIOTECA 2DA"),
                    ("DIRECTOR BIBLIOTECA 3RA", "DIRECTOR BIBLIOTECA 3RA"),
                    ("DIRECTOR BIBLIOTECA CENTRAL", "DIRECTOR BIBLIOTECA CENTRAL"),
                    ("VICEDIRECTOR BIBLIOTECA", "VICEDIRECTOR BIBLIOTECA"),
                ],
                max_length=255,
                null=True,
                verbose_name="cargo",
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="f_hasta",
            field=models.DateField(blank=True, null=True, verbose_name="f_hasta"),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="f_ingreso",
            field=models.DateField(blank=True, null=True, verbose_name="f_ingreso"),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="f_nac",
            field=models.DateField(blank=True, null=True, verbose_name="f_nac"),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="situacion_revista",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TITULAR", "TITULAR"),
                    ("INTERINO", "INTERINO"),
                    ("SUPLENTE", "SUPLENTE"),
                    ("CONTRATADO", "CONTRATADO"),
                ],
                max_length=255,
                null=True,
                verbose_name="situacion_revista",
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="t_doc",
            field=models.CharField(
                blank=True,
                choices=[("DNI", "DNI"), ("LC", "LC"), ("LE", "LE")],
                max_length=3,
                null=True,
                verbose_name="t_doc",
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oplectura.turno",
                verbose_name="turno",
            ),
        ),
    ]
