# Generated by Django 5.2.17 on 2026-09-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0022_alter_bibliotecarioscue_cargo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliotecarioscue",
            name="turno_bnh",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="turno_bnh"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="cargo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="cargo"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecarioscue",
            name="situacion_revista",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="situacion_revista"
            ),
        ),
    ]
