# Generated by Django 5.2.8 on 2026-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_dispositivousuario_email_enviado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivousuario",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
    ]
