# Generated by Django 5.2.8 on 2026-03-05 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapaUnicaOfertas",
            fields=[
                (
                    "cueanexo",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nom_est", models.CharField(max_length=255)),
                ("region_loc", models.IntegerField()),
                ("ref_loc", models.CharField(max_length=255)),
                ("localidad", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
                "db_table": "v_capa_unica_ofertas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sla_horas", models.IntegerField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=255)),
                ("consulta_id", models.IntegerField(null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9)),
                ("escuela", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=20)),
                ("asunto", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En proceso"),
                            ("respondida", "Respondida"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "gestor_asignado",
                    models.CharField(
                        blank=True, db_index=True, max_length=9, null=True
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="consultasge.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="consultas/")),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="consultasge.consulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="consultasge.consulta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["region", "estado"], name="consultasge_region_5670df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["fecha_limite"], name="consultasge_fecha_l_46c2e7_idx"
            ),
        ),
    ]
