# Generated by Django 5.2.8 on 2026-03-02 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capaunicaofertas",
            options={
                "managed": False,
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
            },
        ),
    ]
