# Generated by Django 5.2.8 on 2026-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="gestor_asignado",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
    ]
