# Generated by Django 5.2.8 on 2026-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0002_alter_consulta_gestor_asignado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjunto",
            name="archivo",
            field=models.FileField(upload_to="consultas/adjuntos"),
        ),
    ]
