# Generated by Django 5.2.8 on 2026-03-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0002_alter_capaunicaofertas_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consultasge.categoria",
            ),
        ),
    ]
