# Generated by Django 5.2.8 on 2026-03-05 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0003_alter_adjunto_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjunto",
            name="fecha_subida",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adjunto",
            name="consulta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjuntos",
                to="consultasge.consulta",
            ),
        ),
    ]
