# Generated by Django 5.2.8 on 2026-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0003_alter_consulta_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="region",
            field=models.CharField(max_length=20),
        ),
    ]
