# Generated by Django 5.2.8 on 2026-03-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0004_adjunto_fecha_subida_alter_adjunto_consulta"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjunto",
            name="respuesta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjuntos_respuesta",
                to="consultasge.respuesta",
            ),
        ),
        migrations.AlterField(
            model_name="adjunto",
            name="consulta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjuntos",
                to="consultasge.consulta",
            ),
            preserve_default=False,
        ),
    ]
