# Generated by Django 5.2.8 on 2026-03-03 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0004_alter_consulta_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="fecha_cierre",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("respondida", "Respondida"),
                    ("cerrada", "Cerrada"),
                ],
                db_index=True,
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha_limite",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha_respuesta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="region",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["region", "estado"], name="consultasge_region_5670df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["region", "fecha_limite"], name="consultasge_region_70e84c_idx"
            ),
        ),
    ]
