# Generated by Django 5.2.8 on 2026-03-23 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0005_adjunto_respuesta_alter_adjunto_consulta"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="capaunicaofertas",
            table="v_capa_unica_ofertas_ant",
        ),
    ]
