# Generated by Django 5.2.8 on 2026-03-04 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0005_consulta_fecha_cierre_alter_consulta_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="consulta",
            name="consultasge_region_70e84c_idx",
        ),
        migrations.AlterField(
            model_name="consulta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("respondida", "Respondida"),
                    ("cerrada", "Cerrada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha_limite",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="region",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["fecha_limite"], name="consultasge_fecha_l_46c2e7_idx"
            ),
        ),
    ]
