# Generated by Django 5.2.8 on 2026-05-05 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0006_alter_capaunicaofertas_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="capaunicaofertas",
            table="public.v_capa_unica_ofertas_ant",
        ),
    ]
