# Generated by Django 5.2.8 on 2026-05-05 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultasge", "0007_alter_capaunicaofertas_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="capaunicaofertas",
            table="v_capa_unica_ofertas_ant",
        ),
    ]
