# Generated by Django 5.2.8 on 2026-05-08 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnhpersonas", "0002_alter_personas_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codareastelefonos",
            options={
                "managed": False,
                "ordering": ["codigo", "localidad"],
                "verbose_name": "Codigo Area",
                "verbose_name_plural": "Codigos Areas",
            },
        ),
        migrations.AlterModelOptions(
            name="localidades",
            options={
                "managed": False,
                "ordering": ["descrip_localidad"],
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
            },
        ),
        migrations.AddField(
            model_name="personas",
            name="codigo_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.codareastelefonos",
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="bnhpersonas.localidades",
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6,8}$",
                        message="Ingrese solo el número local (6 a 8 dígitos, sin código de área)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personas",
            name="telefono_normalizado",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name="personas",
            index=models.Index(
                fields=["telefono_normalizado"], name="personas_telefon_948765_idx"
            ),
        ),
    ]
