# Generated by Django 5.2.8 on 2026-03-26 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("url", models.CharField(blank=True, max_length=200)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("categorias", models.JSONField(blank=True, default=list)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("clave", models.CharField(blank=True, max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
    ]
