# Generated by Django 5.2.8 on 2025-12-03 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                (
                    "comunidad_indigena",
                    models.CharField(
                        choices=[
                            ("QOM", "Qom (Toba)"),
                            ("MOQOIT", "Moqoit (Mocoví)"),
                            ("WICHI", "Wichí (Mataco)"),
                            ("NINGUNA", "Ninguna / No Aplica"),
                        ],
                        default="NINGUNA",
                        max_length=11,
                    ),
                ),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[
                            ("SI", "Sí, la persona tiene una discapacidad"),
                            ("NO", "No aplica"),
                        ],
                        default="NO",
                    ),
                ),
            ],
            options={
                "db_table": "alumnos",
            },
        ),
        migrations.CreateModel(
            name="Grado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("cueanexo", models.CharField(max_length=9)),
                (
                    "nombre_grado",
                    models.CharField(
                        choices=[
                            ("2do Año/Grado", "2do Grado"),
                            ("3er Año/Grado", "3er Grado"),
                        ],
                        default="2do Año/Grado",
                        max_length=13,
                    ),
                ),
            ],
            options={
                "db_table": "grados",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionFluidezLectora",
            fields=[
                ("cantidad_palabras_leidas", models.IntegerField(default=0, null=True)),
                (
                    "pregunta_1",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_2",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_3",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_4",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_5",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_6",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "asistencia",
                    models.CharField(
                        choices=[("PRESENTE", "Presente"), ("AUSENTE", "Ausente")],
                        default="AUSENTE",
                    ),
                ),
                ("encargado_carga", models.CharField(max_length=9)),
                (
                    "alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="evaluaciones_educativas.alumno",
                    ),
                ),
            ],
            options={
                "db_table": "evaluaciones_fluidez_lectora",
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "seccion",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("Z", "Z"),
                        ],
                        default="UNICO",
                        max_length=5,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MAÑANA", "Mañana"),
                            ("TARDE", "Tarde"),
                            ("DOBLE", "Doble"),
                        ],
                        default="MANANA",
                        max_length=6,
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones_educativas.grado",
                    ),
                ),
            ],
            options={
                "db_table": "secciones",
                "unique_together": {("seccion", "grado", "turno")},
            },
        ),
        migrations.AddField(
            model_name="alumno",
            name="seccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluaciones_educativas.seccion",
            ),
        ),
    ]
