# Generated by Django 5.2.8 on 2025-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="comunidad_indigena",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QOM", "Qom"),
                    ("MOQOIT", "Moqoit"),
                    ("WICHI", "Wichí"),
                    ("NINGUNA", "Ninguna"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="discapacidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SI", "Sí, la persona tiene una discapacidad"),
                    ("NO", "Ninguna"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_5",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionfluidezlectora",
            name="pregunta_6",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("NORESPONDE", "NoResponde"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="seccion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("Z", "Z"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="seccion",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[("MAÑANA", "Mañana"), ("TARDE", "Tarde"), ("DOBLE", "Doble")],
                max_length=6,
            ),
        ),
    ]
