# Generated by Django 5.2.13 on 2026-05-12 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0002_alter_alumno_comunidad_indigena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comunidad_indigena', models.CharField(choices=[('QOM', 'Qom'), ('MOQOIT', 'Moqoit'), ('WICHI', 'Wichí'), ('NINGUNA', 'Ninguna')], max_length=11)),
                ('discapacidad', models.CharField(choices=[('SI', 'Sí, la persona tiene una discapacidad'), ('NO', 'Ninguna')])),
            ],
            options={
                'db_table': '"diagnostico_2026"."alumnos"',
            },
        ),
        migrations.CreateModel(
            name='Establecimientos2026',
            fields=[
                ('cueanexo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('escuela', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"diagnostico_2026"."establecimientos"',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDiagnostica2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A')),
                ('asistencia', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='AUSENTE')),
                ('encargado_carga', models.CharField(default='DIRECTOR', max_length=9)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.alumno2026')),
            ],
            options={
                'db_table': '"diagnostico_2026"."evaluaciones"',
            },
        ),
        migrations.CreateModel(
            name='Año2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cueanexo', models.CharField(max_length=9)),
                ('nombre_año', models.CharField(choices=[('2do Año', '2do Año')], default='2do Año', max_length=13)),
                ('titulacion', models.CharField(max_length=15)),
                ('Establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.establecimientos2026')),
            ],
            options={
                'db_table': '"diagnostico_2026"."años"',
                'unique_together': {('nombre_año', 'cueanexo')},
            },
        ),
        migrations.CreateModel(
            name='Lengua2026',
            fields=[
                ('evaluaciondiagnostica2026_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluaciones_educativas.evaluaciondiagnostica2026')),
                ('pregunta_1', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_3', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_4', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_5', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_6', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_7', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_8', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_9', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_10', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_11_1', models.CharField(choices=[('2', '2'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_11_2', models.CharField(choices=[('5,65', '5,65'), ('2,80', '2,80'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_11_3', models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_11_4', models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_12', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_13', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_14', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_15', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_16', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_17', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_18', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_19', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_20', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_21', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_22_1', models.CharField(choices=[('7,65', '7,65'), ('3,80', '3,80'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_22_2', models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_22_3', models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True)),
            ],
            options={
                'db_table': '"diagnostico_2026"."evaluaciones_lengua"',
            },
            bases=('evaluaciones_educativas.evaluaciondiagnostica2026',),
        ),
        migrations.CreateModel(
            name='Matematica2026',
            fields=[
                ('evaluaciondiagnostica2026_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evaluaciones_educativas.evaluaciondiagnostica2026')),
                ('pregunta_2', models.CharField(choices=[('6', '6'), ('4', '4'), ('2', '2'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_1', models.CharField(choices=[('6,5', '6,5'), ('3,25', '3,25'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_3', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_4', models.CharField(choices=[('6', '6'), ('3', '3'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_5', models.CharField(choices=[('7', '7'), ('3,5', '3,5'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_6', models.CharField(choices=[('8', '8'), ('4', '4'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_7', models.CharField(choices=[('10', '10'), ('5', '5'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_8', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_9', models.CharField(choices=[('11', '11'), ('5,50', '5,50'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_10', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True)),
                ('pregunta_11', models.CharField(choices=[('11,5', '11,5'), ('7', '7'), ('3,5', '3,5'), ('0', '0')], max_length=10, null=True)),
                ('pregunta_12', models.CharField(choices=[('9', '9'), ('4,5', '4,5'), ('0', '0')], max_length=10, null=True)),
            ],
            options={
                'db_table': '"diagnostico_2026"."evaluaciones_matematica"',
            },
            bases=('evaluaciones_educativas.evaluaciondiagnostica2026',),
        ),
        migrations.CreateModel(
            name='Seccion2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seccion', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=5)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCTURNO', 'Nocturno')], max_length=9)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.año2026')),
            ],
            options={
                'db_table': '"diagnostico_2026"."secciones"',
                'unique_together': {('seccion', 'año', 'turno')},
            },
        ),
        migrations.AddField(
            model_name='alumno2026',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.seccion2026'),
        ),
    ]
