# Generated by Django 5.2.13 on 2026-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0003_alumno2026_establecimientos2026_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion2026',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCTURNO', 'Nocturno')], max_length=11),
        ),
    ]
