# Generated by Django 5.2.13 on 2026-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0003_alumno2026_establecimientos2026_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion2026',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCTURNO', 'Nocturno')], default=None, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_10',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_11_1',
            field=models.CharField(choices=[('2', '2'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_11_2',
            field=models.CharField(choices=[('5,65', '5,65'), ('2,80', '2,80'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_11_3',
            field=models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_11_4',
            field=models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_12',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_13',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_14',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_15',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_16',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_17',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_18',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_19',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_20',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_21',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_22_1',
            field=models.CharField(choices=[('7,65', '7,65'), ('3,80', '3,80'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_22_2',
            field=models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_22_3',
            field=models.CharField(choices=[('2,30', '2,30'), ('1,15', '1,15'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_3',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_4',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_5',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_6',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_7',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_8',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lengua2026',
            name='pregunta_9',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_1',
            field=models.CharField(choices=[('6,5', '6,5'), ('3,25', '3,25'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_10',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_11',
            field=models.CharField(choices=[('11,5', '11,5'), ('7', '7'), ('3,5', '3,5'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_12',
            field=models.CharField(choices=[('9', '9'), ('4,5', '4,5'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_2',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('2', '2'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_3',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_4',
            field=models.CharField(choices=[('6', '6'), ('3', '3'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_5',
            field=models.CharField(choices=[('7', '7'), ('3,5', '3,5'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_6',
            field=models.CharField(choices=[('8', '8'), ('4', '4'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_7',
            field=models.CharField(choices=[('10', '10'), ('5', '5'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_8',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OMITÍO', 'OMITÍO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matematica2026',
            name='pregunta_9',
            field=models.CharField(choices=[('11', '11'), ('5,50', '5,50'), ('0', '0')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seccion2026',
            name='seccion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=5),
        ),
    ]
