# Generated by Django 5.2.13 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0004_alter_seccion2026_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lengua2026',
            name='correcion_escritura',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='lengua2026',
            name='correcion_extraccion',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='lengua2026',
            name='correcion_interpretacion',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='lengua2026',
            name='correcion_reflexion',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='lengua2026',
            name='total_puntaje',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='matematica2026',
            name='correcion_comunicacion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matematica2026',
            name='correcion_reconocimiento',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matematica2026',
            name='correcion_resolucion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matematica2026',
            name='total_puntaje',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
