# Generated by Django 5.2.13 on 2026-05-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0004_seccion2026_turno_alter_lengua2026_pregunta_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondiagnostica2026',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.alumno2026'),
        ),
    ]
