# Generated by Django 5.2.13 on 2026-05-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0005_lengua2026_correcion_escritura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno2026',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.seccion2026'),
        ),
    ]
