# Generated by Django 5.2.13 on 2026-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0006_alter_alumno2026_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno2026',
            name='comunidad_indigena',
            field=models.CharField(choices=[('QOM', 'Qom'), ('MOQOIT', 'Moqoit'), ('WICHI', 'Wichí'), ('NINGUNA', 'Ninguna')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='alumno2026',
            name='discapacidad',
            field=models.CharField(choices=[('SI', 'Sí, la persona tiene una discapacidad'), ('NO', 'Ninguna')], null=True),
        ),
    ]
