# Generated by Django 5.2.13 on 2026-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0007_alter_alumno2026_comunidad_indigena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno2026',
            name='dni',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
