# Generated by Django 5.2.8 on 2026-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0008_alter_alumno2026_dni"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaTemporalAlumno",
            fields=[
                (
                    "numero_de_documento",
                    models.CharField(
                        db_column="numero_de_documento",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cueanexo", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "nombre_institucion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nivel", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_documento",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("apellido", models.CharField(blank=True, max_length=250, null=True)),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("titulacion", models.CharField(blank=True, max_length=255, null=True)),
                ("anio", models.CharField(blank=True, max_length=50, null=True)),
                ("seccion", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "estado_inscripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ciclo_lectivo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": '"diagnostico_2026"."tabla_temporal_alumno"',
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="matematica2026",
            name="pregunta_11",
            field=models.CharField(
                choices=[("10,5", "10,5"), ("7", "7"), ("3,5", "3,5"), ("0", "0")],
                max_length=10,
                null=True,
            ),
        ),
    ]
