# Generated by Django 5.2.8 on 2026-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0010_tablatemporalalumnofluidez2026_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamenLenguaAlumno",
            fields=[
                ("cueanexo", models.CharField(blank=True, max_length=128, null=True)),
                ("escuela", models.CharField(blank=True, max_length=128, null=True)),
                ("ambito", models.CharField(blank=True, max_length=128, null=True)),
                ("sector", models.CharField(blank=True, max_length=128, null=True)),
                ("localidad", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "dni",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("apellidos", models.CharField(blank=True, max_length=128, null=True)),
                ("nombres", models.CharField(blank=True, max_length=128, null=True)),
                ("anio", models.CharField(blank=True, max_length=128, null=True)),
                ("division", models.CharField(blank=True, max_length=128, null=True)),
                ("region", models.CharField(blank=True, max_length=128, null=True)),
                ("p1", models.CharField(blank=True, max_length=128, null=True)),
                ("p2", models.CharField(blank=True, max_length=128, null=True)),
                ("p3", models.CharField(blank=True, max_length=128, null=True)),
                ("p4", models.CharField(blank=True, max_length=128, null=True)),
                ("p5", models.CharField(blank=True, max_length=128, null=True)),
                ("p6", models.CharField(blank=True, max_length=128, null=True)),
                ("p7", models.CharField(blank=True, max_length=128, null=True)),
                ("p8", models.CharField(blank=True, max_length=128, null=True)),
                ("p9", models.CharField(blank=True, max_length=128, null=True)),
                ("p10", models.CharField(blank=True, max_length=128, null=True)),
                ("p11", models.CharField(blank=True, max_length=128, null=True)),
                ("p12", models.CharField(blank=True, max_length=128, null=True)),
                ("p13", models.CharField(blank=True, max_length=128, null=True)),
                ("p14", models.CharField(blank=True, max_length=128, null=True)),
                ("p15", models.CharField(blank=True, max_length=128, null=True)),
                ("p16", models.CharField(blank=True, max_length=128, null=True)),
                ("total", models.CharField(blank=True, max_length=128, null=True)),
                ("extraer", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "interpretar",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "reflexionar_evaluar",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "escribir",
                    models.CharField(
                        blank=True, db_column="Escribir", max_length=128, null=True
                    ),
                ),
                (
                    "discapacidad",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("etnia", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": '"diagnostico_2026"."examen_lengua_alumnos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamenMatematicaAlumno",
            fields=[
                ("cueanexo", models.CharField(blank=True, max_length=128, null=True)),
                ("escuela", models.CharField(blank=True, max_length=128, null=True)),
                ("ambito", models.CharField(blank=True, max_length=128, null=True)),
                ("sector", models.CharField(blank=True, max_length=128, null=True)),
                ("localidad", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "dni",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("apellidos", models.CharField(blank=True, max_length=128, null=True)),
                ("nombres", models.CharField(blank=True, max_length=128, null=True)),
                ("anio", models.CharField(blank=True, max_length=128, null=True)),
                ("division", models.CharField(blank=True, max_length=128, null=True)),
                ("region", models.CharField(blank=True, max_length=128, null=True)),
                ("p1", models.CharField(blank=True, max_length=50, null=True)),
                ("p2", models.CharField(blank=True, max_length=50, null=True)),
                ("p3", models.CharField(blank=True, max_length=50, null=True)),
                ("p4", models.CharField(blank=True, max_length=50, null=True)),
                ("p5", models.CharField(blank=True, max_length=50, null=True)),
                ("p6", models.CharField(blank=True, max_length=50, null=True)),
                ("p7", models.CharField(blank=True, max_length=50, null=True)),
                ("p8", models.CharField(blank=True, max_length=50, null=True)),
                ("p9", models.CharField(blank=True, max_length=50, null=True)),
                ("p10", models.CharField(blank=True, max_length=50, null=True)),
                ("p11", models.CharField(blank=True, max_length=50, null=True)),
                ("p12", models.CharField(blank=True, max_length=50, null=True)),
                ("p13", models.CharField(blank=True, max_length=50, null=True)),
                ("p14", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reconocimiento_conceptos",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "comunicacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resolucion_situaciones",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "discapacidad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("etnia", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": '"diagnostico_2026"."examen_matematica_alumnos"',
                "managed": False,
            },
        ),
    ]
