# Generated by Django 5.2.14 on 2026-08-17 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0011_examenlenguaalumno_examenmatematicaalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_localidad', models.CharField(blank=True, max_length=20, null=True)),
                ('regional', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_cabecera', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_cabecera', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_area_cabecera', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_cabecera', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_coordinador', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_coordinador', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_area_coordinador', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_coordinador', models.CharField(blank=True, max_length=30, null=True)),
                ('cuil_coordinador', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_establecimientos_asociados', models.IntegerField(default=0)),
                ('cantidad_secciones_asociadas', models.IntegerField(default=0)),
                ('cantidad_matriculas_por_seccion', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cabecera',
                'verbose_name_plural': 'Cabeceras',
                'db_table': '"validaciones_2026"."cabeceras"',
            },
        ),
        migrations.CreateModel(
            name='ValReferenteCargaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Referente de Carga Temporal',
                'verbose_name_plural': 'Referentes de Carga Temporal',
                'db_table': '"validaciones_2026"."referentes_carga_temporal"',
            },
        ),
        migrations.CreateModel(
            name='ValEstablecimiento',
            fields=[
                ('cueanexo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('escuela', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('codigo_provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_localidad', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_area', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_director', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_director', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_director', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_director', models.EmailField(blank=True, max_length=255, null=True)),
                ('participa_aprender', models.CharField(choices=[('PARTICIPA', 'Participa'), ('NO PARTICIPA', 'No participa'), ('SIN VALIDAR PARTICIPACION', 'Sin validar participación')], default='SIN VALIDAR PARTICIPACION', help_text="'participa' | 'no participa' | 'sin validar participación'", max_length=30, verbose_name='Participa en Aprender')),
                ('carga_completa', models.BooleanField(default=False, help_text='True cuando el referente confirmó que terminó de cargar todas las secciones', verbose_name='Carga completa')),
                ('motivo_no_participa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de no participación')),
                ('cabecera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos', to='evaluaciones_educativas.valcabecera', verbose_name='Cabecera asignada')),
            ],
            options={
                'verbose_name': 'Establecimiento (Validaciones)',
                'verbose_name_plural': 'Establecimientos (Validaciones)',
                'db_table': '"validaciones_2026"."establecimientos"',
            },
        ),
        migrations.CreateModel(
            name='ValGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cueanexo', models.CharField(max_length=9)),
                ('nombre_grado', models.CharField(choices=[('3er Año/Grado', '3er Año/Grado')], default='3er Año/Grado', max_length=50)),
                ('estado_carga', models.BooleanField(default=False)),
                ('grado_creado', models.BooleanField(default=False, verbose_name='Grado creado manualmente')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='evaluaciones_educativas.valestablecimiento')),
            ],
            options={
                'verbose_name': 'Grado (Validaciones)',
                'verbose_name_plural': 'Grados (Validaciones)',
                'db_table': '"validaciones_2026"."grados"',
            },
        ),
        migrations.CreateModel(
            name='ValHistorialCambiosEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(verbose_name='Justificación de participación')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='evaluaciones_educativas.valestablecimiento')),
                ('referente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_establecimientos_modificados', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Establecimiento',
                'verbose_name_plural': 'Historial de Cambios de Establecimiento',
                'db_table': '"validaciones_2026"."historial_cambios_establecimiento"',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ValSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seccion', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('Z', 'Z')], max_length=20)),
                ('turno', models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('MAÑANA EXTENDIDA', 'Mañana Extendida'), ('TARDE', 'Tarde'), ('TARDE EXTENDIDA', 'Tarde Extendida'), ('DOBLE', 'Doble'), ('VESPERTINO', 'Vespertino')], max_length=20)),
                ('matricula', models.IntegerField(blank=True, null=True, verbose_name='Matrícula cargada')),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('SIN_MATRICULA', 'Sin matrícula'), ('MODIFICADO', 'Modificado'), ('DESHABILITADO', 'Deshabilitado')], default='PENDIENTE', max_length=15, verbose_name='Estado de validación')),
                ('motivo_deshabilitacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de deshabilitación')),
                ('seccion_creada', models.BooleanField(default=False, verbose_name='Sección creada manualmente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluaciones_educativas.valgrado')),
            ],
            options={
                'verbose_name': 'Sección (Validaciones)',
                'verbose_name_plural': 'Secciones (Validaciones)',
                'db_table': '"validaciones_2026"."secciones"',
                'unique_together': {('seccion', 'grado', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='ValHistorialMatriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_anterior', models.IntegerField(blank=True, null=True)),
                ('matricula_nueva', models.IntegerField(blank=True, null=True)),
                ('justificacion', models.TextField(verbose_name='Justificación del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_cambio', models.CharField(blank=True, max_length=50, null=True)),
                ('referente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_matriculas_modificadas', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_matriculas', to='evaluaciones_educativas.valseccion')),
            ],
            options={
                'verbose_name': 'Historial de Matrícula',
                'verbose_name_plural': 'Historial de Matrículas',
                'db_table': '"validaciones_2026"."historial_matriculas"',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
