# Generated by Django 5.2.17 on 2026-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "evaluaciones_educativas",
            "0012_valcabecera_valreferentecargatemporal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="seccionfluidez2026",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOBLE", "Doble"),
                    ("DOBLE EXTENDIDA", "Doble Extendida"),
                    ("MAÑANA", "Mañana"),
                    ("MAÑANA EXTENDIDA", "Mañana Extendida"),
                    ("TARDE", "Tarde"),
                    ("TARDE EXTENDIDA", "Tarde Extendida"),
                    ("VESPERTINO", "Vespertino"),
                ],
                max_length=20,
            ),
        ),
    ]
