# Generated by Django 5.2.17 on 2026-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0013_update_turno_choices_fluidez2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seccionfluidez2026",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Doble", "Doble"),
                    ("Doble Extendida", "Doble Extendida"),
                    ("Mañana", "Mañana"),
                    ("Mañana Extendida", "Mañana Extendida"),
                    ("Tarde", "Tarde"),
                    ("Tarde Extendida", "Tarde Extendida"),
                    ("Vespertino", "Vespertino"),
                ],
                max_length=20,
            ),
        ),
    ]
