# Generated by Django 5.2.14 on 2026-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0014_alter_seccionfluidez2026_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalCargaTabuladoresFluidez2026Eliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('tabuladores_permitidos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '"datos_oficiales"."temporal_carga_tabuladores_fluidez_2026_eliminar"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabuladoresFluidezOctubre2026',
            fields=[
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('cuil', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=250, null=True)),
                ('celular', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('lista_cueanexos', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': '"datos_oficiales"."tabuladores_fluidez_octubre_2026"',
            },
        ),
    ]
