# Generated by Django 5.2.17 on 2026-09-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "evaluaciones_educativas",
            "0015_temporalcargatabuladoresfluidez2026eliminar_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ValPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cuil", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
            ],
            options={
                "db_table": '"validaciones_2026"."personas"',
            },
        ),
        migrations.CreateModel(
            name="ValAplicador",
            fields=[
                (
                    "valpersona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evaluaciones_educativas.valpersona",
                    ),
                ),
                (
                    "seccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicadores",
                        to="evaluaciones_educativas.valseccion",
                    ),
                ),
            ],
            options={
                "db_table": '"validaciones_2026"."aplicadores"',
            },
            bases=("evaluaciones_educativas.valpersona",),
        ),
        migrations.CreateModel(
            name="ValVeedor",
            fields=[
                (
                    "valpersona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evaluaciones_educativas.valpersona",
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veedores",
                        to="evaluaciones_educativas.valestablecimiento",
                    ),
                ),
            ],
            options={
                "db_table": '"validaciones_2026"."veedores"',
            },
            bases=("evaluaciones_educativas.valpersona",),
        ),
    ]
