# Generated by Django 5.2.17 on 2026-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0016_valpersona_valaplicador_valveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="valpersona",
            name="codigo_area",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="valpersona",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
