# Generated by Django 5.2.17 on 2026-09-24 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "evaluaciones_educativas",
            "0017_valpersona_codigo_area_alter_valpersona_telefono",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="valpersona",
            old_name="telefono",
            new_name="numero_telefono",
        ),
    ]
