# Generated by Django 5.2.17 on 2026-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0018_rename_telefono_valpersona_numero_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valpersona",
            name="cuil",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
