# Generated by Django 5.2.17 on 2026-10-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0020_valveedor_asistente_veedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="AplicadoresFluidezOctubre2026",
            fields=[
                (
                    "cuil",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("apellido", models.CharField(max_length=250)),
                ("nombre", models.CharField(max_length=250)),
                ("correo", models.EmailField(blank=True, max_length=250, null=True)),
                ("celular", models.CharField(blank=True, max_length=20, null=True)),
                ("region", models.CharField(max_length=100)),
            ],
            options={
                "db_table": '"datos_oficiales"."aplicadores_fluidez_octubre_2026"',
            },
        ),
        migrations.CreateModel(
            name="SeccionesAplicadorFluidezOctubre2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_seccion", models.BigIntegerField(unique=True)),
                ("id_institucion", models.BigIntegerField()),
                ("cueanexo", models.CharField(max_length=15)),
                ("c_grado_nivel_servicio", models.BigIntegerField()),
                ("anio_grado", models.CharField(blank=True, max_length=50, null=True)),
                ("turno", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ciclo_lectivo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "aplicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secciones",
                        to="evaluaciones_educativas.aplicadoresfluidezoctubre2026",
                    ),
                ),
            ],
            options={
                "db_table": '"datos_oficiales"."secciones_aplicadores_fluidez_octubre_2026"',
            },
        ),
    ]
