# Generated by Django 4.2.5 on 2024-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchMapas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("archivo", models.FileField(upload_to="mapoteca/")),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
