# Generated by Django 5.1.1 on 2025-03-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, unique=True)),
                (
                    "apellido",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombres")),
                (
                    "grado",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=1,
                        verbose_name="Año",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                        ],
                        max_length=2,
                        verbose_name="División",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MAÑANA", "MAÑANA"),
                            ("TARDE", "TARDE"),
                            ("VESPERTINO", "VESPERTINO"),
                        ],
                        max_length=25,
                        verbose_name="Turno",
                    ),
                ),
                ("cueanexo", models.CharField(max_length=9, verbose_name="Cueanexo")),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "db_table": "Alumnos",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("puntaje", models.IntegerField()),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorías",
                "db_table": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("escuela", models.CharField(max_length=9, verbose_name="Cueanexo")),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examenes",
                "db_table": "Examenes",
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("opcion_unica", "Opción Única"),
                            ("agrupada", "Agrupada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(blank=True, to="operativoschaco.categoria"),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "db_table": "Preguntas",
            },
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("puntaje", models.IntegerField()),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="operativoschaco.pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opcion",
                "verbose_name_plural": "Opciones",
                "db_table": "Opcion",
            },
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("puntaje", models.IntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="operativoschaco.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoria",
                "verbose_name_plural": "Subcategorias",
                "db_table": "Subcategorias",
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni_alumno", models.CharField(max_length=8, verbose_name="DNI")),
                (
                    "alumno_apellido",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "alumno_nombre",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                ("puntaje", models.IntegerField(verbose_name="Puntaje")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.categoria",
                        verbose_name="Categorías",
                    ),
                ),
                (
                    "opcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.opcion",
                        verbose_name="Opciones",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.pregunta",
                        verbose_name="Pregunta",
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.subcategoria",
                        verbose_name="Subcategorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "db_table": "Respuestas",
            },
        ),
    ]
