# Generated by Django 5.1.1 on 2025-03-26 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="puntaje",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Puntaje"
            ),
        ),
        migrations.AlterField(
            model_name="opcion",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="operativoschaco.pregunta",
                verbose_name="Pregunta",
            ),
        ),
        migrations.AlterField(
            model_name="opcion",
            name="puntaje",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Puntaje"
            ),
        ),
        migrations.AlterField(
            model_name="opcion",
            name="texto",
            field=models.CharField(max_length=255, verbose_name="Texto"),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, to="operativoschaco.categoria", verbose_name="Categorias"
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="texto",
            field=models.TextField(verbose_name="texto"),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="tipo",
            field=models.CharField(
                choices=[("opcion_unica", "Opción Única"), ("agrupada", "Agrupada")],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="respuesta",
            name="puntaje",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Puntaje"
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="operativoschaco.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="puntaje",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Puntaje"
            ),
        ),
    ]
