# Generated by Django 5.1.1 on 2025-03-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción",
                "verbose_name_plural": "Opciones",
                "db_table": "Opcion",
            },
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="opciones",
        ),
        migrations.AlterField(
            model_name="respuesta",
            name="opcion_seleccionada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operativoschaco.opcion",
                verbose_name="Opción Seleccionada",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="opciones",
            field=models.ManyToManyField(
                related_name="preguntas",
                to="operativoschaco.opcion",
                verbose_name="Opciones",
            ),
        ),
    ]
