# Generated by Django 5.1.1 on 2025-03-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0002_opcion_remove_pregunta_opciones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "Categoria",
            },
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="opcion_seleccionada",
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="puntaje",
        ),
        migrations.AddField(
            model_name="respuesta",
            name="opciones_seleccionadas",
            field=models.JSONField(default=list, verbose_name="Opciones Seleccionadas"),
        ),
        migrations.AddField(
            model_name="opcion",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="operativoschaco.categoria",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, related_name="preguntas", to="operativoschaco.categoria"
            ),
        ),
    ]
