# Generated by Django 5.1.1 on 2025-03-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativoschaco",
            "0002_alter_categoria_nombre_alter_categoria_puntaje_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="respuesta",
            name="subcategoria",
        ),
        migrations.AddField(
            model_name="respuesta",
            name="subcategorias",
            field=models.ManyToManyField(
                blank=True,
                to="operativoschaco.subcategoria",
                verbose_name="Subcategorías",
            ),
        ),
    ]
