# Generated by Django 5.1.1 on 2025-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativoschaco",
            "0003_categoria_remove_respuesta_opcion_seleccionada_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "puntaje_maximo",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje Máximo"
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preguntasM",
                        to="operativoschaco.categoria",
                    ),
                ),
                (
                    "opciones",
                    models.ManyToManyField(
                        related_name="preguntasM",
                        to="operativoschaco.opcion",
                        verbose_name="Opciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta_Matematica",
                "verbose_name_plural": "Preguntas_Matematicas",
                "db_table": "Pregunta_Matematica",
            },
        ),
    ]
