# Generated by Django 5.1.1 on 2025-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0003_remove_respuesta_subcategoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntasporArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_area", models.IntegerField(verbose_name="Código Área")),
                ("cod_pregunta", models.IntegerField(verbose_name="Código Pregunta")),
                (
                    "texto_pregunta",
                    models.CharField(
                        max_length=255, verbose_name="Texto de la Pregunta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta_Area",
                "verbose_name_plural": "Preguntas_Areas",
                "db_table": "Preguntas_areas",
            },
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="puntaje",
        ),
        migrations.AddField(
            model_name="respuesta",
            name="puntaje_agrupada",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=4,
                verbose_name="Puntaje Agrupada",
            ),
        ),
        migrations.AddField(
            model_name="respuesta",
            name="puntaje_opcion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=4,
                verbose_name="Puntaje Opción Única",
            ),
        ),
    ]
