# Generated by Django 5.1.1 on 2025-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0004_preguntasporarea_remove_respuesta_puntaje_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionesRespuestasAreas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_arearesp", models.IntegerField(verbose_name="Código Área")),
                (
                    "cod_pregunta_resp",
                    models.IntegerField(verbose_name="Código Pregunta"),
                ),
                ("opciones", models.CharField(max_length=255, verbose_name="Opciones")),
                (
                    "puntaje",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Puntaje"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opcion_Respuesta",
                "verbose_name_plural": "Opciones_Respuestas",
                "db_table": "Opciones_Respuestas",
            },
        ),
    ]
