# Generated by Django 5.1.1 on 2025-03-31 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0004_preguntam"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamenAlumnoCueanexoM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_examen", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.alumnossecundaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Alumno Matematica",
                "verbose_name_plural": "Exámenes Alumnos Matematicas",
                "db_table": "Examen_Alumno_Cueanexo_M",
            },
        ),
        migrations.CreateModel(
            name="RespuestaM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opciones_seleccionadas",
                    models.JSONField(
                        default=list, verbose_name="Opciones Seleccionadas"
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.examenalumnocueanexom",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operativoschaco.preguntam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Matematica",
                "verbose_name_plural": "Respuestas Matematicas",
                "db_table": "Respuesta_Matematica",
            },
        ),
    ]
