# Generated by Django 5.1.1 on 2025-03-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0005_opcionesrespuestasareas"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcionesrespuestasareas",
            name="tipo_opcion",
            field=models.CharField(
                default="unico", max_length=50, verbose_name="Tipo Opción"
            ),
        ),
    ]
