# Generated by Django 5.1.1 on 2025-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operativoschaco", "0005_examenalumnocueanexom_respuestam"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnossecundaria",
            name="anio",
            field=models.CharField(default=1, max_length=25, verbose_name="Año"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumnossecundaria",
            name="division",
            field=models.CharField(default=1, max_length=5, verbose_name="División"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alumnossecundaria",
            name="region",
            field=models.CharField(default=1, max_length=25, verbose_name="Regional"),
            preserve_default=False,
        ),
    ]
