# Generated by Django 5.1.1 on 2025-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operativoschaco",
            "0006_alumnossecundaria_anio_alumnossecundaria_division_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreCargaL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=9)),
                ("fecha_cierre", models.DateTimeField(auto_now_add=True)),
                ("total_registros", models.PositiveIntegerField()),
            ],
        ),
    ]
