# Generated by Django 4.2.5 on 2024-05-07 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="rooms_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
