# Generated by Django 4.2.5 on 2024-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.CharField(verbose_name="Mensaje"),
        ),
    ]
