# Generated by Django 4.2.5 on 2024-05-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="manager_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rooms",
                to="chat.manager",
            ),
        ),
    ]
